### ISSUE TITLE
ios ipad fullscreen bug 

### ISSUE THREAD

**Issue by supersh86** [openplayerjs/openplayerjs#10]
https://www.openplayerjs.com/embed.html?file=https%3A%2F%2Fcommondatastorage.googleapis.com%2Fgtv-videos-bucket%2Fsample%2FTearsOfSteel.mp4&type=video

Hi, I found a critical bug on my old ipad mini 2 ios 12.

In chromium and safari, the full-screen mode in landscape mode does not work correctly.

Also, the control menu is too small for interaction, and seek does not work.

![Imgur](https://i.imgur.com/fdakPbs.jpg)

![Imgur](https://i.imgur.com/8XLN8H2.jpg)

**Comment by rafa8626** [comment]
I don't have iOS 12; however, I added a minor fix for the fullscreen effect. Can you confirm, please. I'll investigate the issue with the seek behavior

**Comment by supersh86** [comment]
In the safari the problem is solved.
In chrome, it does not go into full-screen mode at all

**Comment by rafa8626** [comment]
in iPhone?

**Comment by supersh86** [comment]
Yes in Ipad

**Comment by rafa8626** [comment]
@supersh86 Please download the master branch and test this. Read also the commit comments, since it has bigger changes you should be aware of, including native support in iOS for fullscreen. Let me know if all the issues you had in iPad are solved.

**Comment by supersh86** [comment]
Good morning Rafa!
I see you did a native full-screen mode.
That's just advertising is not played))

**Comment by rafa8626** [comment]
Thanks for the feedback. I'll check that later tomorrow

**Comment by rafa8626** [comment]
I just pushed a last fix for the time rail and Ads on iPad; please download the master branch and let me know if it works better for you. Thanks

**Comment by rafa8626** [comment]
Is this issue good to be closed?

**Comment by rafa8626** [comment]
is this an issue on the website only? I have tested the player with the demo file and the only thing I did experienced in Safari was a little delay but I was able to play it

**Comment by rafa8626** [comment]
@supersh86 I've refactor most of the Ads workflow to make them more effective and mobile-friendly. If you want to test this, please check the master branch and let me know if it works for you. Thanks for your feedback
