### ISSUE TITLE
Second and next vasts aren't displayed

### ISSUE THREAD

**Issue by xel23** [openplayerjs/openplayerjs#101]
Hello!
The problem is: if I use several vast/vpaid, the second one and next vast/vpaid(s) aren't displayed correctly. It seems that ads are showed under main media content.
First screen of media freezes and ad is played with visability 0%. I've decided about it because I can catch event whith is sent by player.

Besides, there is the red line for progress instead yellow (like for ads).
![image](https://user-images.githubusercontent.com/33120394/68544373-91f5a880-03d3-11ea-9f64-fa9579b7a925.png)

Probably, I pass several vast incorrectly?
I use construction as below:
```
var player = new OpenPlayer('video', ['url1', 'url2']);
player.init();
```

**Comment by rafa8626** [comment]
@xel23 can you provide me a CodePen so I can check the problem please?

**Comment by xel23** [comment]
@rafa8626 
https://codepen.io/xel23/pen/pooZjdL

**Comment by rafa8626** [comment]
@xel23 thanks I’ll take a look at this and get back to you as soon as I can

**Comment by rafa8626** [comment]
@xel23 this issue seems to be fixed now; please test the master branch and let me know if it works for you. After that, this will be put for the oncoming release candidate

**Comment by xel23** [comment]
@rafa8626 Thanks for your work. It seems ads start switching. But some another problem is appered:
There is unhandled exception if no ads or incorrect ad format
![image](https://user-images.githubusercontent.com/33120394/68693283-0c672980-0588-11ea-84cd-5f445fa7b158.png)

![image](https://user-images.githubusercontent.com/33120394/68693318-20129000-0588-11ea-8c70-8776867a698a.png)

**Comment by rafa8626** [comment]
@xel23 let me take a look and get back to you

**Comment by rafa8626** [comment]
@xel23 it's fixed my bad there was a typo in the code but it's good now. Let me know if everything else is fine

**Comment by xel23** [comment]
@rafa8626 Yes. For now everything about these problems is ok. Thank you!

**Comment by rafa8626** [comment]
Thank you for reporting this
