### ISSUE TITLE
macOS Safari - autoplay not working properly

### ISSUE THREAD

**Issue by nickcuper** [openplayerjs/openplayerjs#109]
macOS Catalina 10.15.2

Autoplay not working in Safari browser, i have tested for few different providers (akamai, ngenix)

`
Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
(anonymous function)
rejectPromise
play
value — hls.js:1:215689
(anonymous function) — hls.js:1:310640
promiseReactionJob
`

**Comment by rafa8626** [comment]
Thanks for bringing this to my attention @nickcuper I'll take a look at it and get you back. Can you star the project to show your support, please?

**Comment by nickcuper** [comment]
@rafa8626 thanks, of course, np
Im not sure 100% but problem might be with video element 
looks like you delete current media element and create new one

existing tag 
`
 <video id="video" autoplay muted playsinline class="op-player__media op-levels__option"></video>
`

After player initialisation it looks 
`
<video muted="" playsinline="" class="op-player__media op-levels__option" src="blob:https://mono.betgames.local/2b0f89a8-92b4-44e1-99aa-1e827c42ab0e" op-live="true"><source src="{somesrchere}"></video>
`

The difference in `autoplay` attr 

Also found small bug (not critical)
even for ios/macos/ipad you load hls.js but it not necessary
ios/macos/ipad - can play hls native

**Comment by rafa8626** [comment]
@nickcuper please test the master branch and let me know if it works for you. If so, this will be part of the next release. Thanks

**Comment by nickcuper** [comment]
@rafa8626 i have tried it for v1.14.3 and v1.14.2 and it not working

**Comment by rafa8626** [comment]
Download the master branch and test it with it since I haven’t released the fix yet

**Comment by nickcuper** [comment]
@rafa8626 ok, will try that

**Comment by nickcuper** [comment]
well, i have checked master https://github.com/openplayerjs/openplayerjs/commit/60a0a73c9773b04c8713155475bc17ddb4ac30da

autoplay for safari still not working

good news, you have fixed unnecessary load hls.js - well done, perfect

and looks like i figure out how to fix for safari/ios 
it works for me, i have tested for macOS, iOS (10,11,12,13), iPad (12, 11)

```js
import { IS_IOS, IS_SAFARI } from './constants';
...
export function isAutoplaySupported(media: HTMLMediaElement, autoplay: (n: any) => any, muted: (n: any) => any, callback: () => any): void {
    const playPromise = media.play();
    if (playPromise !== undefined) {
        playPromise.then(() => {
            // Umuted autoplay works.
            media.pause();
            autoplay(true);
           // Autoplay with sound not will be working for IOS, macOS
           // Apple has strict policy about that
            muted((IS_IOS || IS_SAFARI)); 
            callback();
        }).catch(() => {
            // Unmuted autoplay failed. New attempt with muted autoplay.
            media.volume = 0;
            media.muted = true;
            media.play().then(() => {
                // Muted autoplay works.
                media.pause();
                autoplay(true);
                muted(true);
                callback();
            }).catch(() => {
                // Both muted and unmuted autoplay failed. Fallback to click to play.
                media.volume = 1;
                media.muted = false;
                autoplay(false);
                muted(false);
                callback();
            });
        });
    } else {
        autoplay(!media.paused || 'Promise' in window && playPromise instanceof Promise);
        media.pause();
        muted(false);
        callback();
    }
}
```

**Comment by rafa8626** [comment]
How did you figure out the fix? I see the code but I can’t figure out where is the change

**Comment by rafa8626** [comment]
Oh I see it now. Let me change this so you can test it once more

**Comment by rafa8626** [comment]
@nickcuper ready; please download the latest version of master and test once more. Thanks for the catch on the autoplay method

**Comment by nickcuper** [comment]
@rafa8626 i have tested latest version, it works for iOS devices (in normal mode)

Also i found the same issue for old Android 4.4 (native browser) Android 5 (samsung browser)
All iOS devices (in low power mode) are affected by this bug also.

So, that mean our solution is not so good it covers just some range of devices.

I digged more deeply in logic `isAutoplaySupported` and found interesting thing

```js
playPromise.then(() => {
     ...
     // callback function is throws exceptions which never handle here, 
     // that the reason why autoplay not working for iOS/macOS and for another specific cases
     callback();
}).catch(() => {
      // it will never triggered this part
         ...
});
```

Now, about iOS devices (in low power mode) - it not possible to play video you have to show play button

And one more suggestion from my side: as i noticed player does not considered muted attribute for video tag, imho the better solution will be considered that attribute or add some config for that

About `playPromise` i have fixed this bug and i will try to create pull request at monday (i have tested it for ios 10,11,12,13 and android 4.4, 5,6,7,8)

**Comment by rafa8626** [comment]
@nickcuper thanks for your help, once you submit the PR I'll review it

**Comment by rafa8626** [comment]
@nickcuper what’s missing is to enclose this callback into a try/catch block correct?

**Comment by rafa8626** [comment]
@nickcuper I added one more piece that included try/catch across that method to try to execute the `catch` parts. Please test the master brach and let me know if it worked for you

**Comment by rafa8626** [comment]
@nickcuper any updates on this? Have you had a chance to test the new update in master?

**Comment by nickcuper** [comment]
hello @rafa8626 
sorry for long response
checking ur fix

**Comment by rafa8626** [comment]
thanks @nickcuper keep me posted

**Comment by nickcuper** [comment]
checked, it not working

**Comment by rafa8626** [comment]
can you indicate me how did you fix this on your end, please? I may be able to update it on my side in a little bit

**Comment by nickcuper** [comment]
https://github.com/openplayerjs/openplayerjs/pull/110

**Comment by rafa8626** [comment]
@nickcuper thanks I’ll review it shortly; are you gonna include the Ads fix in this PR? Or should I wait for another PR?

**Comment by rafa8626** [comment]
Thanks @nickcuper I added my comments on the PR

**Comment by rafa8626** [comment]
Fixed by #110

**Comment by rafa8626** [comment]
@nickcuper quick question: have you experienced issues with your fix using Ads? I've seen some inconsistencies but I wanted to confirm if it plays Ads, and then automatically starts the media

**Comment by nickcuper** [comment]
@rafa8626 Hi, i didnt
But i can check later on

**Comment by rafa8626** [comment]
@nickcuper yes please I’d appreciate it if you could help me with that. Keep me posted about it

**Comment by rafa8626** [comment]
@nickcuper any updates about this?

**Comment by nickcuper** [comment]
@rafa8626 hey, I have checked it’s work for me
But I noticed problem with Adblock extension, if user enable Adblock - ads not working 
Could you provide please more info for me, thanks

**Comment by rafa8626** [comment]
@nickcuper the issue that I described above is related to mobile devices not in desktop; can you verify that as well please? As per the Ads blocker it is expected since it overrides URLs based on patterns that Ads use. Let me know if you found issues on mobile

**Comment by rafa8626** [comment]
@nickcuper I confirm that there are issues when using mobile; I tried opening the OpenPlayerJS website in an iPhone 8. I tried to play the video, and first, the Ads play, but then it doesn't switch to the video. Can you look at that please? This seemed to start happening after the fix for this issue got introduced

**Comment by rafa8626** [comment]
@nickcuper I found out that the error I saw came from an earlier release so it has nothing to do with the fix you implemented. Thanks anyway
