### ISSUE TITLE
Add to the player settings the rewind time

### ISSUE THREAD

**Issue by supersh86** [openplayerjs/openplayerjs#11]
Hi
Many users ask me to reduce the time rewind time using the arrow keys.
I suggest adding a setting responsible for this.

**Comment by rafa8626** [comment]
Can you provide an live example of this please?

**Comment by supersh86** [comment]
You just press the keyboard left and right. And the current time is changing.
At the moment, it moves for too long, more than a minute.

I suggest that this time be changed in the settings

**Comment by rafa8626** [comment]
@supersh86 Please download the master branch and test this. You can set now a `step` configuration item that it will skip/rewind X number of seconds (you can use decimals as well):
```javascript
new OpenPlayer('VIDEO ID', ..., {
     step: 2 // 2 seconds
});
```
it will skip 2 seconds or rewind 2 seconds.

**Comment by supersh86** [comment]
Thanks! Close issues
