### ISSUE TITLE
hls quality switch and rewind ,forward button

### ISSUE THREAD

**Issue by bhmtech** [openplayerjs/openplayerjs#116]

**Comment by rafa8626** [comment]
@bhmtech the quality switch is already available using the `levels` option in the `controls` settings. As per the other 2 buttons they could be included as part of the core player, but you have the option to create them as well. For more information, take a look at the README file in the project

**Comment by rahulrsingh09** [comment]
@rafa8626 Can you please help with a small snippet here i was trying in this codepen but was unable to get the quality picker 
https://codepen.io/rafa8626/pen/QZWEVy

**Comment by rafa8626** [comment]
@rahulrsingh09 I noticed that your media doesn’t play correctly; maybe it’s a n issue with CORS and that’s why it doesn’t parse the manifest correctly

**Comment by rahulrsingh09** [comment]
@rafa8626 but it's an open test hls url i doubt it will have cors

**Comment by rafa8626** [comment]
@rahulrsingh09 interesting; the source doesn't play in iOS, just FYI; I'll check on desktop your issue

**Comment by rafa8626** [comment]
@rahulrsingh09 I know why: `levels` control is not set by default; you have to manually activate it. If you add in your config:
```javascript
controls: {
    right: ['settings', 'levels', 'fullscreen']
  },
```
you will see the quality levels coming up. 

As a big favor, please star the project to show your support.
