### ISSUE TITLE
Configurable progressbar for live audio streams

### ISSUE THREAD

**Issue by ampersand83** [openplayerjs/openplayerjs#117]
**Is your feature request related to a problem? Please describe.**
I am locking for a way to make the progressbar appear for live hls audio streams. 
Looking at the code of the setInitialProgress method in openplayer.js I see that the progressbar is set to aria-hidden=true, when a livestream is detected. In our case we have hls livestreams of radio stations that allow to jump back in time for two hours. Hence we need the progressbar to do that.

**Describe the solution you'd like**
It would be nice to offer a configuration option to make the player display a progress bar although a livestream is played. However for a better user experience it would be better if the initial position of the progress indicator in the progressbar was located on the right and not on the left like for on demand content. To go back in time I would have to move the progress indicator to the left. You can see such a behaviour on the [hls.js demo page](https://hls-js.netlify.com/demo/). The only problem here is, that (other than openplayer) they render the audiolivestreams as video elements.

**Comment by rafa8626** [comment]
@ampersand83 thanks for the suggestion; I'll include this configuration item soon so it is released in the oncoming release. Please star the project to show your support

**Comment by rafa8626** [comment]
@ampersand83 could you provide me a URL for one of your streams so I can test the implementation of this please?

**Comment by ampersand83** [comment]
Hi @rafa8626, thank you for your really quick response. I am afraid, that I won't be able to send you that url until monday morning CET. Unfortunately my company is really strict in their security policy so that I don't have access to our internal git repo and hence can't figure out that url.

**Comment by rafa8626** [comment]
@ampersand83 no worries; if you cannot I'll ask to test the master branch on your side. I'll let you know when I have the implementation ready

**Comment by ampersand83** [comment]
One livestream url to test is https://hlsyoufm-i.akamaihd.net/hls/live/1002759/youfm/master.m3u8.

**Comment by rafa8626** [comment]
@ampersand83 please download the branch `feature/show-live-progress` and test it on your side; so far on my end worked as expected. But let me know if you find any issues or something else is missing. To activate it, set the `showLiveProgress` flag as `true` in the configuration. Thanks for the suggestion on this

**Comment by ampersand83** [comment]
@rafa8626 , thank you for the quick implementation. It works as expected but i still found one issue. 

When I start the stream, move the scrollbar in the past and after that move it back to the very right (to get back to the live broadcast), I have to wait for quite some time (5 to 10 seconds) until the stream plays again. Trying that on the hls.js demo page the stream almost immediately plays.
Are you able to reproduce that behaviour as well or is it just a problem at my local computer?

**Comment by rafa8626** [comment]
@ampersand83 can you indicate what url in his.js demo are you using as a reference? I saw that a couple of times in my tests but I thought it was my machine

**Comment by ampersand83** [comment]
Hi @rafa8626 its the url https://hlsyoufm-i.akamaihd.net/hls/live/1002759/youfm/master.m3u8 I mentioned in an earlier comment.

**Comment by rafa8626** [comment]
@ampersand83 gotcha. I'll take a look at it and keep you posted

**Comment by rafa8626** [comment]
@ampersand83 sorry for the delay on this; I may have a chance to complete this early next week. Just FYI

**Comment by ampersand83** [comment]
Ok, Thank you. No worries. Take your time.

**Comment by rafa8626** [comment]
@ampersand83 I think I have this sorted out; please test the branch once more and let me know if it's all good on your end

**Comment by rafa8626** [comment]
@ampersand83 once you confirm this is good to go, I'll merge this and send the release. So I'll wait for your feedback. Thanks

**Comment by ampersand83** [comment]
@rafa8626 Hi,
I checked it again, but unfortunately nothing seems to have changed. When initially pressing the playbutton the stream starts to play immediately. Moving the progressbar to a moment in the past the stream also plays immediately. But if I move the progressbar back to live the stream won't play for quite some time. In Chrome the following error is displayed in the console when I try to move the handle of the progressbar while waiting for the stream to play:
`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().`
Here you can see a small video of the effect. I don't know if that helps.
https://drive.google.com/file/d/1flE03X_JgPzk_XppivLmXJnKk-97EoZV/view

**Comment by rafa8626** [comment]
@ampersand83 I'll re check this since I tried to emulate what the native player does: store the last current time before it was moved to a different position. As far as I tested it was working, but let me check and I'll get back to you

**Comment by rafa8626** [comment]
@ampersand83 ok I fixed the issue with the slider; you should see a smoother transition in the audio when sliding the progress bar. Check the branch and let me know

**Comment by ampersand83** [comment]
Hi @rafa8626  now everything works as expected. You can merge it in the master.
Thanks for your quick response and your great work.

**Comment by rafa8626** [comment]
@ampersand83 Thanks for the suggestion to make this player better. I'll release today

**Comment by rafa8626** [comment]
@ampersand83 do you happen to have a sample URL where I can showcase this feature again please? I checked the URL you provided on this ticket and it doesn't work anymore. Also, I'm working on a feature to autodetect if the streaming is a DVR or not, and that automatically toggles to visibility of the progress bar without any configuration, but I can't find workin samples online

**Comment by ampersand83** [comment]
Hi @rafa8626, oh yeah that url is now outdated. The new one is https://hlsyoufm.akamaized.net/hls/live/2016538/youfm/master.m3u8.

**Comment by rafa8626** [comment]
@ampersand83 awesome! Thanks!
