### ISSUE TITLE
Ads not playing media after they end

### ISSUE THREAD

**Issue by rafa8626** [openplayerjs/openplayerjs#118]
**Describe the bug**
Ads are not playing media once they end in mobile; also, Ads are not playing midroll and postroll in desktop

**To Reproduce**
1. Go to https://openplayerjs.com
2. Click on Play button for video in iPhone 8

**Expected behavior**
Ads should be played and after that, media should automatically play (mobile); if preroll plays, midroll and postroll should play as well

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome 79
 - Version 10.5.2

**Smartphone (please complete the following information):**
 - Device: iPhone8
 - OS: iOS 8
 - Browser Safari
 - Version 13.1

**Comment by Sh1d0w** [comment]
This is still happening for me. What was the solution?

**Comment by Creativ1s** [comment]
Hi, ads are also not playing for me as well on any browser. I'm using a Vue implementation.

**Comment by rafa8626** [comment]
@Creativ1s If you have a CodePen where I can see the issue I’d appreciate it

**Comment by Creativ1s** [comment]
Hi, @rafa8626 I've reused the vue.js code example and added the "ads" object I am using. I've attached a 
 Codepen: [https://codepen.io/Creativ1s/pen/zYwpJxR](https://codepen.io/Creativ1s/pen/zYwpJxR)

The behaviour is the same as our codebase as it ignores the file that's in ads.src value. 
Your assistance would be greatly appreciated.

**Comment by rafa8626** [comment]
@Creativ1s in the CodePen I see that the ad source is an mp3, and it should be an xml source. That’s why it doesn’t work

**Comment by Creativ1s** [comment]
@rafa8626 Understood but I have also tried m3u8 files and I get the following error.

openplayer.min.js:1 GET https://imasdk.googleapis.com/js/sdkloader/ima3.js net::ERR_CONNECTION_RESET
(anonymous) @ VM287 openplayer.min.js:1
t.loadScript @ VM287 openplayer.min.js:1
e @ VM287 openplayer.min.js:1
value @ VM287 openplayer.min.js:1
value @ VM287 openplayer.min.js:1
mounted @ VM289 pen.js:23
callWithErrorHandling @ VM288 vue@next:1429
callWithAsyncErrorHandling @ VM288 vue@next:1438
hook.__weh.hook.__weh @ VM288 vue@next:4177
flushPostFlushCbs @ VM288 vue@next:1626
render @ VM288 vue@next:7010
mount @ VM288 vue@next:5344
app.mount @ VM288 vue@next:10247
(anonymous) @ VM289 pen.js:27
imasdk.googleapis.com/js/sdkloader/ima3.js:1 Failed to load resource: net::ERR_CONNECTION_RESET

Uncaught (in promise) undefined

Test ad: https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8

**Comment by Creativ1s** [comment]
Also in my example, I've used videos but we are actually using the player with audio (HLS) URLs.

**Comment by rafa8626** [comment]
@Creativ1s your confusion is that in the ads configuration part you are setting a source that is not an xml file or string (which is the format for VAST or VPAID). If you change `ads: { src: ` with a sample from https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags, you will see that they play just fine. The player needs a VAST/VPAID/VMAP resource to play Ads, since the ads definition is inside that xml file
