### ISSUE TITLE
Support React with Server Side Render

### ISSUE THREAD

**Issue by meotimdihia** [openplayerjs/openplayerjs#119]
Example with video.js  
https://github.com/zeit/next.js/tree/canary/examples/with-videojs  
I can't get openplayerjs work with next.js.

**Comment by rafa8626** [comment]
@meotimdihia thanks for raising this issue; I'll check this and let you know my findings. Please star the project to show your support

**Comment by rafa8626** [comment]
@meotimdihia can you post a CodePen showing the issue please? It would be easier for me to debug the root of the issue if I can see an example of it

**Comment by meotimdihia** [comment]
https://codesandbox.io/s/cranky-jepsen-uu6b5?fontsize=14&hidenavigation=1&theme=dark

Hi, Try to access the link `Openplayer` in demo. It will work when render in client. But when you refresh the browser for SSR render, you will get the error: `Unhandled Rejection (ReferenceError): window is not defined`

**Comment by rafa8626** [comment]
@meotimdihia thanks; I know now why it doesn't work. If you change your effect to mimic a `componentDidMount`:
```javascript
useEffect(() => {
    var player = new OpenPlayer("my-player");
    player.init();
  }, []);
```
I see it working properly in your code after i did that change. According to Next.js:

> Next.js is universal, which means it executes code first server-side, then client-side. The window object is only present client-side, so if you absolutely need to have access to it in some React component, you should put that code in componentDidMount. This lifecycle method will only be executed on the client. You may also want to check if there isn't some alternative universal library which may suit your needs.

**Comment by meotimdihia** [comment]
Hi, can you share the code link on how to make it works? I don't get this part.

**Comment by rafa8626** [comment]
@meotimdihia I used your same CodeSanbox and it's working for me as is

**Comment by meotimdihia** [comment]
@rafa8626 : I post a video for this bug again in the case you mistake it:
![2020-02-21_21-11-58](https://user-images.githubusercontent.com/300961/75041285-dc1c1900-54ee-11ea-8208-ba85135089fc.gif)

**Comment by rafa8626** [comment]
@meotimdihia thanks, I'll check this in a bit

**Comment by rafa8626** [comment]
@meotimdihia I finally figured out the issues; check this https://codesandbox.io/s/vigorous-almeida-71gln

**Comment by meotimdihia** [comment]
Hi, I am waiting the new release 👍 .

**Comment by rafa8626** [comment]
@meotimdihia I’m just waiting to have a feature approved and then I’ll release maybe next week

**Comment by Cremz** [comment]
@rafa8626 I'm having the same issue when trying to use your player on a nextjs application with server rendering.
Followed the example with useEffect, but it seems the error starts already when importing the openplayerjs file, code inside the useEffect doesn't even run in my case. Any tips?

**Comment by rafa8626** [comment]
@Cremz I’ll need to see this issue in a CodePen. There’s a link in the README that contains the implementation with NextJS. Start with that and then if it doesn’t work create one where you replicate the issue

**Comment by Cremz** [comment]
After a whole lot of time spent on this i discovered that nextjs offers a dynamic loader that let me include a component only when there's no server side rendering. so issue was related to nextjs, not openplayer

**Comment by rafa8626** [comment]
@Cremz great, thanks for the heads up. Can you help me starring the project to show your support please?

**Comment by rafa8626** [comment]
@rayronvictor are you seeing this in the latest version of OpenPlayerJS?

**Comment by rayronvictor** [comment]
@rafa8626 yes, using Gatsby 3.5.x

**Comment by rayronvictor** [comment]
I created a codesandbox https://codesandbox.io/s/adoring-franklin-wf8gg

To reproduce the error, run `yarn build` in a new terminal tab

**Comment by rafa8626** [comment]
@rayronvictor thanks! I’ll check it and get back to you

**Comment by rafa8626** [comment]
@rayronvictor please download the master branch and confirm it works now. If so, let me know so I can release this fix as soon as possible. Thanks for bringing this up

**Comment by rayronvictor** [comment]
I can confirm that solved the SSR problem. Thanks for the fast response and work!

**Comment by rafa8626** [comment]
@rayronvictor you are welcome! Thanks for testing this. I’ll release the fix later today
