### ISSUE TITLE
Issue with seeking

### ISSUE THREAD

**Issue by Gungrave223** [openplayerjs/openplayerjs#12]
There seems to be an issue when seeking where player skips further into the video than where you clicked.

![snip20180917_3](https://user-images.githubusercontent.com/8568496/45621906-270b4480-ba50-11e8-96bf-5f75e7e28f08.png)

This bug seems to result in onend never being triggered when the video finishes playing.

**Comment by rafa8626** [comment]
Thanks I'll check this today

**Comment by rafa8626** [comment]
Can you just specify your test case please so I can replicate it on my end?

**Comment by Gungrave223** [comment]
All I did was seek close to the end of the video.

**Comment by Gungrave223** [comment]
Ok I did some more testing... Was not able to replicate the onend not firing when playing mp4, however, I am able to replicate when using HLS m3u8 playlist by clicking towards the end then clicking a few seconds back.

So it could just be an issue with the HLS lib and not the player.

**Comment by rafa8626** [comment]
Can you provide your HLS URL so I can check on my end and verify that it is a hls.js issue, please?

**Comment by Gungrave223** [comment]
Unfortunately the hosted test files are behind a CORS wall but can I provide a zip with the segmented files if that will work?

**Comment by rafa8626** [comment]
If you can test any of the streams in https://video-dev.github.io/hls.js/demo/, and if you are able to replicate it with one of them in my player, that would definitely help. If not, send me the zipped files and I'll try to check it on my end

**Comment by rafa8626** [comment]
I even tried https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8 and it worked just fine.

**Comment by Gungrave223** [comment]
Yep you're right...the I wasn't able to replicate with any of the streams you provided. So I'm going to go ahead and close this since it pretty clear the issues lies with the files themselves.

Thanks.

**Comment by rafa8626** [comment]
You are welcome. Please invite more users to star the project to give it more visibility
