### ISSUE TITLE
Ad loop

### ISSUE THREAD

**Issue by KajKas** [openplayerjs/openplayerjs#123]
Would it be possible to add an option to loop the VAST ad so that it plays in repeat without any other videos?

**Comment by rafa8626** [comment]
@KajKas please download the branch **feature/infinite-ad** and let me know if it works for you. I tested in iOS and desktop and all seems to be working as expected. Read the documentation to know how to activate the loop in Ads

**Comment by KajKas** [comment]
@rafa8626 Works great, thanks a lot!

**Comment by rafa8626** [comment]
Thanks @KajKas it has been merged into master; I’ll release it tomorrow
