### ISSUE TITLE
Progress bar flash when enabling levels control

### ISSUE THREAD

**Issue by meotimdihia** [openplayerjs/openplayerjs#125]
Progress bar flash when enabling levels control:
Code link: https://codesandbox.io/s/cranky-jepsen-uu6b5
**Screenshots**
![2020-03-15_02-58-12](https://user-images.githubusercontent.com/300961/76689505-18174980-6669-11ea-83ca-8525c39ee13b.gif)

```javascript
    var player = new OpenPlayer("my-player", null, false, {
      controls: {
        left: ["play", "time", "volume"],
        middle: ["progress"],
        right: ["levels", "captions", "settings"] // The bug is not happen If I remove levels option
      },
      detachMenus: true
    });
```

**Comment by rafa8626** [comment]
@meotimdihia thanks I’ll check this and keep you posted

**Comment by rafa8626** [comment]
@meotimdihia please test the PR I created and let me know if it's good to go. Thanks

**Comment by rafa8626** [comment]
@meotimdihia thanks for your feedback
