### ISSUE TITLE
How to manually insert AdBreaks?

### ISSUE THREAD

**Issue by bcorvino** [openplayerjs/openplayerjs#129]
Hi,

IVe' been using openplayerjs for my new project and it's fantastic.  One issue though: I'd like to be able to manually trigger ad breaks using the same tag at intervals responding to the HTML5 timeupdate event.

I believe in IMA SDK this is accomplished by setting:
adsLoader.getSettings().setAutoPlayAdBreaks(false);

and then adding a custom listener (see below)
https://developers.google.com/interactive-media-ads/docs/sdks/html5/ad-rules

But I don't see a way to directly access the adsLoader in openplayer (it's privately scoped).

Am I missing an overload method somewhere or is this something I should make a fork for?

Thanks!
Bill

**Comment by rafa8626** [comment]
@bcorvino the only method I have to access the Ads is `getAd`, but since the method is private you can actually set a PR to turn it public; that way more users could benefit of that approach

**Comment by bcorvino** [comment]
Thank you for the quick response, rafa. Happy to do the PR for the project.

**Comment by bcorvino** [comment]
Hi Rafa,

Pull request sent.

Bill

**Comment by rafa8626** [comment]
@bcorvino thanks; I was just checking it. Can you remove the `dist` files since it complicates the review of it please?

**Comment by bcorvino** [comment]
oops will do. Do I need to make a new pull request after, or will it be reflected when master is updated?

**Comment by rafa8626** [comment]
better create a new pull request

**Comment by bcorvino** [comment]
last thing: better to remove the files or just pull down the ones from your master so they match on the PR?

**Comment by rafa8626** [comment]
which files, the `dist` ones?

**Comment by bcorvino** [comment]
yes, the dist ones.

**Comment by rafa8626** [comment]
just pull down the ones from master; at the end of the day I just need to review your `demo` and `src` folders' changes

**Comment by bcorvino** [comment]
Thats' what I figured.  Coming up, thanks!

**Comment by bcorvino** [comment]
New PR sent

**Comment by rafa8626** [comment]
Review back to you

**Comment by rafa8626** [comment]
@bcorvino thanks for the PR; this is now part of the new version of the player

**Comment by bcorvino** [comment]
Happy to have contributed!
