### ISSUE TITLE
 preload="none" doesn't work anymore

### ISSUE THREAD

**Issue by frequeradio** [openplayerjs/openplayerjs#134]
**Describe the bug**
With the last version, with the following code ` <audio class="op-player op-player__media" controls preload="none">` the user has to click twice on the button play to start the stream.

The issue did not occur with my version currently in production 1.9.0

Thanks !

**Comment by rafa8626** [comment]
@frequeradio can you create a quick CodePen that shows this issue, so I can look at it later, please?

**Comment by frequeradio** [comment]
Thanks !

https://codepen.io/frequeradio/pen/XWmbGYL   --> with the 1.16.3 and the issue
https://codepen.io/frequeradio/pen/abvOMab  --> with the 1.9.0, without the issue

**Comment by rafa8626** [comment]
@frequeradio please download the master branch and test; this fix will go in the oncoming release

**Comment by frequeradio** [comment]
It works :)

thanks !
