### ISSUE TITLE
IMA SDK: set numRedirects

### ISSUE THREAD

**Issue by aldevit** [openplayerjs/openplayerjs#135]
hi,
how can i edit numRedirects for IMA SDK?

currently default is 4 I have to set maxredirects 6.

Thanks,
Al

**Comment by rafa8626** [comment]
@aldevit currently, there's no way right now to change that but let me work on it and I'll get back to you

**Comment by aldevit** [comment]
> but let me work on it and I'll get back to you

thank you so much

**Comment by rafa8626** [comment]
@aldevit you are welcome, a quick favor: can you star the project to show your support, please? If you have any friends on GitHub, please ask them to do as well. The more popularity, the better the player will turn

**Comment by rafa8626** [comment]
@aldevit please download the master branch and test the new `numRedirect` parameter inside of the `ads` config element. Read https://github.com/openplayerjs/openplayerjs#usage-with-javascript for more info. Thanks and let me know so this can go in the oncoming release

**Comment by aldevit** [comment]
@rafa8626 I have download new file js with numRedirects and deployed on website, but it isn't changed the numRedirects is still settengis on 4

![ima_numRedirects](https://user-images.githubusercontent.com/63758206/79421928-2637ed00-7fbc-11ea-8fef-12df4d4bc42f.PNG)

**Comment by rafa8626** [comment]
@aldevit I’ll check this and ping you back

**Comment by rafa8626** [comment]
@aldevit I checked this and it works; once the loading of the Ads starts, it sets the numRedirects correctly

**Comment by aldevit** [comment]
@rafa8626  thank you for everything you did!

**Comment by rafa8626** [comment]
@aldevit you are welcome! I’ll release later today. Thanks for suggesting this feature
