### ISSUE TITLE
Uncaught TypeError: Cannot read property 'labels' of null

### ISSUE THREAD

**Issue by frequeradio** [openplayerjs/openplayerjs#136]
There is a new error in the console with the version 1.16.4 and the player does not load correctly

https://codepen.io/frequeradio/pen/eYpBxaq

Is there a change to do in the configuration ?

**Comment by rafa8626** [comment]
@frequeradio interesting; I’ll check your Pen and get back to you

**Comment by rafa8626** [comment]
@frequeradio please download the master branch and let me know if it works for you, so I can release this as soon as possible

**Comment by frequeradio** [comment]
Hi Rafa

The issue is fixed.
FYI when I slide the volume bar i have this error in the console

`Uncaught TypeError: Cannot set property 'volume' of undefined
    at Media.set (openplayer.js:7430)
    at Volume.updateVolume (openplayer.js:7073)`

I don't know if it's related or if i should open another ticket

**Comment by rafa8626** [comment]
@frequeradio I'll check it as part of this ticket as well

**Comment by rafa8626** [comment]
@frequeradio please download it again and let me know if that issue is also fixed, please

**Comment by frequeradio** [comment]
@rafa8626 all good :)

**Comment by rafa8626** [comment]
@frequeradio thanks for catching this. Closing ticket and sending new release
