### ISSUE TITLE
Recommended AWS Cloudfront settings for hls and m3u8 files

### ISSUE THREAD

**Issue by agsdot** [openplayerjs/openplayerjs#137]
Can there be some documentation for best practice/recommended S3 and Cloudfront settings when hosting m3u8 files?

I can occasionally get S3 m3u8 files to be served up. But for Cloudfront, "*.m3u8' from origin 'https://website URL' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource." 

Console Developer Tools
![Screen Shot 2020-05-26 at 3 12 03 PM](https://user-images.githubusercontent.com/1510449/82955499-d574c600-9f63-11ea-8255-1170d4f48df4.png)

S3 CORS setup
![Screen Shot 2020-05-26 at 3 15 15 PM](https://user-images.githubusercontent.com/1510449/82955505-d9084d00-9f63-11ea-8032-f639f1c13aca.png)

Cloudfront configurations
![Screen Shot 2020-05-26 at 3 15 37 PM](https://user-images.githubusercontent.com/1510449/82955509-dc033d80-9f63-11ea-8bcd-3a13fed1adf3.png)

Thanks for your help.

**Comment by rafa8626** [comment]
@agsdot sure; let me prepare a space for it, so it is documented in the project as well. Thanks for raising the concern about that part. Please start the project to show your support

**Comment by agsdot** [comment]
@rafa8626 Thanks! Super appreciate your help. Been on StackOverflow and Googling for solutions the week and more or so. 

Already using OpenPlayer.js for mp4 files (the above S3/Cloudfront settings seem to work ok with mp4 files), but would really like to transition to using m3u8/*.ts files. Easier for locations that might be on lower bandwidth or further from the Amazon Edge site.

**Comment by rafa8626** [comment]
That’s good; can you give the project a star so we can help it to become more popular please?

**Comment by agsdot** [comment]
👍 , just put in a star.

**Comment by rafa8626** [comment]
@agsdot thanks! Can you check if any of these answers help you in your scenario: https://stackoverflow.com/questions/33858072/aws-s3-cloudfront-gives-cors-errors-when-serving-images-from-browser-cache?

**Comment by agsdot** [comment]
@rafa8626 , I saw that SO article the other day. However, I proceeded to try the curl diagnostics from the second post. Screenshots are documented of configs for both S3 and Cloudfront, as well as the curl outputs. I'm still encountering the same issue in the browser console.

![Screen Shot 2020-05-27 at 11 17 56 AM](https://user-images.githubusercontent.com/1510449/83058280-f9401680-a00c-11ea-9972-077248e7670c.png)

![Screen Shot 2020-05-27 at 11 19 22 AM](https://user-images.githubusercontent.com/1510449/83058288-fe9d6100-a00c-11ea-820d-cdb5a25afd3e.png)

<img width="1428" alt="Screen Shot 2020-05-27 at 11 12 57 AM" src="https://user-images.githubusercontent.com/1510449/83058346-1674e500-a00d-11ea-90b4-91bb42eca193.png">

![Screen Shot 2020-05-27 at 11 10 28 AM](https://user-images.githubusercontent.com/1510449/83058397-25f42e00-a00d-11ea-92b9-b2d2b540eeae.png)

**Comment by rafa8626** [comment]
@agsdot IDK if it helps as well, but placing a crossdomain.xml at your root folder file was an old practice, I don't know if that will also help. I generally had relied on more specialized people to set this up

**Comment by agsdot** [comment]
`<cross-domain-policy>
<allow-access-from domain="*" />
</cross-domain-policy>`

and 

`<cross-domain-policy>
<allow-access-from domain="*" secure="false"/>
</cross-domain-policy>`

(from https://foliovision.com/player/video-hosting/hls#cors-in-amazon-s3 and https://github.com/Tinywan/html5-dash-hls-rtmp/blob/master/crossdomain.xml)
were tested out. The same issue occurred. 

P.s. Are crossdomain.xml files used for hls or only rtmp/flash?

**Comment by rafa8626** [comment]
Could be used for both; since this is more related to your setup than to the project, if you need more specialized help we can talk about it. It’s hard to know what’s failing on your side without having access to it in so capacity

**Comment by agsdot** [comment]
@rafa8626 , you're correct, it was more of an AWS setup question (and recommended best practice) more so than about the openplayer project.

Fortunately after several weeks+ of googling for solutions and sifting through SO articles, I came across something new that worked.

I was contemplating yesterday after your last comment about perhaps trying GCP's setup vs AWS and how to configure their equivalent S3 and Cloudfront with COR's.

Googling around I found this github gist which happened to also have recommended COR's recommendations (apparently for web font's): https://gist.github.com/rwaldron/4cf573222da7a6131e26dfccb51f6cfa

Put this in my CORs configs for S3 and things worked. My guess is that the "    <ExposeHeader>Access-Control-Allow-Origin</ExposeHeader>" line was crucial -- it's funny I didn't see that line mentioned anywhere else in SO articles or any other pages I googled.

I'm no longer getting the error in the console. Issue can be closed.

**Comment by agsdot** [comment]
Just to document the CORs setup that worked for me:

`
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <MaxAgeSeconds>3600</MaxAgeSeconds>
    <ExposeHeader>ETag</ExposeHeader>

    <ExposeHeader>Content-Length</ExposeHeader>
    <ExposeHeader>Date</ExposeHeader>
    <ExposeHeader>ETag</ExposeHeader>
    <ExposeHeader>Access-Control-Allow-Origin</ExposeHeader>
    <ExposeHeader>Connection</ExposeHeader>

    <AllowedHeader>*</AllowedHeader>
    <AllowedHeader>Host</AllowedHeader>

</CORSRule>
</CORSConfiguration>
`

**Comment by rafa8626** [comment]
@agsdot thanks so much for giving me a heads up about this! in the next version I'll try to include the documentation or links for this at least. Please invite other users to star the project to give it more popularity.

**Comment by agsdot** [comment]
CORS setup referenced in the gist: https://gist.github.com/rwaldron/4cf573222da7a6131e26dfccb51f6cfa. Just putting some copy pasta in case that gist get's removed, and/or it makes it easier for other people to find CORS setting when they want to setup openplayerjs

AWS S3 CORS
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <CORSRule>
		<AllowedOrigin>*</AllowedOrigin>
		<AllowedMethod>GET</AllowedMethod>
		<AllowedMethod>POST</AllowedMethod>
		<AllowedMethod>HEAD</AllowedMethod>
		<MaxAgeSeconds>2592000</MaxAgeSeconds>
		<ExposeHeader>Content-Length</ExposeHeader>
		<ExposeHeader>Date</ExposeHeader>
		<ExposeHeader>ETag</ExposeHeader>
		<ExposeHeader>Access-Control-Allow-Origin</ExposeHeader>
		<ExposeHeader>Connection</ExposeHeader>
		<AllowedHeader>*</AllowedHeader>
		<AllowedHeader>Host</AllowedHeader>
	</CORSRule>
</CORSConfiguration>
```

GCP
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CorsConfig>
  <Cors>
		<Origins>
			<Origin>*</Origin>
		</Origins>
		<Methods>
			<Method>GET</Method>
			<Method>POST</Method>
			<Method>HEAD</Method>
		</Methods>
		<ResponseHeaders>
			<ResponseHeader>*</ResponseHeader>
		</ResponseHeaders>
		<MaxAgeSec>86400</MaxAgeSec>
	</Cors>
</CorsConfig>
```

**Comment by agsdot** [comment]
For sure, no problem @rafa8626 . Thanks once again for making an awesome media player. Much appreciated.
