### ISSUE TITLE
Ads not playing media after they end

### ISSUE THREAD

**Issue by Sh1d0w** [openplayerjs/openplayerjs#148]
**Describe the bug**
Ads are not playing media once they end on mobile

**To Reproduce**

1. Go to https://openplayerjs.com
2. Put ads url 
3. Click on Play button for audio in iPhone 11

**Expected behavior**
Ads should be played and after that, media should automatically play (mobile)

Device: iPhone 11
OS: iOS 13.5.1
Browser Safari
Version 13.1

**Comment by rafa8626** [comment]
@Sh1d0w let me check this and get back to you; please give us a star to support the project

**Comment by Sh1d0w** [comment]
Thanks for the quick response @rafa8626 . I've already starred it when I've discovered the project. Been using it since then, great job 👍

**Comment by rafa8626** [comment]
@Sh1d0w thanks for your support! I’ll keep you posted on my findings

**Comment by rafa8626** [comment]
@Sh1d0w after checking in depth some of the rules for Ads, the problem with the main website is that the duration of the media was less than the amount of Ads the source I set could play. So media tried to play all of them but couldn't because there was no middle roll time to execute them, so that caused some weird behaviors in the player. I changed the source to a longer one where the player could play all the Ads, and it behaves as expected.

Let me know if you have any other issues with it

**Comment by Sh1d0w** [comment]
Thanks for looking into this @rafa8626 .

In this case I am not sure this is the problem. The audio file itself is with 3 min length, so I don't think it is too short.

Let me give you some more info how to reproduce. On https://www.openplayerjs.com

- Use this for source of audio https://d21ha4knzzqzxd.cloudfront.net/0c0046ba-0c83-4fbe-93d4-5c6270d2f7b2.mp3
- Use this for ads https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=[timestamp]

You will notice that when you load it and click play on iPhone it will start a 10 sec ad and then after it finishes audio won't play. I am attaching a video as well:

https://imgur.com/a/62TgOag

**Comment by Sh1d0w** [comment]
Also just to clarify again that this problem appears only on iPhone, but works fine on Android.

**Comment by rafa8626** [comment]
@Sh1d0w gotcha. Ok let me check more and get back to you

**Comment by rafa8626** [comment]
@Sh1d0w I think I got this sorted out; please download the master  branch and let me know if it works for you. I tried the sources you indicated above and they seemed to be working as expected

**Comment by Sh1d0w** [comment]
Hi again @rafa8626 . Thanks for the quick fix, working like a charm now!

**Comment by Sh1d0w** [comment]
Hey again @rafa8626 . This seems to be fixed when we have an audio player, but seems still to not work if we have a video player. After the ad at the beginning finishes the video never starts.

I saw your commit https://github.com/openplayerjs/openplayerjs/commit/097f6127c5d52bf2207913fb07d45023f280cf04#diff-5237133821c414288086616f803f7455R759

There you target only the audio player, would it work if we remove the !isVideo check?

**Comment by rafa8626** [comment]
@Sh1d0w I’ll check that. I tested it but maybe I missed something

**Comment by rafa8626** [comment]
@Sh1d0w I fixed it, and it should be fine for both video and audio; please download master branch and test once more

**Comment by Sh1d0w** [comment]
Works for both audio and video now! Thanks !

**Comment by rafa8626** [comment]
@Sh1d0w great! Thanks for letting me know!

**Comment by Sh1d0w** [comment]
@rafa8626 sorry to bother you again but seems like the fix caused a side effect bug. Now if we get the error vast document is empty the player won’t start playing only on iOS, works fine on other platforms / browsers. I tried to narrow it down and seems like it is caused by not calling the admanager destroy function on the lines you’ve changed so the old events don’t get cleared. Since you are more familiar with the library is there any chance you can take a look at this again?

**Comment by rafa8626** [comment]
@Sh1d0w sure, do you have a CodePen that reproduces this error?

**Comment by Sh1d0w** [comment]
@rafa8626 Thank you very much for your time! Here is a codepen https://codepen.io/GDPR/pen/vYLdPeq

In order to reproduce you need to open it on iOS device, I am currently testing with iPhone 11 on latest version of iOS.

**Comment by rafa8626** [comment]
@Sh1d0w I’ll take a look and let you know my findings

**Comment by rafa8626** [comment]
@Sh1d0w I think the code was right before I set up the fix; I think the issue you saw before is related to the XML itself or how the Ad is being served. I see the same error happening with other sample tags from IMA SDK. I'll check this during the week.

**Comment by rafa8626** [comment]
@Sh1d0w please download the master branch and let me know if it works now, please test the Ads in your CodePen and the one you shared in this issue, since they are both different, and seems like I nailed down the behavior finally, but please confirm before I send this for a small release. Thanks for catching this

**Comment by Sh1d0w** [comment]
Hey @rafa8626 that was really quick! Just took a look and the original issue is now resolved! The player now starts correctly  on all platforms including iOS!

However I've noticed another bug I am not sure if it is related to your changes. It again happens only on iOS.

Using the master branch with your last commit, on iOS only if I try to change the position of the progress bar after the ad played and the audio started, no matter where I click it always resets to the start of the audio. I am not sure how to provide codepen for the master branch, but you can reproduce it basically with the same codepen as before using this VAST tag

```
https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=123456
```

You need to replace the last part `correlator ` with the current timestamp on each render in order to get some ads. I've reported this for Android devices few days ago and you've fixed it not sure if this was regression or was present on iOS as well and not fixed https://github.com/openplayerjs/openplayerjs/issues/149

**Comment by rafa8626** [comment]
@Sh1d0w gotcha. Let me check that and get back to you

**Comment by rafa8626** [comment]
@Sh1d0w download once more the master branch and let me know if it works now for you; I found out that a setting in IMA SDK messed with the internal timer of the video, so by doing it in a different way, I was able to click anywhere in the progress bar. Let me know if all is good so I can prepare the release today. Thanks

**Comment by Sh1d0w** [comment]
@rafa8626 Seems like you've nailed it! Thanks for the quick fix and the great work.

Btw is there a way I can support the project sending a few bucks? I see you haven't enabled GitHub sponsors.

**Comment by rafa8626** [comment]
@Sh1d0w no I'm not part of the GitHub sponsors yet, but if you send me your email I can send you my PayPal link through email. I really appreciate the willingness to contribute to the project and that you find it useful!

The more stars, the more exposure the project will have, so if you can also help me with that I'd appreciate it ;)

**Comment by rafa8626** [comment]
@Sh1d0w FYI, I released the 1.16.8 version with this fix, so you are good to use the CDN in a bit

**Comment by rafa8626** [comment]
@Sh1d0w I forgot I had my PayPal link public: https://paypal.me/rafa8626?locale.x=en_US. Thanks for your help and for reporting issues like this

**Comment by Sh1d0w** [comment]
Thanks, bought you a bunch of coffees!

**Comment by rafa8626** [comment]
Thank you!
