### ISSUE TITLE
Progress bar on Android phones problem

### ISSUE THREAD

**Issue by Sh1d0w** [openplayerjs/openplayerjs#149]
**Describe the bug**
Hi, there seems to be a problem when trying to change the current position with the progress bar on Android phones (with the audio player). If you try to move the handle it aways goes to the middle of the audio.

**To Reproduce**
1. Go to 'openplayerjs.com'
2. Switch to audio player
3. Click play and try to change the progress manually
4. See the progress bar skips to the middle no matter where you try to move it

**Expected behavior**
The position correctly changes to to where you adjust it.

**Smartphones:**

LG X Power2, Android v 8.1.0, Chrome
Huawei p20 Lite, Android 9, Chrome 

This works correctly on iOS but not on Android, at least on the two devices I was able to test on.

**Comment by rafa8626** [comment]
@Sh1d0w thanks for reporting this; I’ll try to reproduce it as soon as I have an Android phone at reach since it’s only isolated to that OS

**Comment by rafa8626** [comment]
@Sh1d0w I think this is sorted out now; please download the master branch and let me know if it worked for you. Thanks!

**Comment by Sh1d0w** [comment]
Hey @rafa8626 . Thanks all working fine now!
