### ISSUE TITLE
Video player playing with sound when video element has muted attribute

### ISSUE THREAD

**Issue by jamesmorrisapps** [openplayerjs/openplayerjs#150]
**Describe the bug**
I have a muted video element that I'm having OpenPlayer.js play. However, while the video autoplays, the muted attribute of the video element is not respected and the video player plays with sound.

**To Reproduce**
Run the included code below in a web browser. You can run it here: https://www.w3schools.com/html/tryit.asp?filename=tryhtml_basic_headings

**Expected behavior**
The video player will play with sound.

**Code**
Here is my DOM:

<!DOCTYPE html>
<html>

    <head>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.css">

    </head>

    <body>

    	<div width="300" height="250">
        	<video id="video" class="op-player__media" muted autoplay controls playsinline>

        <source src="https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" type="video/mp4">

    </video>
    
    </div>

    <script src="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.js"></script>

    <script>
        const player = new OpenPlayerJS('video', null, true);
        player.init();

    </script>

    </body>

</html>

Thanks for the help!

**Comment by rafa8626** [comment]
@jamesmorrisapps please download the master branch and let me know if it's fixed for you. Once you confirm, I'll deploy the release

**Comment by jamesmorrisapps** [comment]
Thank you so much! I’ll check in a bit.

   Cheers,

      James

**Comment by jamesmorrisapps** [comment]
Hey Rafael,

This works perfectly! Thank you! 

   Cheers,

      James

**Comment by rafa8626** [comment]
@jamesmorrisapps thanks! New release is now out there with this fix
