### ISSUE TITLE
Unable to access the hls object.

### ISSUE THREAD

**Issue by Jaikant** [openplayerjs/openplayerjs#158]
Firstly thanks for the awesome project.

I am using HLs with multiple audio streams. I need to access the audio streams, more specifically the
`hls.audioTrack` for the current track, `hls.audioTracks` for all the tracks, and then I need to set the track based on user input. For this purpose, I need access to the hls object. How to get a reference to it?

Below some sample code, I was using directly with hls.js without a player.

```
  //       hls.on(Hls.Events.MANIFEST_PARSED, function () {
  //         const audioTrackId = hls.audioTrack;
  //         const len = hls.audioTracks.length;
  //         const track = hls.audioTracks[audioTrackId];

```

**Comment by rafa8626** [comment]
@Jaikant thanks for raising this issue; currently I haven’t integrated a way to access hls within the player but let me take a look and get back to you as soon as I can. Thanks and please star the project to show your support

**Comment by Jaikant** [comment]
@rafa8626 Thanks! Let me know if it is a trivial change in the library, I could do the PR. If you give me some pointers.

**Comment by rafa8626** [comment]
@Jaikant I think the easiest way is to create a method to access the player instance you are dealing with; something like 
```javascript
player.getMedia().getInstance().audioTrack
```
this has to be a common method from `native.ts`. If you wanna raise a PR, I'd be happy to review it.

Let me know your thoughts

**Comment by rafa8626** [comment]
@Jaikant can you check the master branch and let me know if it works for you? The way to use it is:
```javascript
player.getElement().addEventListener('hlsManifestParsed', function () {
     console.log(player.getMedia().instance.audioTracks);
});
```

**Comment by Jaikant** [comment]
@rafa8626 awesome thank you so much! 
PS: I had starred the project before you asked me to :) because it is awesome.

**Comment by rafa8626** [comment]
@Jaikant nice! I’m going to try to simplify the approach so you can use getMedia() only. I’ll keep you posted about it
