### ISSUE TITLE
Please provide an example of how are we supposed to use the module in typescript

### ISSUE THREAD

**Issue by abdes** [openplayerjs/openplayerjs#159]
**Is your feature request related to a problem? Please describe.**
As you are providing types only as a namespace in the type declaration file within the npm module, it's not clear how we can import the module in a typescript file without errors.

Doing:
import OpenPlayer from 'openplayerjs';

Results in:
TypeScript error in src/views/MainPanel.tsx(3,24):
File '...../node_modules/openplayerjs/openplayer.d.ts' is not a module.  TS2306

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rafa8626** [comment]
@abdes thanks for posting this issue. I’ll check this and get back to you as soon as I can. Meanwhile, please give the project a star to show your support

**Comment by abdes** [comment]
Done.

**Comment by rafa8626** [comment]
@abdes please download the master branch and let me know if the issue is gone. I had to update quite a bit the approach I was using and as far as I could see, it is working as expected but let me know so this fix goes into the next release

**Comment by rafa8626** [comment]
@abdes let me know if it worked for you so I can put for the big release coming soon. Thanks for reporting this

**Comment by abdes** [comment]
The new types declaration files are complete now.
Thanks for the update.
