### ISSUE TITLE
Cannot change live HLS source unless player is destroyed

### ISSUE THREAD

**Issue by abdes** [openplayerjs/openplayerjs#160]
**Describe the bug**
If a player is already initialized with a HLS live source (.m3u), and the `player.src` is changed, the player continues to request the previous streams in the previous src value while requesting the new ones as well.

In order to switch the live HLS stream to a different source, the current player instance needs to be destroyed and recreated with the new source.

Is there a way to change HLS source without destroying the player instance?

**To Reproduce**
1. Init a player with a .m3u source
2. Play
3. Change the player.src

```
    player.current.pause();
    player.current.src = manifestUris[chan + 1];
    player.current.load();
    setTimeout(() => {
      player.current.play();
    }, 250);
```

4. P{layer continues to request the streams from the previous .m3u playlist as well as the new one...

**Expected behavior**
Player should stop the streams from the current src and switch the new src .m3u playlist.

**Workaround**
```
    if (player.current) {
      player.current.destroy();
    }
    player.current = new OpenPlayer('player');
    player.current.src = manifestUris[chan + 1];
    player.current.init();
    setTimeout(() => {
      player.current.play();
    }, 250);
```

**Additional context**
    "openplayerjs": "^1.16.11",

**Comment by rafa8626** [comment]
@abdes thanks for reporting this. Let me check what could be the issue since it shouldn't be doing that already. Can you send me a couple of live streaming URLs I can use to test this please?

**Comment by abdes** [comment]
@rafa8626 Unfortunately all streams I have require a username and password and cannot be shared.

**Comment by rafa8626** [comment]
@abdes I checked this and I’m unable to replicate it. I used 2 different live streams in my demo file and all worked as expected. Without a sample from your end it’s hard for me to say what’s the issue

**Comment by abdes** [comment]
Can you please share the code you used to switch streams without destroying the player?

I will test it on my side using the same code.

**Comment by rafa8626** [comment]
@abdes if you check the `demo.js` file inside the `demo` folder in this project, look for the loadMedia (https://github.com/openplayerjs/openplayerjs/blob/f7dcecd61683e348fa142149cc2c2285010ca2a7/demo/demo.js#L21) that's how I'm doing it, and that's based even in how HLS.js does it

**Comment by rafa8626** [comment]
Closing hubs since it seems to be related to a custom implementation than an issue with the code. If you need this to be reopened, let me know
