### ISSUE TITLE
Uncaught TypeError: n(...).default is not a constructor, using TypeScript

### ISSUE THREAD

**Issue by tigitz** [openplayerjs/openplayerjs#161]
**Describe the bug**
Uncaught TypeError: n(...).default is not a constructor

**To Reproduce**
I'll provide a reproducer if bug cannot be solved easily but basically, I'm using the player in a `contentscript.ts` used in web extension development.

the tsconfig.json
```json
{
  "compilerOptions": {
      "module": "commonjs",
      "target": "es5",
      "noImplicitAny": true,
      "noImplicitUseStrict": true,
      "noImplicitReturns": true,
      "strictNullChecks": true,
      "lib": ["dom", "es2017"]
  }
}
```
.babelrc
```json
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": "last 2 versions"
      }
    }]
  ],
  "ignore": ["node_modules"]
}

```
Code generating the error. I'm using the master branch.
```ts
import OpenPlayerJS from 'openplayerjs';
const player = new OpenPlayerJS('vokatic-player', '...');
```

**Expected behavior**
To not error.

**Screenshots**
the compiled code
![image](https://user-images.githubusercontent.com/1524501/94338418-4bf90180-fff2-11ea-917b-707770427953.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Additional context**
I'm planning to use your player to vocalize news content, it's done through a web extension for testing purpose right now.

**Comment by tigitz** [comment]
Solved by importing this way:

```ts
import * as OpenPlayerJS from 'openplayerjs';
```

Probably my lack of understanding of CommonJS vs ES2015 modules. README could help in that sense with different examples.

**Comment by rafa8626** [comment]
@tigitz I’m glad you figured out, and yes, I’ll include an example in the docs once I release the new 2.0 version. Can you star the project to show your support to it, please?

**Comment by tigitz** [comment]
already done :wink: :

**Comment by rafa8626** [comment]
Thanks. Much appreciated. By the way did you have this issue downloading directly the master branch, or using npm? The reason I’m asking it’s because I fixed a problem recently but hasn’t been released yet

**Comment by rafa8626** [comment]
Either way, if you can give me a CodePen or similar when you can show me this issue, I’d appreciate it, just in case I may have missed something for the next release. Thanks

**Comment by tigitz** [comment]
I used

**Comment by rafa8626** [comment]
Gotcha; if you have a way to show me that error in a CodePen or something similar let me know so I can take a look at it and determine how to use it in the format I have indicated in the docs

**Comment by tigitz** [comment]
OK, I'm on it !

**Comment by tigitz** [comment]
@rafa8626 Here it is
https://codesandbox.io/s/open-player-default-constructor-issue-3grz3

I definitely think it has something to do with the tsconfig

**Comment by rafa8626** [comment]
@tigitz gotcha. Would you like to create a PR  where you include this config to confirm this solves your issue?

**Comment by tigitz** [comment]
> @tigitz gotcha. Would you like to create a PR where you include this config to confirm this solves your issue?

Sure but to clarify first you mean a PR including an integration test ? or a demo ? or just a doc ?

**Comment by rafa8626** [comment]
We could add just docs but I wonder if I do need to setup that in the project’s tsconfig file

**Comment by rafa8626** [comment]
@tigitz I have added the configuration in the project itself and seems that it did the trick as you said. You should be able now to use 
```javascript
import OpenPlayerJS from "openplayerjs";
```
if you test the master branch. Let me know if it worked for you now.

**Comment by rafa8626** [comment]
@tigitz let me know if this one is good to go so it's part of v2

**Comment by tigitz** [comment]
Hey @rafa8626 , I tried with the latest master again and it didn't work.

I took some time to dig a little bit the "module" subject and the `"esModuleInterop": true` modification on the OpenPlayer's tsconfig side will not change anything for projects consuming it.

What will change the way other projects will import your library is actually the `modules: ` property.

Actually it's setup to `modules: commonjs` which is described as:
```

**Comment by rafa8626** [comment]
@tigitz thanks for all this information; I'll check all of it and come back to you to see if the multiple version approach worked for you

**Comment by rafa8626** [comment]
@tigitz can you check the 2.0.0 branch and see if the new files in dist will help you with this issue, please? I ended up adding those ESM files and the main module reference in the package.json in that branch. Let me know if this worked for you

**Comment by tigitz** [comment]
It worked ! Hopefully we both learned from this experience :)

Thanks for your commitment.

**Comment by rafa8626** [comment]
Thanks for the valuable info you provided :)
