### ISSUE TITLE
VMAP with mid-roll is buggy

### ISSUE THREAD

**Issue by tigitz** [openplayerjs/openplayerjs#162]
**Describe the bug**
Tried to used an example in the list of IMA sample tags here: https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags

that fits my needs and I picked : `VMAP Pre-, Mid-, and Post-rolls, Single Ads` as I want mid roll ads but it has a weird behavior.

**To Reproduce**
https://www.openplayerjs.com/embed.html?file=https%3A%2F%2Fcommondatastorage.googleapis.com%2Fgtv-videos-bucket%2Fsample%2FTearsOfSteel.mp4&type=video&ads=https%3A%2F%2Fpubads.g.doubleclick.net%2Fgampad%2Fads%3Fsz%3D640x480%26iu%3D%2F124319096%2Fexternal%2Fad_rule_samples%26ciu_szs%3D300x250%26ad_rule%3D1%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dvmap%26unviewed_position_start%3D1%26cust_params%3Ddeployment~3Ddevsite~26sample_ar~3Dpremidpost%26cmsid%3D496%26vid%3Dshort_onecue%26correlator%3D

_List of bugs:_

**Scenario 1**
- If you let it roll until `00:00:07`, it just pause itself for no obvious reason
- If you resume and let it roll until `00:00:15` when the midroll ad is supposed to start, the ad plays but the underlying video still plays too
- if you fast forward to the end, post roll starts but no video is shown and playing time is doing weird things

**Scenario 2**
- if you fast forward, mid roll ads plays but when it switch back progress bar is the yellow ad one

**Expected behavior**
To have a proper pre / mid / post roll behavior

**Comment by rafa8626** [comment]
@tigitz thanks I’ll check this and get back to you

**Comment by tigitz** [comment]
I've update the bug description. I realised mid roll ad not playing in the middle of the video is expected since it's defined this way: `AdBreak timeOffset="00:00:15.000" breakType="linear" breakId="midroll-1"`

**Comment by rafa8626** [comment]
@tigitz can you test the master branch and let me know if worked for you? There was an event in Ads that was causing this but in my tests all came positive

**Comment by rafa8626** [comment]
@tigitz let me know if this one is good to go so it's part of v2

**Comment by tigitz** [comment]
Yep it's all good with the last version :+1: 

Congrats and many thanks !
