### ISSUE TITLE
next button in pause and end

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#163]
Next button in pause and end of video like YouTube player. and  auto click on next button after X sec. 
 
![Capture](https://user-images.githubusercontent.com/13816403/94994487-c999b000-05a4-11eb-9046-e587b6ea3a98.PNG)

**Comment by rafa8626** [comment]
@foadabdollahi this is more likely to be a separate plugin, since that is completely tied to a playlist, and not built into the current player's capabilities. In v2 I'll provide ways to create this in an easier manner
