### ISSUE TITLE
Auto rotate on fullscreen 

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#164]
Auto rotate 90 degree on full-screen mode on mobile device

**Comment by rafa8626** [comment]
@foadabdollahi thanks for the suggestion; I'll look at this this week before the big release

**Comment by rafa8626** [comment]
@foadabdollahi can you check the 2.0.0 branch and let me know if it works what I implemented, please? I don't have Android devices with me, and in iOS there's no way to lock the screen since it's a constrain

**Comment by rafa8626** [comment]
@foadabdollahi I forgot to update the bundles but it should be fine now; please let me know if it worked for you

**Comment by foadabdollahi** [comment]
@rafa8626 Great! this work correct 👍

**Comment by rafa8626** [comment]
Thanks @foadabdollahi for the confirmation. Closing this issue
