### ISSUE TITLE
Advertising and multiple players is buggy

### ISSUE THREAD

**Issue by vlouppe** [openplayerjs/openplayerjs#165]
**Describe the bug**
Multiple players can not play ads in the same time. 

**To Reproduce**
Demo here : https://codepen.io/vlouppe/pen/eYzmYxd

**Expected behavior**
The adsContainer id should no be hard coded "op-ads" https://github.com/openplayerjs/openplayerjs/blob/925b075c03ef50fee3676f8c0918d9102c468260/src/js/media/ads.ts#L333

**Comment by rafa8626** [comment]
@vlouppe thanks for logging this in. I’ll take a look later today. Meanwhile, please star the project to show your support

**Comment by vlouppe** [comment]
I have already star this projet ;)

**Comment by rafa8626** [comment]
@vlouppe so, I fixed the ID issue in the 2.0.0 branch. However, the default behavior in the player as a whole is not to allow multiple player instances to play at the same time. It will only allow one to play and when the other one is attempted to play, it will pause the other one

**Comment by Rubioli** [comment]
Hello @rafa8626 

Any chance you could let me know how to enable this?

**Comment by rafa8626** [comment]
@Rubioli do you have a CodePen to reproduce this issue?

**Comment by Rubioli** [comment]
Thanks for your reply @rafa8626 

Yes, please find it here: https://codepen.io/rubioli/pen/QWOVJjZ

Even though both players are `muted` and `autoplay` they don't play and as you already mentioned default behavior is to let one play, and if one is playing the other one will be paused. but I need to be able to play both at the same time and with ads.

Appreciate any help to solve my issue!

**Comment by rafa8626** [comment]
@Rubioli can you add to both players’ configuration the `pauseOthers` as false, and see if that helps?
