### ISSUE TITLE
How to manually insert an ad break on a playing video ?

### ISSUE THREAD

**Issue by vlouppe** [openplayerjs/openplayerjs#166]
**Is your feature request related to a problem? Please describe.**
I'm searching a way to insert fresh ads on a playing video. The goal is to insert periodically new ads coming from header bidding request. I think it's not possible right now.

**Describe the solution you'd like**
A new method on Ads class or an extra ads param on load method may be fine.

**Comment by tigitz** [comment]
Had the same need to manually start a midroll ads and relied on: https://github.com/openplayerjs/openplayerjs/pull/131

This me be helpful to you.

If you feel grateful don't hesitate to contribute a codepen exemple in the README :wink:

**Comment by rafa8626** [comment]
@tigitz this is a CodePen that will be included in the list for 2.0.0: https://codepen.io/rafa8626/pen/abZNgoY
@vlouppe FYI
