### ISSUE TITLE
new option for addControl

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#168]
Hi,
some idea:

can you add 
 svg option to add control and if icon option is undefined load svg option:

```
player.addControl({
    icon: null,
    svg: '... sng tag  ....',  //<========= 
    title: 'Rewind',
    position: 'right',
    click: () => { 
        const target = player.getElement();
        target.currentTime = target.currentTime <= 20 ? 0 : (target.currentTime - 20);
    },
// add on main deck : true/false
});
```

also if any option that can be add this control also in center of video side of play icon

**Comment by rafa8626** [comment]
@foadabdollahi I’ll check that in the 2.x version and integrate that there. My plan is to release the new version by the end of this week, so I’ll keep you posted once I get this ready in that branch

**Comment by rafa8626** [comment]
@foadabdollahi please check the 2.0.0 branch and test this; there's no need to add a new element: we can reuse the icon for this purpose. Let me know if it worked for you. Thanks

**Comment by foadabdollahi** [comment]
@rafa8626 i check it. if i use svg as link it work by if i wanna use inline svg it not work 

like this:
```
player.addControl({
    icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#ff000a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>', 
    title: 'Rewind',
    position: 'right',
    click: () => { 
        const target = player.getElement();
        target.currentTime = target.currentTime <= 20 ? 0 : (target.currentTime - 20);
    }, 
});
```

**Comment by rafa8626** [comment]
I’ll check that today and see why it doesn’t work since I followed pretty much what you did on your PR

**Comment by rafa8626** [comment]
ok @foadabdollahi try again. I added a missing workflow to add button correctly, and once I did I can see the code you posted above doing this:

<img width="727" alt="Screen Shot 2020-10-15 at 8 41 43 AM" src="https://user-images.githubusercontent.com/910829/96126974-43de0480-0ec2-11eb-8a10-a1a29449b5f1.png">

**Comment by foadabdollahi** [comment]
great, it's ok.

**Comment by foadabdollahi** [comment]
do you have any config for add control to main deck

![Captures](https://user-images.githubusercontent.com/13816403/96234044-c390cf80-0fa5-11eb-9f6c-726cbb593fc5.PNG)

**Comment by foadabdollahi** [comment]
and one question. Can i order added control ? for example a wanna add control before volume

**Comment by rafa8626** [comment]
@foadabdollahi if you set the position to main, you will be adding the control where the big play button is; as per the order, you have now more layers so it will take the order in which you configure each one of them. Check the docs for more info

**Comment by rafa8626** [comment]
@foadabdollahi is this issue good to be closed now ?

**Comment by foadabdollahi** [comment]
yes thanks
