### ISSUE TITLE
Localization for ads

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#170]
customize ads display like Localization text:

https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/localization

**Comment by rafa8626** [comment]
@foadabdollahi Test the 2.0.0 branch and let me know if it works for you; you only need to pass the language in the ads configuration. Check the usage.md file for more details

**Comment by foadabdollahi** [comment]
it's work fine. thanks
