### ISSUE TITLE
Main video play event

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#171]
maybe it's use full add an event for on initial main play (not ads video).

```
player.getElement().addEventListener("initialplay", function () {
    console.log("play initial main video"); 
});
```

**Comment by rafa8626** [comment]
@foadabdollahi can you give me a use case for this?

**Comment by foadabdollahi** [comment]
for example i wanna add control after ad ended or skiped  and main video started

**Comment by rafa8626** [comment]
@foadabdollahi if that’s what you need I’d suggest you to use the ads event and dispatch that action once the ad is skipped or completed; check the docs for more info on them

**Comment by foadabdollahi** [comment]
i only wanna addcontrol to main video not ads video

![IMG_20201017_164954](https://user-images.githubusercontent.com/13816403/96338118-dc2de200-1098-11eb-9e6a-392aaf4094fd.jpg)


maybe it's bug for addcontrol.

**Comment by rafa8626** [comment]
If anything, you should try to hide it once the adstarted event is dispatched, and show it when adscompleted or adsskipped are dispatched

**Comment by foadabdollahi** [comment]
i think this hidden by css must be act by default to all exist or added control during ads plays.

![12222222222](https://user-images.githubusercontent.com/13816403/96359939-f6ad9d00-1124-11eb-94f8-20e72a4152b1.PNG)

**Comment by rafa8626** [comment]
@foadabdollahi it can be achieved only for custom controls; the ones by default cannot because those can control certain things that are required by the Ads, such as play/pause, volume and fullscreen

**Comment by foadabdollahi** [comment]
ok, if you think it's ok so it must be ok.

**Comment by rafa8626** [comment]
I can add one element to determine if it will be hidden in ads and that should help you

**Comment by rafa8626** [comment]
@foadabdollahi I added one last option when you add a control: `showInAds`. If you set it to false, it won't be displayed by the time Ads are active. Let me know if that worked for you
