### ISSUE TITLE
levels  not work in v2.0

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#172]
in version 2.0 levels not work.

**Comment by rafa8626** [comment]
@foadabdollahi can you give me a URL where I can check this please?

**Comment by foadabdollahi** [comment]
check it please: 
https://nashrin.com/v/fc56

**Comment by rafa8626** [comment]
@foadabdollahi it doesn't work because the structure for controls has changed, as indicated in the migration section. If you use this, it should work:
```javascript
controls: {
   layers: {
       left: ['play', 'time', 'volume'],
       middle: ['progress'],
       right: ['levels', 'captions', 'settings', 'fullscreen'],
    }
}
```

**Comment by foadabdollahi** [comment]
yes, mistake is mine. thanks
