### ISSUE TITLE
cors vtt request

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#173]
load vtt from other source has error 'Unsafe attempt to load URL' also vtt file has cors header 

https://nashrin.com/v/5ops
https://vdn15.nashrin.com/5ops/en.vtt

**Comment by rafa8626** [comment]
@foadabdollahi this is a configuration problem with your VTT files, not with the player. It's very clear what the message indicates:
```Unsafe attempt to load URL https://vdn15.nashrin.com/5ops/fa.vtt from frame with URL https://nashrin.com/v/5ops. Domains, protocols and ports must match.```

One quick thing you can do as far as I know is to set the `crossorigin` attribute in the video tag to `anonymous `. But I always recommend to fix it from the area that serves these files.

Also I see also a warning in terms of MIME types. VTT files should be `text/vtt`.  
```Cross-Origin Read Blocking (CORB) blocked cross-origin response https://vdn15.nashrin.com/ with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.```
