### ISSUE TITLE
select quality base of connection

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#174]
Quality selector ('auto') can base of connection type, like 720p in 4G and 360p for 3G mobile network. 

https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API

**Comment by rafa8626** [comment]
@foadabdollahi I'm working on this. I'll keep you posted once I have this ready to be tested

**Comment by foadabdollahi** [comment]
Hi, i can't find any change.

**Comment by rafa8626** [comment]
@foadabdollahi I’ve been busy this week; let me see if by the end of the week I have this ready

**Comment by rafa8626** [comment]
@foadabdollahi please download the master branch and test if this is working for you

**Comment by foadabdollahi** [comment]
Thanks
