### ISSUE TITLE
Live rmtp

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#175]
enable integrate with flv,js for play rmtp live video

https://github.com/bilibili/flv.js

**Comment by rafa8626** [comment]
@foadabdollahi please download the master branch and test if this is working for you

**Comment by foadabdollahi** [comment]
hi, do you have any document or some help?

**Comment by rafa8626** [comment]
Just set the fly file as a source like any other source the player handles, and to add fly.js configuration elements, use the flv object, like the existing hls or dash objects. I’ll add the docs about this during these next couple of days

**Comment by rafa8626** [comment]
@foadabdollahi check https://github.com/openplayerjs/openplayerjs/blob/master/docs/usage.md#javascript, there's an FLV element to configure it. Other than that, unless you can provide a URL with FLV (either static or live) that I can use to create a CodePen, that's all I can offer as an example

**Comment by rafa8626** [comment]
@foadabdollahi is this good to go? I want to release the next version between today and tomorrow

**Comment by foadabdollahi** [comment]
@rafa8626 Excuse me, I'm busy this week. i try it tomorrow.

**Comment by foadabdollahi** [comment]
hi, it try it and work great.

for suggest you can add live label in control bar by default. I added by addcontrol attribute.  but maybe it can be useful default feature

**Comment by foadabdollahi** [comment]
and how can disable(remove) pause/play button in center in live stream?

**Comment by rafa8626** [comment]
@foadabdollahi I’m glad to hear that; as per the label, the params in the player allow you to show the Live label. Check the documentation

**Comment by rafa8626** [comment]
And to disable the play/pause you can hide it with CSS for now. I wasn’t planning on toggling it via the params but I can consider it for a latter release

**Comment by rafa8626** [comment]
Check here and let me know if that helps: https://github.com/openplayerjs/openplayerjs/blob/master/docs/usage.md#javascript

**Comment by rafa8626** [comment]
@foadabdollahi do you have a URL that I can use to create a CodePen showing how to use the player with flv?

**Comment by foadabdollahi** [comment]
@rafa8626 
Hi,
you can use this:
http://flv.bdplay.nodemedia.cn/live/bbb.flv

**Comment by rafa8626** [comment]
@foadabdollahi thanks I'll include a CodePen in the oncoming release using this URL
