### ISSUE TITLE
Player Size in the configuration

### ISSUE THREAD

**Issue by komato3huk** [openplayerjs/openplayerjs#177]
Hi
Please add to man thats need to resize player

**Comment by rafa8626** [comment]
Hi @komato3huk can you explain more what is what you need from the player in terms of size, please?

**Comment by komato3huk** [comment]
not convenient if you need to insert the player on different sites. Then you need to create a lot of parameters. it would be more convenient to specify the width and height of the player in the parameters.

**Comment by rafa8626** [comment]
If you use CSS to set width/height you can target the class that each player has since it is common for each one of them, so it’s even less code than setting the params in the configuration, does it make sense?

**Comment by rafa8626** [comment]
I assume that to set it in different sites you are using HTML and JS, so is it more convenient to use a <styles> tag within the HTML to achieve this?

**Comment by komato3huk** [comment]
very convenient to specify in the player parameters. similar to loop debug.

**Comment by rafa8626** [comment]
This can be a new feature, so I’ll let you know when I have something you can test

**Comment by rafa8626** [comment]
@komato3huk  I created the `player-sizing` branch for this; you can use the `width` and `height` elements in the player configuration. Please test it and let me know if that works fine for you. Sorry it took me some time to get around this

**Comment by rafa8626** [comment]
@komato3huk I’m planning to release this by the end of the week; if you can confirm this works as expected in the next couple of days  I’d appreciate it
