### ISSUE TITLE
Uncaught TypeError: connection is undefined

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#179]
i use  dist folder js file. and have this error : 
Uncaught TypeError: connection is undefined

![jsssssssssss](https://user-images.githubusercontent.com/13816403/98436911-246a7e00-20f4-11eb-8dab-695b5590f584.PNG)

and i find this error in firefox only

**Comment by rafa8626** [comment]
@foadabdollahi I’ll check this. Thanks for reporting it

**Comment by rafa8626** [comment]
@foadabdollahi this should be fixed now; let me know

**Comment by rafa8626** [comment]
@foadabdollahi is this one good to be closed? It’s in the latest changes of master
