### ISSUE TITLE
Wrong documentation for first quartile and third quartile ad events

### ISSUE THREAD

**Issue by nejcsever** [openplayerjs/openplayerjs#182]
[Api/Events documentation](https://github.com/openplayerjs/openplayerjs/blob/master/docs/api.md#events) defines first and third quartile ad events as `adsfirstquartile` and `adsthirdquartile` which doesn't trigger event handlers. Events handler is triggered when using `adsfirstQuartile` and `adsthirdQuartile` though (upper-cased `quartile`).

I think it's just a matter of updating this section of documentation.

**Comment by rafa8626** [comment]
@nejcsever thanks for noticing this; I’ll update it during the course of the day. Please give the project a star to show your support

**Comment by nejcsever** [comment]
🚀 What a response time. Starred. Thanks! ⭐

**Comment by rafa8626** [comment]
@nejcsever the change is now in master; once I fix one issue I’ll release this. Thanks again for reporting it and for the star 😀
