### ISSUE TITLE
Ads are not scaling when video's size change

### ISSUE THREAD

**Issue by nejcsever** [openplayerjs/openplayerjs#183]
**Description**
Ads are not scaling when video's size change. Video is scaling normally though it's just ads that are stuck on the same size as they were initially loaded.

**Steps to reproduce the behavior:**
1. Open [Ads Codepen example](https://codepen.io/rafa8626/pen/vVYKav).
2. Click play to start the video.
3. Resize video/window.
4. You can see that ad size stays fixed and is not scaling with the actual video container.

**Expected behavior**
Ads should be scaled to the video container (just like the actual video content is scaling).

**Screencast**
I've recorded a screen recording which I think nicely displays the issue. Here's the link to the video:
https://drive.google.com/file/d/17_jlqGnMzpFGADWfsovOXLnALJAAAa2a/view?usp=sharing

In the video you can see that when ad is playing and window is resized, ad is not scaling with the actual video container. When the ad stops and window is scaled down you can see that video scaling works normally.

**Environment**
 - OS: maxOS
 - Browser: chrome
 - Version: 2.1.2

**Comment by rafa8626** [comment]
@nejcsever thanks for reporting this; I’ll take a look and keep you posted

**Comment by rafa8626** [comment]
@nejcsever I have fixed this; please download the master branch and let me know if it worked for you. If so, I'll release this patch

**Comment by nejcsever** [comment]
Seems to be working. Thank you!

**Comment by rafa8626** [comment]
you are welcome; releasing the patch
