### ISSUE TITLE
Add option to 'contain' video when in fill display mode

### ISSUE THREAD

**Issue by nejcsever** [openplayerjs/openplayerjs#184]
**Description**
I would like to be able to use 'fill' mode but without scaling and cropping the video but instead **containing** it. This way video would be filled vertically or horizontally depending on site's aspect ratio and video aspect ratio.
Imagine it's the same scaling as in fullscreen mode but not scaled to an actual screen but to the website (like 'fill').

**Describe alternatives you've considered**
Alternative would be to dynamically adjust the size of container in which video is displayed, but I think that this scaling logic would be the same as in fullscreen, but just filled to the whole website. That's why I think it would be a nice added feature.

**Additional context**
I think this could be added to `mode` parameter as `fill-contain` value. It's the same principle as `object-fit: contain;` in css language. Or this `mode` parameter could even be expanded into it's own object, so it would be something along those lines:
```
playerOptions = {
    ...
    display: {
        mode: 'fill',
        scaling: 'contain'
    }
    ...
}
```
Above proposed solution maybe adds extensibility to the current mode. E.g.: there could be padding property or some other custom styling parameters added. Just throwing this idea out here... 😄 

Here is an image presenting how I imagine this would look like comparing to the current `fill` mode:
![fill-contain-demonstration](https://user-images.githubusercontent.com/219859/100280399-6b67c880-2f68-11eb-873d-12fa55fb6669.png)

Hope it makes sense, but if it's not let me know and I can try explaining it further. 🙂

**Comment by rafa8626** [comment]
@nejcsever that is an interesting suggestion; if you want to prepare a PR for this, I could certainly review it and include it as part of the next release. If not, I’ll take a look when I have a chance

**Comment by rafa8626** [comment]
@nejcsever I created the `player-sizing` branch for this; you can use the `fit` mode. Let me know if that works fine for you

**Comment by nejcsever** [comment]
🙌 Works as I imagined it. Thank you very much!

**Comment by rafa8626** [comment]
You are welcome, I’ll try to release this by the end of the week if possible. Thanks for the suggestion

**Comment by nejcsever** [comment]
Hey @rafa8626 

Looks like 'fit' mode only works in 2.2.0 and is broken in 2.2.1.

**Comment by rafa8626** [comment]
I checked it in 2.2.1 and it seemed fine; can you point an example or CodePen where it is not working for you?

**Comment by nejcsever** [comment]
You can see that in the actual 'fit' codepen: https://codepen.io/rafa8626/pen/abmboKV

If you change Pen settings of openplayer cdn link from:
`https://cdn.jsdelivr.net/npm/openplayerjs@2.2.1/dist/openplayer.min.js`
to
`https://cdn.jsdelivr.net/npm/openplayerjs@2.2.0/dist/openplayer.min.js`

there you can see that the video doesn't fit the whole screen anymore.

**Comment by rafa8626** [comment]
@nejcsever can you check the CodePen once more and confirm that is what you expect please? The idea of fit is that it will fit the parent container, so if what you see is correct, then I need to add a few styles

**Comment by nejcsever** [comment]
Oh, I thought that it would be the same as 'fill' so basically fill the whole window, but the sizing of video would be fit/cover instead of scale/crop. Basically I imagined the behaviour to be exactly like it is in version 2.2.0 😄 (it fill the whole page but doesn't crop the video content)

**Comment by rafa8626** [comment]
Gotcha; in 2.2.0 I noticed that the player was not wrapped properly but it caught the body's position, and that made it look like  it was going to take the whole screen, but in 2.2.1 I caught that and fixed it. At the end of the day, the fit will adapt to the dimensions of the parent container, so if you set the dimensions properly in the parent, it will work as expected

**Comment by nejcsever** [comment]
Oh, ok I see. I was just a bit confused because `2.2.1` release had different behaviour than the version on `player-sizing` branch. But I understand. That works too. 🙂 Thanks for explanation. 🙏 

Just one more side question if I may. Currently video is not fitting if the size of video's custom container, for example:
```
<div id="custom-video-wrapper" style="width: 500px; height: 500px;">
  <video class="op-player__media" id="video" controls playsinline>
      <source src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" type="video/mp4">
  </video>
</div>
```
You can see here that `custom-video-wrapper` div is wrapping the video element, but video element doesn't adjust it's size to it. You have to manually override `op-player__fit--wrapper` if you want to alter that.
Is that behaviour on purpose or should it be default styling something like in code below?
```
.op-player__fit--wrapper {
  width: 100%;
  height: 100%;
  ...
}
```

**Comment by rafa8626** [comment]
if anything, by default, it must have the width/height set for the wrapper; I don't know if it's better to use percentage or vh/vw

**Comment by rafa8626** [comment]
@nejcsever  after checking this some more, I decided to use percentages; I modified the CodePen to reflect the change, so I'll add the styles and they will be part of the oncoming release, once I complete the non-linear Ads feature, but in the mean time you can use it like the CodePen shows
