### ISSUE TITLE
Non linear VAST Compatibility

### ISSUE THREAD

**Issue by Rubioli** [openplayerjs/openplayerjs#186]
First of all, such a great player!

I was wondering if currently is possible for having Non-linear VAST and if not is there a feature that is in the plan :)?

Thanks

**Comment by rafa8626** [comment]
@Rubioli if you have a URL where I can check the non-linear VAST I can see how the player can support it.

If you can also star the project to show your support I’d appreciate it

**Comment by Rubioli** [comment]
@rafa8626 Thanks for your reply

You can use this VAST code for non-linear test: https://pubads.g.doubleclick.net/gampad/ads?sz=480x70&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dnonlinear&correlator=


Google has a bunch of VAST and VPAID sample as well here: https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags

**Comment by rafa8626** [comment]
@Rubioli Thanks for the info; I'll test the first source and check if it plays. If not, I'll adapt the code to play non-linear ads. As per the ability to run both linear and non-linear, I need to check how IMA SDK does this, since that's the library I'm using for ads

**Comment by rafa8626** [comment]
@Rubioli please download the master branch and let me know if you can see the non-linear ads; if you have a sample where you combine linear with non-linear to see if it will work. Let me know.

**Comment by rafa8626** [comment]
could you give the project a star to show your support please?

**Comment by rafa8626** [comment]
@Rubioli since we support non-linear ads I’ll close this and release this today. Thanks for submitting this request
