### ISSUE TITLE
(Feature request) Ability to disable the seekbar?

### ISSUE THREAD

**Issue by MarshmelloSUCKS** [openplayerjs/openplayerjs#187]
**Is your feature request related to a problem? Please describe.**
I plan on using OpenPlayerJS as a replacement to the HTML5 player for my IceCast stream. Because it's live, I have no need for the seekbar.

**Describe the solution you'd like**
I'd like to be able to disable the seekbar.

**Describe alternatives you've considered**
I'm not aware of any.

**Additional context**
I'm currently using it on my testing page, view it [here](https://ice1.msx.gay/test.html) if you'd like.

**Comment by rafa8626** [comment]
@MarshmelloSUCKS I think what you are looking for is achieve via the controls configuration, like this
```javascript
controls: {
        alwaysVisible: false,
        layers: {
            left: ['play', 'time', 'volume'],
            middle: [],
            right: ['captions', 'settings', 'fullscreen'],
        }
    },
```
if you wanna truly disable it, because there's no flag to just hide it, and since your intention is not to use it at all, then this will satisfy your need.

Let me know if that works and please star the project to show your support. Thanks!

**Comment by MarshmelloSUCKS** [comment]
Would I place that in a `<script>` block?

**Comment by rafa8626** [comment]
@MarshmelloSUCKS you will need to remove first the `op-player` and add an ID from the audio tag, and then, after the openplayer.js, you will add a script tag as follows:
```javascript
var player = new OpenPlayer('[AUDIO ID]', {
   controls: {
        layers: {
            left: ['play', 'time', 'volume'],
            middle: [],
            right: ['captions', 'settings', 'fullscreen'],
        }
    },
});
player.init();
```
and that should do it

**Comment by MarshmelloSUCKS** [comment]
Having a bit of an issue doing that. I added in the script:
```<div class="player"><audio id=kmsx controls playsinline><source src="https://ice1.msx.gay:8443/kmsx.aac" type="audio/aac"></audio>
<script src="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.js"></script>
<script>
var player = new OpenPlayer('kmsx', {
   controls: {
        layers: {
            left: ['play', 'time', 'volume'],
            middle: [],
            right: [],
        }
    },
});
player.init();
</script>```
but when I refresh the page, the native HTML5 player shows

**Comment by rafa8626** [comment]
@MarshmelloSUCKS I see this in your snippet: `id=kmsx` and it should be `id="kmsx"`; also, the div is not closed so after the `audio` closing tag,  add the closing tag for the div; that should work for you

**Comment by MarshmelloSUCKS** [comment]
That div element is there to restrict the width of the player and the title text below it. Here's a full snippet of it:
```
<div class="player"><audio id="kmsx" controls playsinline><source src="https://ice1.msx.gay:8443/kmsx.aac" type="audio/aac"></audio>
<script src="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.js"></script>
<script>
var player = new OpenPlayer('kmsx', {
   controls: {
        layers: {
            left: ['play', 'time', 'volume'],
            middle: [],
            right: [],
        }
    },
});
player.init();
</script>
<small><b>Now playing:</b> <span id=txt></span></small></div>
```
Updated and still getting the default player.

**Comment by rafa8626** [comment]
you removed the `op-player__media` class from the audio tag; that's why it's not setting anything
```html
<div class="player"><audio id="kmsx" class="op-player__media" controls playsinline><source src="https://ice1.msx.gay:8443/kmsx.aac" type="audio/aac"></audio>
<script src="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.js"></script>
<script>
var player = new OpenPlayer('kmsx', {
   controls: {
        layers: {
            left: ['play', 'time', 'volume'],
            middle: [],
            right: [],
        }
    },
});
player.init();
</script>
<small><b>Now playing:</b> <span id=txt></span></small></div>
```

**Comment by MarshmelloSUCKS** [comment]
Oh. It works now, thanks!

**Comment by rafa8626** [comment]
You are welcome; if you could star the project to show your support, I'd appreciate it. Thanks!
