### ISSUE TITLE
PageSpeed Insights Errors

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#188]
hi,
i check my pages with PageSpeed Insights. and see some item with new version 2.2.1

![image](https://user-images.githubusercontent.com/13816403/100837169-f1fb3900-3485-11eb-8a40-203bc7620449.png)
![image](https://user-images.githubusercontent.com/13816403/100837206-04757280-3486-11eb-9715-8fcce82735a1.png)
![image](https://user-images.githubusercontent.com/13816403/100837621-2d960300-3486-11eb-8d07-4fecb7b2994c.png)

**Comment by rafa8626** [comment]
@foadabdollahi you didn’t see these ones in 2.0.0 or 2.2.0?

**Comment by foadabdollahi** [comment]
i have not 'avoid serving lagacy ...' in  2.0.0 
but passive listerner i see later

**Comment by rafa8626** [comment]
Ok I’ll check it and see what can be done to remove most of the warnings you are showing me

**Comment by rafa8626** [comment]
@foadabdollahi please download the master branch and test it once more. The only warning I cannot get rid of is the `Remove unused Javascript`, since that contains code for other features that you may not be using, so that's expected. The legacy code and the passive listeners should be fixed now

**Comment by rafa8626** [comment]
Once you confirm this, I'll release these changes

**Comment by foadabdollahi** [comment]
yes it has not error yet.
thanks

**Comment by rafa8626** [comment]
Thanks @foadabdollahi I’ll release this today
