### ISSUE TITLE
run ads with other sdk

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#190]
Hi,
it's a question : can you add new ad sdk (not imasdk.googleapis). and reason it i have my cdn and all of my js load from my domain and i can use imasdk.googleapis locally and must load google servers.

some things like : 
https://github.com/dailymotion/vast-client-js
https://github.com/fluid-player/fluid-player/blob/master/src/modules/vpaid.js
https://github.com/fluid-player/fluid-player/blob/master/src/modules/vast.js

**Comment by rafa8626** [comment]
@foadabdollahi this player’s code uses only IMA SDK and right now it can’t use another ads library because each library requires specific code. The only thing you can do is to set where IMA SDK is
