### ISSUE TITLE
Not able to preload ads and start video via API

### ISSUE THREAD

**Issue by nejcsever** [openplayerjs/openplayerjs#191]
This is not a bug per-se, but just an issue that I'm currently having.

What I would like to achieve is to "preload" the ads and when this is done, starting the video player via `player.play()` to start playing.

For some reason I can't get this to work in any combination using `player` API calls.

@rafa8626 do you have any suggestions of how I could achieve something like that?

The flow in the shortest way possible would look something like this:
```
player.loadAds().then(() => player.play());
```

Is something like this achievable? I wasn't able to get this working with current implementation.

**Comment by rafa8626** [comment]
@nejcsever if what you are looking for meets this: https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/preload I can add the necessary code to make it  work like that. Let me know if it makes sense and that’s what you are looking for; otherwise it may be more difficult to implement

**Comment by nejcsever** [comment]
Maybe this would also solve this issue, but I think the problem lays somewhere else and I think the logic is already implemented, but just running somehow in different execution stage. Let me try to explain what I mean in more details with some code samples :)

If we forget about loading ads for a second, the first thing that I would like to achieve is to start playing video with `player.play()` API command (from an outside event). I'm currently encountering two issues with this.

**First is a really basic init and play example:**
```
const player = new OpenPlayerJS('video1', {
  ads: {
    src: 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator='
  }
});
player.init();
player.play();
```
Above code fails with error
```
Uncaught (in promise) TypeError: Cannot read property 'initialize' of undefined
    at Ads._initNotDoneAds (ads.js:410)
    at play (ads.js:95)
```

**The second example which presents the issue that I'm having is this:**

```
const player = new OpenPlayerJS('video1', {
  ads: {
    debug: true,
    src: 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator='
  }
});
player.init();

var playerElement = player.getElement();
playerElement.addEventListener('play-video', (e) => {
  player.play();
})

setTimeout(() => playerElement.dispatchEvent(new Event('play-video')), 1000);
```

Above code fires `play-video` event after 1 second (which in this case in an ugly way solves the first issue). When event is fired you can see from the console log (notice that debug flag is set to true) that ads are loaded, but for some reason it doesn't want to start playing the video. You can copy-paste this snippet into [Ads Example CodePen](https://codepen.io/rafa8626/pen/vVYKav) to reproduce this issue.

So even getting this `player.play()` to work as expected would be a really great thing for me!


Now if we return to the load ads added feature (if this play issue can be fixed), I would basically like to be able to fire this ad loading which happens in example no. 2, with a separate command, something like `player.loadAds()`.

So if I just modify code from example no. 2 a bit, this would look something like this (notice how load ads and video play command are called from different events):
```
const player = new OpenPlayerJS('video1', {
  ads: {
    debug: true,
    src: 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator='
  }
});
player.init();

var playerElement = player.getElement();
playerElement.addEventListener('preload-ads', (e) => {
  player.loadAds();
})
playerElement.addEventListener('play-video', (e) => {
  player.play();
})
```

I'm assuming that this `loadAds` would just call `adsLoader.requestAds(this.adsRequest);` on demand, not just when play command happens.

Let me know if this makes things clearer. I can provide further info if it's still unclear what's the issue I'm facing.

Thanks!

**Comment by rafa8626** [comment]
@nejcsever thanks for the thorough explanation; let me see what I can do to help you with this, but it may take some time. So as soon as I’m not as busy as I am right now I’ll get to this

**Comment by rafa8626** [comment]
@nejcsever I think I got it; download the master branch and use the following snippet to solve your problem:
```javascript
const player = new OpenPlayerJS('player1', {
  ads: {
      debug: true,
      enablePreloading: true,
      src: 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator='
  }
});
player.init();
player.getElement().addEventListener('adsloaded', () => {
    player.play();
});
```

Let me know if it works as expected; otherwise I'll reopen the ticket

**Comment by nejcsever** [comment]
@rafa8626 I think it's almost there, but there's still a slight issue. I've tried your snippet, but now player starts playing ad on `player.init()` automatically. Or is that happening only to me?

So here's the snippet without `adsloaded` event listener from your example:
```
const player = new OpenPlayerJS('video1', {
  ads: {
      debug: true,
      enablePreloading: true,
      src: 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator='
  }
});
player.init();
```

This for me still starts playing ad.

If this snippet would just load ads and not start start playing the ad, that would be perfect 😄

**Comment by rafa8626** [comment]
@nejcsever you are right; let me see what happened there and get back to you

**Comment by rafa8626** [comment]
@nejcsever I figured it out; please download the master branch one more and test the snippet I sent you. I forgot to add a couple of conditionals to ensure the loading of ads happen initially but until you dispatch a Play event everything will run. Let me know if it works for you now

**Comment by nejcsever** [comment]
Works like a charm, perfect! Thank you very much! 🙏

**Comment by rafa8626** [comment]
@nejcsever thanks for confirming this; I'll set the release tonight with this change

**Comment by nejcsever** [comment]
@rafa8626 sorry, just an additional question, not sure if this feature caused this issue or not, but after this snippet is executed:
```
const player = new OpenPlayerJS('video1', {
  ads: {
    src: 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator='
  }
});
player.init();
player.getElement().addEventListener('adsloaded', () => { 
    player.play()
});
```

If you click pause when ad starts playing and then try to play it again (by clicking play button or calling `player.play()`) it doesn't continue playing it, ad stays paused 😬

**Comment by rafa8626** [comment]
@nejcsever I think it's fixed; please download the master branch once more and let me know if it works correctly

**Comment by nejcsever** [comment]
Seems to be working now, yes 🙂

**Comment by rafa8626** [comment]
@nejcsever can you test one more time and let me know if all is working as expected, please?

**Comment by nejcsever** [comment]
Checked again and everything works as expected.

**Comment by rafa8626** [comment]
Thansk
