### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#192]
when i update new release. this issue appeared.
when ad play i puase it and after play again not work and this error logged in console
![image](https://user-images.githubusercontent.com/13816403/102693631-40078f00-4231-11eb-96e0-f718caa55eec.png)

**Comment by rafa8626** [comment]
@foadabdollahi I have fix for it, although the warning is something I'll address later today

**Comment by rafa8626** [comment]
can you check if the master branch works for you please?

**Comment by rafa8626** [comment]
@foadabdollahi I may need to change the approach to fix the passive event error a little bit; I’ll let you know when it’s ready to be tested

**Comment by rafa8626** [comment]
@foadabdollahi fix is ready; please check one more time and let me know if it works; once you confirm I'll release the patch
