### ISSUE TITLE
Preroll runs with sound even though video is muted

### ISSUE THREAD

**Issue by zgomotos** [openplayerjs/openplayerjs#193]
**Describe the bug**
Hello, Rafael! 

Thank you for making this project possible. It seems that after the last update, the preroll ads are playing with sound, even though the player is muted. Media plays as expected -> muted.  

**To Reproduce**
I have included a fiddle with the player code and the Google Ad Manager preroll code: https://jsfiddle.net/z7d0j5hc/1/
Using v2.2.2 doesn't have this issue.

**Expected behavior**
The preroll video ad should be also muted 

**Additional context**

Thank you for your time and greetings from Romania!

**Comment by rafa8626** [comment]
@zgomotos thanks for reporting this; I’ll take a look and let you know. Please give the project a star to support the project

**Comment by rafa8626** [comment]
@zgomotos please download the master branch and check if it works correctly for you. If so, I'll release this patch as soon as possible. Thanks again :)

**Comment by rafa8626** [comment]
@zgomotos let me know if it works for you, or I can reopen the issue if not
