### ISSUE TITLE
Multi subtrack issue

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#195]
Hi,
i know when i have multi track link like this:
```
       <video class="op-player__media" id="player" controls playsinline>
            <source src="/path/to/video.mp4" type="video/mp4">
            <track kind="subtitles" src="/path/to/en.vtt" srclang="en" label="English">
            <track kind="subtitles" src="/path/to/fa.vtt" srclang="fa" label="Farsi">
        </video>
```
only first track work. and if i use "default" attribute for load default 

`            <track kind="subtitles" src="/path/to/fa.vtt" srclang="fa" label="Farsi" **default**>`

not loaded

**Comment by rafa8626** [comment]
@foadabdollahi thanks for reporting this; I’ll check it and let you know when fixed

**Comment by rafa8626** [comment]
@foadabdollahi I checked this and I didn't see any issues; the only thing I noticed is that the CC button is not highlighted and that I need to fix, but other than that I was able to play the captions correctly. If you are using URLs make sure the protocols coincide with your website and CORS are not an issue; other than that, unless you gave me a CodePen where I can see the issue, there's not much I can do about this.

**Comment by foadabdollahi** [comment]
thanks for your check

no, it's not for cors. last player i use before openplayer it work true
i create an live sample for test and tell you  tomorrow.

**Comment by foadabdollahi** [comment]
please check it: 
https://codepen.io/foadabdollahi/pen/dypddBa

**Comment by rafa8626** [comment]
Ok I’ll check it; do the captions can play correctly using localhost? Just because in the past CodePen has had problems reading captions from a different domain and I think this is not the exception

**Comment by foadabdollahi** [comment]
yes in local work but this icon not work.
[index.zip](https://github.com/openplayerjs/openplayerjs/files/5757478/index.zip)
![image](https://user-images.githubusercontent.com/13816403/103414205-387da980-4b92-11eb-9c26-7cafe2b05cda.png)

**Comment by rafa8626** [comment]
@foadabdollahi yes that’s what I saw yesterday. The captions work but not the button correctly; that’s what I’ll be looking at and let you know when fixed

**Comment by rafa8626** [comment]
@foadabdollahi this should be fixed now; I checked your zipped file and then added default to the last track and worked as expected. Please download the master branch and check if this works as expected since I found a fix for the captions button

**Comment by foadabdollahi** [comment]
thank's,
I check it and default work but 'Off' have check icon yet.
![image](https://user-images.githubusercontent.com/13816403/103453316-f7021100-4ced-11eb-8251-217e6e744bab.png)

**Comment by rafa8626** [comment]
@foadabdollahi let me check that and get back to you; I didn’t notice it before

**Comment by rafa8626** [comment]
@foadabdollahi I couldn't replicate it with the current master branch
<img width="472" alt="Screen Shot 2021-01-02 at 11 04 05 AM" src="https://user-images.githubusercontent.com/910829/103461170-53633180-4cea-11eb-9999-03ac3533576d.png">

**Comment by rafa8626** [comment]
@foadabdollahi is this one good to be closed now?

**Comment by foadabdollahi** [comment]
yes thanks.
