### ISSUE TITLE
save last quality selected

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#196]
Hi again.
when I change quality from auto to 360p. in next page or refresh quality change to auto again. can you save selected quality in some where like localstorage ?

**Comment by rafa8626** [comment]
@foadabdollahi I will add a levelchanged event so you can create the workflow yourself to save the selected level in local storage; and with the current configuration you can preselect the desired level

**Comment by foadabdollahi** [comment]
can you help me for find related document?

**Comment by rafa8626** [comment]
@foadabdollahi there’s no documentation yet; once I have the 2 items ready for you I’ll let you know

**Comment by rafa8626** [comment]
@foadabdollahi please download the master branch and check the changes for the levels element and see if that works for you

**Comment by foadabdollahi** [comment]
thanks, i see "levelchanged" event document. but i can find how can set one level in initial config.

**Comment by rafa8626** [comment]
@foadabdollahi use the defaultLevel configuration, and that should be a number not a label

**Comment by rafa8626** [comment]
@foadabdollahi I updated the documentation; check the last commit on the master branch. If you are ok with the approach, I'll close this

**Comment by foadabdollahi** [comment]
thanks

**Comment by foadabdollahi** [comment]
i check again and have error. if i set defaultLevel more than 0 it work true. but when 0 index set that not set 0 and set -1. and i think problem is here:

`"".concat(this.player.getOptions().defaultLevel || this.player.getMedia().level)`

```
"".concat(0 || -1) //=> "-1" problem here
"".concat(1 || -1) //=> "1"
```

**Comment by rafa8626** [comment]
@foadabdollahi great catch; I’ll fix that and let you know

**Comment by rafa8626** [comment]
@rafa8626 ok change pushed; please download the master and let me know if it's fixed

**Comment by rafa8626** [comment]
@foadabdollahi is this good to be closed? I need to release an important fix and I want to release this tomorrow as well

**Comment by foadabdollahi** [comment]
Hi,
no problem not solved, when i set defaultLevel that set but in UI auto always checked.

**Comment by foadabdollahi** [comment]
if have some hot fix you can solve it after release

**Comment by foadabdollahi** [comment]
and i have a problem with hls. can I have level in hls ? do you have any sample?

**Comment by rafa8626** [comment]
@foadabdollahi ok I’ll check the UI issue; shouldn’t be something difficult to fix. As per the HLS I have a sample but I haven’t tried this feature in it. I’ll take a look at you CodePen and let you know

**Comment by foadabdollahi** [comment]
maybe it can be helpfull
https://github.com/video-dev/hls.js/blob/master/docs/API.md#quality-switch-control-api

**Comment by rafa8626** [comment]
Yeah I’ve used that when I was working with levels, but I need to check if there’s something else I omitted. I’ll keep you posted. Thanks for bringing that up

**Comment by rafa8626** [comment]
@foadabdollahi can you post a sample for the regular levels (not using HLS) so I can test my solution please?

**Comment by rafa8626** [comment]
@foadabdollahi I think I got it finally. Please download the master branch and test this again; it should work for HLS as well without anything out of the ordinary, but you need to indicate the `levels` item in your control configuration to make it work with HLS and HTML5

**Comment by foadabdollahi** [comment]
Prefect. it work.
thanks.

**Comment by foadabdollahi** [comment]
I found new issue. when i use hls always volume is mute. but in mp4 work correctly.

**Comment by rafa8626** [comment]
@foadabdollahi I’ll check that as well; thanks for testing it

**Comment by rafa8626** [comment]
@foadabdollahi I checked the HLS using your source and the snippet I posted above and I couldn't replicate the muted issue; do you have another sample I need to check?

**Comment by foadabdollahi** [comment]
please check it : https://nashrin.com/v/jwxa

**Comment by rafa8626** [comment]
@foadabdollahi it doesn't have it often and this has to do mostly with the browser policies. It doesn't matter if it's HLS or HTML5, the player checks if the browser can auto play with/without volume. See https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#new-behaviors

**Comment by foadabdollahi** [comment]
no i know browser policy.

if you check this page: https://nashrin.com/v/6xxd (source mp4)

and compare with https://nashrin.com/v/jwxa (source hls)

hls default is mute but mp4 is not

**Comment by rafa8626** [comment]
@foadabdollahi I see the same happening with MP4; it is driven by the browser's policies with autoplay. See the attached screenshots:
<img width="931" alt="Screen Shot 2021-01-06 at 5 11 40 PM" src="https://user-images.githubusercontent.com/910829/103824666-648da480-5042-11eb-91be-b35d25865b63.png">
<img width="930" alt="Screen Shot 2021-01-06 at 5 11 51 PM" src="https://user-images.githubusercontent.com/910829/103824669-65bed180-5042-11eb-9832-24962d28458c.png">

**Comment by foadabdollahi** [comment]
in my phone (android 6 chrome last version) in mp4 and HLS have difference behavior

**Comment by foadabdollahi** [comment]
in hls "allow sound" permitting not get but in mp4 after first click get Allow sound for ever but only in mp4 resource not hls

![photo_2021-01-07_12-57-43](https://user-images.githubusercontent.com/13816403/103876171-935e5600-50e8-11eb-96bb-6bf2b05e2e5b.jpg)
![photo_2021-01-07_12-57-30](https://user-images.githubusercontent.com/13816403/103876515-f94add80-50e8-11eb-92c8-b3ae66e100a4.jpg)

**Comment by rafa8626** [comment]
@foadabdollahi good points; I don’t have an android phone but I can say that If the browser can support HLS it will use a native approach, not HLS.js so I need to check that; that’s part of the problem here

**Comment by rafa8626** [comment]
@foadabdollahi Please download the master branch and test the feature again; you will be able to see the levels now in mobile as expected. As far as the unmute feature, I haven't been able to replicate this. Even I tried Browserstack and I see the same behavior consistently for mp4/m3u8 files. See attached screenshots
<img width="440" alt="Screen Shot 2021-01-07 at 4 05 33 PM" src="https://user-images.githubusercontent.com/910829/103945580-65d2d600-5103-11eb-9154-e88b1c946fd5.png">
<img width="508" alt="Screen Shot 2021-01-07 at 4 06 09 PM" src="https://user-images.githubusercontent.com/910829/103945582-666b6c80-5103-11eb-8e82-a9a4fe740cb8.png">
<img width="498" alt="Screen Shot 2021-01-07 at 4 06 20 PM" src="https://user-images.githubusercontent.com/910829/103945584-67040300-5103-11eb-8423-d26bfa841da6.png">

**Comment by foadabdollahi** [comment]
thanks, levels in mobile fixed but I have problem mute in Hls yet.  for now in hls i have "Allow sound" but need to tap to unmute.

**Comment by rafa8626** [comment]
Yeah I’ll continue researching about it but I don’t think I can do much about it since that relies on browser policies; my only advise will be to remove auto play and after init() you put play(), although I don’t know how it will behave for mobile
