### ISSUE TITLE
 TypeError: Cannot read property 'setVolume' of null

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#198]
when vast xml is empty(no have any ad for show) in change volume error:

```
<VAST>There is no ad to show with your specifications.</VAST>
```

Uncaught TypeError: Cannot read property 'setVolume' of null

![Untitled](https://user-images.githubusercontent.com/13816403/103748464-698a2e00-5019-11eb-92f1-4dda1d185765.jpg)

**Comment by foadabdollahi** [comment]
and also loading always show

**Comment by rafa8626** [comment]
Do you have a URL I can use to test my fix please?

**Comment by rafa8626** [comment]
@foadabdollahi please download the master branch again and let me know if it works as expected

**Comment by foadabdollahi** [comment]
i think proble not solved
please check it
https://nashrin.com/v/581n

when ad not load seek bar not work

**Comment by rafa8626** [comment]
@foadabdollahi I checked your page and I cannot see the issue with the seek bar. I can move to any position

**Comment by foadabdollahi** [comment]
I check again and sure have any problem with empty vast xml. and when I comment ads option it work again.

![image](https://user-images.githubusercontent.com/13816403/103867797-33ae7d80-50dd-11eb-8dcf-322707cd4f96.png)

**Comment by rafa8626** [comment]
@foadabdollahi got it; let me check what’s broken because I didn’t see any errors coming up from IMA SDK

**Comment by rafa8626** [comment]
@foadabdollahi please download the master branch and test this again; I figured out your problem finally

**Comment by foadabdollahi** [comment]
Yes, it's fixed.
thanks

**Comment by rafa8626** [comment]
you are welcome

**Comment by foadabdollahi** [comment]
excuse me. but i check again in my mobile and see not fixed 😥

**Comment by rafa8626** [comment]
I tried on my emulator and I see it playing correctly and I can use the slider without issues

**Comment by foadabdollahi** [comment]
maybe can be help

https://user-images.githubusercontent.com/13816403/103900819-83a53880-510d-11eb-9756-af5cc845b077.mp4

**Comment by rafa8626** [comment]
nothing comes up in the video

**Comment by foadabdollahi** [comment]
@rafa8626 can you check it?
https://github.com/openplayerjs/openplayerjs/files/5782040/output.zip

**Comment by rafa8626** [comment]
@foadabdollahi it's weird because if I use this: 
```html
<video id="player" class="op-player__media" playsinline controls autoplay crossorigin="anonymous"> 
        <source src="https://vs2.cdn.nashrin.com/a/jjjjjjjj/all.m3u8">
      </video>
      <script src="dist/openplayer.min.js"></script>
      <script>
        const player = new OpenPlayerJS('player', {
            defaultLevel: 1,
            ads: {
                src: '<VAST>There is no ad to show with your specifications.</VAST>'
            },
            controls: {
                layers: {
                    left: ['play', 'time', 'volume'],
                    middle: ['progress'],
                    right: ['levels', 'captions', 'settings', 'fullscreen'],
                }
            },
            hls: {
                enableWorker: true,
            }
        });
        player.init();
      </script>
```
It works fine in desktop and mobile, but your link doesn't. Makes me wonder if something is not updated on your side

**Comment by foadabdollahi** [comment]
i can't find any difference.
but i  check remote debugging my mobile chrome and see an error that not see in desktop

![image](https://user-images.githubusercontent.com/13816403/103940522-b0c00e00-5142-11eb-8c1e-14701296306b.png)

**Comment by rafa8626** [comment]
@foadabdollahi I finally got it; it was a conditional that shouldn't be there. I'll push the fix in a bit

**Comment by rafa8626** [comment]
@foadabdollahi please download the master branch and test this one more time, and let me know if it works

**Comment by foadabdollahi** [comment]
thanks, it;'s fixed
