### ISSUE TITLE
after fullscreen in vertical Video

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#201]
Hi,
If set in option mode :'fit'  and a video with rate 1:1 for example or height>width after one time click fullscreen and un-fullscreen vidoe  video go to full but contaner still fill 
![image](https://user-images.githubusercontent.com/13816403/105022281-d2809580-5a5e-11eb-8f9f-b7a98c4d4eea.png)
![image](https://user-images.githubusercontent.com/13816403/105022310-dc09fd80-5a5e-11eb-8954-dd249f0e22a8.png)

**Comment by rafa8626** [comment]
@foadabdollahi can you provide me a Code Pen so I can check this issue please?

**Comment by foadabdollahi** [comment]
ok i do it in next hour
bu you can see it in this page
first click fullscrean and then unfullscreen 
https://nashrin.com/v/djxx
half of page is show

**Comment by rafa8626** [comment]
@foadabdollahi please download the master branch and let me know if this is fixed

**Comment by rafa8626** [comment]
@foadabdollahi all good with this or does it need to be reopened?

**Comment by foadabdollahi** [comment]
@rafa8626  excuse me i have busy days but i check it now and it is fixed 
thanks

**Comment by rafa8626** [comment]
@foadabdollahi no problem; glad it’s fixed
