### ISSUE TITLE
Error handler doesn't fire for particular VAST error code

### ISSUE THREAD

**Issue by nejcsever** [openplayerjs/openplayerjs#205]
**Description**
Error handler function doesn't catch `VIDEO_PLAY_ERROR`/`400 VAST Error` ad error when autoplay is disabled (for example no-browser interaction). `onError` function or `playererror` event listener should catch errors from IMA SDK, but in some cases (e.g. autoplay) errors are not caught.  

**To Reproduce**
Try to not interact with browser (for me this is Google Chrome) while page executes the following code (modified snippet code from https://codepen.io/rafa8626/pen/vVYKav):
```
const player = new OpenPlayerJS('video1', {
    ads: {
        debug: true,
        enablePreloading: true,
        src: 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator='
    },
    onError: () => console.error("ERROR OCCURED")
});
player.init();
player.getElement().addEventListener('adsloaded', () => {
    player.play();
});
```

**Expected behavior**
`ERROR OCCURED` should be printed in error console when there was no interaction with the browser (autoplay not possible).

**Additional context**
Here's the logged line from ima SDK debug output:
```
[ima.admanager.VideoAdManager]  Playback error: [object Object] AdError 400: There was an error playing the video ad. Caused by: AdError 1205: The browser prevented playback initiated without user interaction.
```

It's weird that error is logged from IMA SDK debug, but not propagated to error handler.

**Comment by rafa8626** [comment]
@nejcsever im the code I set up a distinction between warnings and errors in the Ads, since the errors must destroy the Ads manager but not the warnings. I can definitely check that and dispatch the error player even if they are warnings

**Comment by rafa8626** [comment]
@nejcsever I reviewed some more your code and my first question is: why do you add enablePreloading and then play? I think the conflict comes from there, but I tried to look more into the IMA docs and this error for some reason is not triggered as part of its error event; I don’t know how to catch this one, but I’ll keep looking

**Comment by nejcsever** [comment]
@rafa8626 Yeah I tried catching it too but couldn't do it. I saw one example using AdEvent.LOG which might be able to catch non-fatals (haven't tried it).

https://ads-developers.googleblog.com/2016/09/fatal-versus-non-fatal-errors-in-ima.html

That post is from 2016, but probably still applies. Maybe LOG AdEvent should also propagate through player from IMA SDK?

Regarding autoplay trigger. I didn't find a way to check if autoplay is possible or not with the player, that's why I can only rely on events from the player. Correct me if I'm wrong.

**Comment by rafa8626** [comment]
@nejcsever I’ll check that link and see what I can do; in terms of auto play, you can add the autoplay attribute in the video tag and that should do it since that’s an HTML5 standard

**Comment by rafa8626** [comment]
@nejcsever I added the LOG event (among others) now; even though I added them, it didn't make a difference. But using the following snippet, your player will work as expected (it won't go to error unless there's a serious bug):
```html
<video id="video1" class="op-player__media" controls playsinline autoplay>
  <source src="http://clips.vorwaerts-gmbh.de/VfE_html5.mp4" type="video/mp4">                
</video>

<script>
const player = new OpenPlayerJS('video1', {
    ads: {
        debug: true,
        src: 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator='
    },
    onError: () => console.error("ERROR OCCURED")
});
player.init();
</script>
```

Please download the master branch to test what I implemented. Let me know if it worked for you
