### ISSUE TITLE
Add sub items for custom control

### ISSUE THREAD

**Issue by gabrieletassoni** [openplayerjs/openplayerjs#206]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a multi language control for Live streaming, having rtmp inputs for different languages, I'd like to have a control menu with links to different languages set as sources for the video element, in order to be able to switch from languages at will.

**Describe the solution you'd like**
Clicking on a custom control on the right position as per [Add Control](https://github.com/openplayerjs/openplayerjs/blob/HEAD/docs/customize.md#add-control) wiki page, I would like to have a documented way to open a submenu (mimicking the Settings one, for example, which opens a submenu of speeds) which I may have populated with objects like:

```
{
  id: "submenu-1",
  title: "Italian",
  click: () => {} // here the code to set the src of the player to the new URL or whatever action needed
}
```

So, using the AddControl example, a complete one could be:

```
player.addControl({
    icon: 'Languages',
    id: 'languages-selector',
    title: 'Languages',
    // Possible values: 'bottom-left', 'bottom-middle', 'bottom-right',
    // 'left', 'middle', 'right', 'top-left', 'top-middle', 'top-right',
    // or `main` to add it in the video area
    position: 'right',
    showInAds: false, // or true
    subitems: [
       {
         id: "submenu-1",
         title: "Italian",
         click: () => {console.log("Submenu item with id element clicked" + this.id)} // here the code to set the src of the player to the new URL or whatever action needed
       },
       {
         id: "submenu-2",
         title: "English",
         click: () => {console.log("Submenu item with id element clicked" + this.id)} // here the code to set the src of the player to the new URL or whatever action needed
       },

    ]
    click: () => {console.log("Main element clicked")}, // the operation it executes maybe, if there are subitems, this can be skipped
  });
```

**Describe alternatives you've considered**
I tried to understand if I could create submenus using hidden controls in the upper-right position, but I'd prefere to stick to an official solution if exists.

**Comment by rafa8626** [comment]
@gabrieletassoni hi, currently the subtitles menu appears of you set up the detachMenu option in the player; however, if you need to have a different experience and you want to use the addControl method, I’ll need to enhance that to support subitems and its operations. If the first option doesn’t work for you, let me know and I’ll schedule the work for the second option then. Thanks for suggesting this

**Comment by gabrieletassoni** [comment]
> @gabrieletassoni hi, currently the subtitles menu appears of you set up the detachMenu option in the player; however, if you need to have a different experience and you want to use the addControl method, I’ll need to enhance that to support subitems and its operations. If the first option doesn’t work for you, let me know and I’ll schedule the work for the second option then. Thanks for suggesting this

@rafa8626 thanks for consideration, to me it remains important because is to implement a functionality that's actually non existent: mimicking different audio languages, maybe I wasn't clear in the description of the feature, but it's scope is not the subtitles (for which I probably can just use the already present functionality), in my case is to fake the presence of different languages. I try to explain better the functional bit: usually rtmp to hls transcoders (like nginx rtmp plugin or mux.com service) just support rtmp input with one audio and one video, no multi audio support, the hls output is therefore one audio and one video. During live events there are usually, to comply with this limitation, one rtmp audio/video stream for each language (say one with italian audio, another with english audio translation and so on), and such thing goes towards having one hls or mpegdash for each audio language (always audio/video), in my case, mimicking the existence of different audio languages is made by having a control with the submenu which shows labels for each language and holds hidden somewhere the actual hls m3u8 url of the relevant audio/video stream, when a language is clicked (say I click English, having in the submenu of the custom control also Italian and French), the src of the video player is replaced by the relevant hls m3u8 url. I can do this outside the video player, with a select, but it's more beautiful and feels better integrated to have it inside the video player ui, hence the idea to have it as a custom control with submenus.

Having custom controls which can also have submenus, is anyway a general useful enhancement, not just for my case, i think.

I'm also willing to help implementing, unfortunately I don't know typescript, but if aimed in the right direction, where to add objects, where to hook code and your general view on how to implement this, I can try to do the groundwork for the functionality, maybe I will just be a bit slow and write awkward code, since I'm not a pro at typescript at all, but still... :-)

**Comment by rafa8626** [comment]
@gabrieletassoni thanks for the detailed explanation; I think I can make the adjustments in the next few days. The only thing I'd ask is for a couple of samples I can use to explore what you are looking for. That way I can spend the time dealing with the enhancements rather than researching for samples.

**Comment by rafa8626** [comment]
@gabrieletassoni Ignore my comment above; please download the master branch and test my approach using the following sample:
```javascript
player.addControl({
            icon: 'Languages',
            id: 'languages-selector',
            title: 'Languages',
            position: 'right',
            showInAds: false, // or true
            subitems: [
            {
                id: "submenu-1",
                label: "Italian",
                title: 'Click here to see a log for Italian',
                icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/200px-Flag_of_Italy.svg.png',
                click: () => {
                     console.log("Ciao, com'e va?")}
            },
            {
                id: "submenu-2",
                label: "English",
                click: (e) => {
                    console.log("Submenu item with id element clicked ", e.target.id)
                }
            },
            ],
        });
```
Let me know if it needs something else, and thanks again for your suggestion

**Comment by gabrieletassoni** [comment]
Wow! Thank you very much! I was in the process of producing test videos, but it's plain great this super fast feedback! I start to test it in few minutes and let you know, thank you very much again!

**Comment by gabrieletassoni** [comment]
Wow! That's beautiful! It works really good to me. Thank you very much! also the plus of having icons in submenu items is really handsome! ^_^

**Comment by rafa8626** [comment]
@gabrieletassoni you are welcome! I’m glad this worked for you. Please invite others to star the project so the project gains more popularity. This will be released in the next few days :)
