### ISSUE TITLE
Remove custom control after init

### ISSUE THREAD

**Issue by gabrieletassoni** [openplayerjs/openplayerjs#207]
**Is your feature request related to a problem? Please describe.**
By using player.addControl(..) I can add a custom control on the player interface also after init(), I would like to remove custom controls at will, I tried by splicing the object representation like so `player.controls.items.right.splice(0, 1);`, but it has no effect, the Custom control stays in place.

Maybe I'm missing something from documentation, but I don't find a removeControl() function which can remove a custom control added at runtime.

Thank you very much, bye,
Gabriele

**Comment by rafa8626** [comment]
@gabrieletassoni yes that doesn’t exist yet. But I can work on it during these next days. I’ll keep you posted about it

**Comment by gabrieletassoni** [comment]
Really really super! Thank you again.

**Comment by rafa8626** [comment]
@gabrieletassoni please download the master branch and let me know if it works for you; you just need to use 
```javascript
player.removeControl('play') // or the name you use for your custom control
```

**Comment by gabrieletassoni** [comment]
@rafa8626 Hi, thanks for the effort, it works ok on predefined controls like play (as per your suggestion for testing), but not for custom controls, I used it for a custom control I created using the custom crontrols `player.removeControl('languages-selector')`, languages-selector is the id of the customControl.

**Comment by rafa8626** [comment]
@gabrieletassoni can you provide me a CodePen where I can check your issue please?

**Comment by rafa8626** [comment]
@gabrieletassoni nevermind, I see the issue already. I'll fix it shortly

**Comment by rafa8626** [comment]
@gabrieletassoni please download the master branch again and let me know if it works now for you

**Comment by gabrieletassoni** [comment]
@rafa8626 Tested and it works like a charm! Thank you very much!
