### ISSUE TITLE
Set video duration manually

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#208]
some time for delay in receive video player show 00:00 for video duration. if I can set this duration manually (in configuration) it can be better experience for user . until video load

![image](https://user-images.githubusercontent.com/13816403/107843322-756acc00-6ddf-11eb-99c2-99f066f07afa.png)

**Comment by rafa8626** [comment]
@foadabdollahi many video players actually won’t show any duration at all until is detected; would that work for you?

**Comment by foadabdollahi** [comment]
yes i want set duration until  detected (before detect) for show better user experience. it can be an optional configuration

**Comment by rafa8626** [comment]
@foadabdollahi please download the master and let me know if it works; the way to use it is like this:
```javascript
const player = new OpenPlayer('player1', {
                progress: {
                    duration: 80  // in seconds
                }
 });
player.init();
```

**Comment by foadabdollahi** [comment]
Thanks. it work as i need
