### ISSUE TITLE
Guidance on extending OpenPlayerJS with spritesheet thumbnail previews 

### ISSUE THREAD

**Issue by samsends** [openplayerjs/openplayerjs#210]
**Is your feature request related to a problem? Please describe.**

It would be nice to display thumbnail previews depending on the position of the seek bar. For the end user this function helps with seeking especially given that continuous watch times are going down in favor of shorter skipping behavior to seek to the interesting areas of a video. 

To my knowledge, this is not possible with OpenPlayerJS to display thumbnail previews. Given that it may be out of scope of the project, what is the best way to extend off OP to add this functionality for the community?

**Describe the solution you'd like**

Open a discourse regarding how to best implement this (either plugin or adding to OpenPlayer code base, etc)

**Comment by rafa8626** [comment]
@samsends thanks for choosing OP as part of your project. IMO, this feature may be best suited by using a custom control, to which you can find documentation [here](https://github.com/openplayerjs/openplayerjs/blob/master/docs/customize.md#add-control). This feature looks like an secondary progress bar, so it should be easy to create; however, the only thing I don't have integrated yet for custom controls, is the ability to add custom events to them, and I know that the preview will require a `mouseenter`, and currently I only support `click`. I'll be thinking about how to support more events in custom controls, but in the meantime, check how to create a custom control, and if you have more questions, please let me know.
Also, can you give a star to the project to show your support to it, please?

**Comment by rafa8626** [comment]
@samsends sorry for the delay (I've been really busy lately); please download the master branch and let me know if it works for you; I have added 5 new common events that are supported with custom controls to enhance the experience with them

**Comment by samsends** [comment]
Hey @rafa8626, thank you for adding the additional events. Does this also include touch events? I have noticed some weird behavior when seeking video position on mobile devices. Another question I have is whether it is possible to send the video into full screen mode on mobile, but not desktop?

My work email is sam@glass.xyz. If you don't mind shooting me an email I would like to discuss potentially sponsoring the OP project. I also went ahead and  gave you a star :)

**Comment by rafa8626** [comment]
@samsends thanks for the star :) no I didn’t add a touch event but I can add it quickly today; as per the full screen effect, only Android can do that but not iOS since that’s more restrictive. I haven’t checked if it’s currently possible but I’ll check. I’ll shoot you an email to discuss sponsorship

**Comment by rafa8626** [comment]
@samsends I checked about the touch events, but they seem to agree that having click is the same as touchstart, also because mobile devices dispatch click after the touch events. See https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent#event_order
