### ISSUE TITLE
ambiguity for JS example

### ISSUE THREAD

**Issue by JustinWebDev** [openplayerjs/openplayerjs#216]
**Describe the bug**
Some of the configuration information is not clear.

**To Reproduce**
1. Go to https://github.com/openplayerjs/openplayerjs/blob/master/docs/usage.md#javascript
2.  look at config info:
```
controls: {
        // By default, the player will display the controls for a number of seconds before they are hidden; this option will allow the user to permanently show the controls if they need fully customize them.
        alwaysVisible: false,
        // Controls configuration by default; `levels` can be added as well since it's an optional feature;
        // Each one of the items will have in their class name the `op-control__[left|middle|right]` according
        // to the controls' structure listed below. Also available: `top-left`, `top-middle`,
        // `top-right`, `bottom-left`, `bottom-middle` and `bottom-right`.
        // If you use `main`, it will be appended to the media's container to create elements.
        layers: {
            left: ['play', 'time', 'volume'],
            middle: ['progress'],
            right: ['captions', 'settings', 'fullscreen'],
        }
    },
```
What is "`levels`?  It is not mentioned elsewhere?  Is it supposed to be 'layers'?
What is "`main`"?  How is it used (syntax)?  It is not explained anywhere.

Also, it would be good to single-quote the _left_, _middle_, _right_ layer positions so that it is very clear that the layer positions have to be quoted -- the comment text for the other positions is back-ticked and the reader doesn't know if you are semantically saying 'this label' or if it actually needs to be quoted.

**Expected behavior**
clear documentation

**Comment by rafa8626** [comment]
@JustinWebDev thanks for noticing this; I made some changes in the docs based on your suggestions. Let me know if it's clear now

**Comment by JustinWebDev** [comment]
This is better.  It would be good to clarify that _detachMenus_ is a Boolean and defaulted to false.
I couldn't get _progress - duration_ to do anything, so might need to be more verbose on what it does or what to expect.
Thanks.

**Comment by rafa8626** [comment]
@JustinWebDev thanks for the last feedback; I have added it and should be more descriptive now in terms of what these items are supposed to do

**Comment by JustinWebDev** [comment]
for _detachMenus_:  "geerally speaking"  oops!

Thanks for the updates.

**Comment by rafa8626** [comment]
@JustinWebDev nice catch! I'll correct it. Thanks
