### ISSUE TITLE
low or mute volume speaker image changes height of player

### ISSUE THREAD

**Issue by JustinWebDev** [openplayerjs/openplayerjs#217]
**Describe the bug**
When the volume icon changes due to lower volume level or mute, the position of the controls moves vertically.  The control element should not move because of volume level change.

**To Reproduce**
1. Go to https://codepen.io/rafa8626/pen/WaNxNB
2. Click on the audio player speaker to mute it or change the volume level <50% to force the speaker icon to change - observe the control position changes vertically

**Expected behavior**
The control elements vertical position should not change.

EDIT:  I first thought the height of the player was changing, but upon closer inspection it looks like it is just the controls are moving up and down within the player box.

**Comment by rafa8626** [comment]
@JustinWebDev thanks for reporting this; I’ll take a look and I’ll keep you posted. Please star the project to show your support

**Comment by rafa8626** [comment]
@JustinWebDev this has been fixed in the master branch; it was related to the size of the mute button compared to other states.

**Comment by JustinWebDev** [comment]
Thanks much!
