### ISSUE TITLE
controls-layers configuration parameters are not honored

### ISSUE THREAD

**Issue by JustinWebDev** [openplayerjs/openplayerjs#219]
**Describe the bug**
Setting the controls - layers config params does not correctly alter the player.

**To Reproduce**
1. for a simple audio player, configure a vertical stack of controls, something like:
HTML
`<audio id="player" class="op-player__media">
...`

JS
`const player = new OpenPlayerJS('player', {
          controls: {
                  layers: {
                      'top-left': ['play'],
                      'left': ['time'],
                      'bottom-left': ['progress'],
                  }
              },
    });`

2. view the web page - observe the controls are not stacked, but instead mangled left to right
![image](https://user-images.githubusercontent.com/40804543/110880195-d92fca00-82a3-11eb-8cf3-b35c68d0384f.png)

Even if you set a height, the controls do not position correctly:
![image](https://user-images.githubusercontent.com/40804543/110880280-01b7c400-82a4-11eb-9885-42205e2341a3.png)

**Expected behavior**
The controls placement should honor the controls-layers config params.

**Comment by rafa8626** [comment]
@JustinWebDev this should be fixed; please download the master branch and confirm it. If it's not fixed, let me know so I can reopen this issue. Thanks for reporting this

**Comment by JustinWebDev** [comment]
@rafa8626 I'm not seeing any difference.

**Comment by rafa8626** [comment]
@JustinWebDev I just checked again in the master branch and worked as expected. I used 
```javascript
const player = new OpenPlayerJS('player1', { controls: { layers: { 'top-left': ['play'], 'top-right': ['fullscreen'], 'left': ['time'], 'bottom-left': ['progress'], } }, });
player.init();
```
to achieve this result:
<img width="725" alt="Screen Shot 2021-03-13 at 6 58 05 PM" src="https://user-images.githubusercontent.com/910829/111053007-3b1c3b00-842e-11eb-8726-3284d2a512aa.png">

**Comment by JustinWebDev** [comment]
@rafa8626 With audio, it doesn't look any different.  So, I tried video (it looks like that is what you tested with):
`<html>
    <head>
        <link rel="stylesheet" href="openplayer.css">
    </head>
    <body>
        <video class="op-player__media" id="player" controls playsinline>
            <source src="/path/to/video.mp4" type="video/mp4">
        </video>
        <script src="openplayer.min.js"></script>
        <script>
           const player = new OpenPlayerJS('player', { controls: { layers: { 'top-left': ['play'], 'top-right': ['fullscreen'], 'left': ['time'], 'bottom-left': ['progress'], } }, });
            player.init();
        </script>
    </body>
</html>`

I tried local files and the CDN but got the same result.  (tested in major browsers)

(Why does GitHub's editor have to suck?)

![image](https://user-images.githubusercontent.com/40804543/111081763-e4b50800-84d2-11eb-91ca-439537af780f.png)

**Comment by rafa8626** [comment]
@JustinWebDev let me take a look at it; I'm currently finishing some adjustments for a bunch of your tickets. Then I can take a look at this so we have this sorted out :)
