### ISSUE TITLE
API property to get currently playing source

### ISSUE THREAD

**Issue by JustinWebDev** [openplayerjs/openplayerjs#220]
**Is your feature request related to a problem? Please describe.**
I need a way to get the currently playing source.  My audio tag has two sources.  I can't find a way to discover which source is playing or active (set to play).

**Additional context**
There is the getMedia object, the src property, and the media.src property (which is not documented), but they just give a list of sources.

**Comment by rafa8626** [comment]
@JustinWebDev now you can use `getMedia().current` to know which one is the right media. Let me know if that works for you

**Comment by JustinWebDev** [comment]
@rafa8626 This does let me see what is actually playing. Can it be extended to show what is _set to be played_ (i.e., 'queued')?  When an audio tag is rendered, there is a source that is marked to be played; I'd like to get that also.  If you look at plain HTML5, there is a _currentSrc_ property on the audio tag object that is like what I need.  I'd think it would also show currently playing source, but I can't confirm that.

**Comment by rafa8626** [comment]
@JustinWebDev that’s odd because when I tested this I could retrieve the current media as an object retrieving the source and type of media. Let me check that just in case

**Comment by JustinWebDev** [comment]
In case it matters in your testing, I use two source tags in the audio tag.

**Comment by rafa8626** [comment]
@JustinWebDev I tested this using 
```html
<audio class="op-player__media" id="audio" controls playsinline>
                        <source src="https://stream.berean-biblechurch.org/live.ogg" type="audio/ogg">
                        <source src="https://stream.berean-biblechurch.org/live.mp3"  type="audio/mp3">
                    </audio>
```
and then the JS:
```javascript
const player = new OpenPlayerJS('audio');
player.init();
console.log(player.getMedia().current);
```
and I see in the console the object including the OGG source and type: "audio/ogg"

**Comment by JustinWebDev** [comment]
@rafa8626 Ah, thanks for the code.  Now I see the difference.  I use `preload="none"` in the audio tag.  That's the difference.

**Comment by rafa8626** [comment]
@JustinWebDev gotcha; glad it worked!

**Comment by JustinWebDev** [comment]
@rafa8626  Well, it didn't work.  I just found the difference between your test and my test.  With preload off, the queued track is not seen.

**Comment by rafa8626** [comment]
@JustinWebDev if preload is none there’s nothing ready to be played, hence the only viable source there is to get the first source in the list; would that work for you?

**Comment by JustinWebDev** [comment]
@rafa8626 I think that would be okay. That may be what HTML _currentSrc_ property on the audio tag does.

**Comment by rafa8626** [comment]
@JustinWebDev check the master branch; this should be possible now even with the `preload=none` attribute

**Comment by JustinWebDev** [comment]
@rafa8626 Awesome - thanks!
