### ISSUE TITLE
no source found behavior

### ISSUE THREAD

**Issue by JustinWebDev** [openplayerjs/openplayerjs#222]
**Is your feature request related to a problem? Please describe.**
I have a live stream that is on only at certain times.  When the stream is not on, and I play the player, there is no indication that it is looking for the stream, and there is no indication that it didn't find it and timed out.  The player persists with the pause button, and the console says "All candidate resources failed to load. Media load paused."  

**Describe the solution you'd like**
1) indication that the player is searching for the stream.
2) indication that the player could find a stream, or even just a reset to play.
3) Would it make sense if user toggles from pause to play that the player resets the media search?  Right now nothing happens except the button toggles states.

**Describe alternatives you've considered**
_playererror_ event does not report the 'not found' condition.
_stalled_ event does trigger, so I could use that to at least know that the stream failed.

**Comment by rafa8626** [comment]
@JustinWebDev can you provide me with a sample of your streaming to use it to develop this feature please?

**Comment by JustinWebDev** [comment]
@rafa8626 I'm not exactly sure of what you are asking, but the live audio stream page is [here](https://berean-biblechurch.org/live-stream/).  Audio stream links are there also.  So, if you try to load the stream any other time than stated to be on, you'll get nothing because the streaming server won't even be on.

**Comment by rafa8626** [comment]
@JustinWebDev so can I use the Live Broadcast streaming URL in the link you indicated to check the behaviors you are wanting to achieve?

**Comment by JustinWebDev** [comment]
@rafa8626 yes, either one, the OGG or MP3.

**Comment by rafa8626** [comment]
@JustinWebDev please download the master branch and test this; I used the mp3 and ogg for this, and once you try to load the media, the progress bar will display an animation to indicate that is trying to download the source. After 30 secs, the animation will stop. You can use the `playererror` to perform other operations. I'd leave you the reset feature since that is more related to your scenario than something the player needs, but I'm pretty sure you have now everything you need. Let me know if it works, and thanks for suggesting this :)

**Comment by JustinWebDev** [comment]
@rafa8626 Wowza - that's great!  That makes me think of enhanced config parameters  :-)

I used `playererror`.  Is error.detail.message "Media download failed part-way due to a network error" returned from the browser is that your code (string)?
Is there a way to capture the playererror object in a variable so I can access it programmatically?

BTW, the link for "Usage with Java**s**cript" on https://github.com/openplayerjs/openplayerjs/blob/master/docs/api.md doesn't go anywhere.

**Comment by rafa8626** [comment]
@JustinWebDev yes that’s my code. I tried to catch it using what W3C suggests but it wasn’t consistent; there’s no way to catch the error other than using the event and store the result in a variable. I’ll check the link issue, thanks for noticing it :)
