### ISSUE TITLE
show current time only

### ISSUE THREAD

**Issue by JustinWebDev** [openplayerjs/openplayerjs#223]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to show current play time only.  I don't need the total time of the media.

**Describe the solution you'd like**
Configuration option to show only current play time.

**Comment by rafa8626** [comment]
@JustinWebDev Please check the master branch; the new option should be placed under the `progress` option: `showCurrentTimeOnly`

**Comment by JustinWebDev** [comment]
@rafa8626 Awesome -- thanks!
