### ISSUE TITLE
mute button and volume slider don't stay connected if in right position

### ISSUE THREAD

**Issue by JustinWebDev** [openplayerjs/openplayerjs#224]
**Describe the bug**
Tell us what your bug is about.

**To Reproduce**
1. add this to your player config, where width is not set:
`controls: {
                  layers: {
                    left: ['play'], middle: ['time'], right: ['volume']
                  }
              },`
2. observe that the mute button is right next to the time but the short volume slider is next to the right end, so there is a large gap between the button and slider.

**Expected behavior**
Mute button and volume slider should always hang together.

**Screenshots**
![image](https://user-images.githubusercontent.com/40804543/111054273-fc3bb480-8430-11eb-9814-505a14fa2cb2.png)

**Comment by rafa8626** [comment]
@JustinWebDev This should be fixed; please check the master branch

**Comment by JustinWebDev** [comment]
Confirmed!
