### ISSUE TITLE
'Uncaught TypeError' with progress - showCurrentTimeOnly configured

### ISSUE THREAD

**Issue by JustinWebDev** [openplayerjs/openplayerjs#225]
**Describe the bug**
If 
_progress:{
          showCurrentTimeOnly: true,
          }_
is in the configuration for an audio player, Chrome console reports:
```
Uncaught TypeError: Failed to set the 'value' property on 'HTMLProgressElement': The provided double value is non-finite.
    at HTMLAudioElement.m.media.timeupdate
```
and the progress bar goes away.

Firefox does not show an error, and the progress bar continues to show.

**To Reproduce**
1. configure an audio player as described above
2. play the audio - see error in the console

**Expected behavior**
no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/40804543/111549188-c4db4980-8749-11eb-8dc1-089a19453770.png)

**Comment by rafa8626** [comment]
@JustinWebDev thanks I’ll check this soon, it’s been crazy this week

**Comment by rafa8626** [comment]
@JustinWebDev  this should be fixed now; please download the master branch and let me know if it works

**Comment by JustinWebDev** [comment]
@rafa8626 No errors!  Looks good.
