### ISSUE TITLE
Multiple Ads sets up playererror

### ISSUE THREAD

**Issue by Rubioli** [openplayerjs/openplayerjs#226]
In my player, I'm using multiple ads and also have set up a `addEventListener` on `playererror`. On both when skipping the first ads and also when the first ad is finished, it will fire up `playererror`, which shouldn't be fired in the first place.

This is my set up:
```
<script>
const player = new OpenPlayerJS('video-player', {
  hls: {
    startLevel: -1,
    enableWorker: true,
    emeEnabled: true,
  },
  ads: {
    src: [
          "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=",
          "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dredirectlinear&correlator="
        ]
  }
});
player.init();

player.getElement().addEventListener('playererror', e => {
  console.log(e);
  if (e.detail.type === 'Ads') {    
    console.log('No Ad');
  }
});
</script>
```

Also if the first ad or second doesn't have any ad/feed, the error would run also every second and gives the `console.log('No Ad');`

```
src: [
  "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dredirectlinear&correlator=",
  "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dredirecterror&nofb=1&correlator=",
]
```

With the sources above, the first ad will run fine and the second one will fail and you'll see the player error every second and makes it so that my live stream doesn't play as the player gets stuck in one "situation" and to be 100% clear, I want the `playererror`, only on the second ad and not the first one. Not sure if it makes sense or possible. In this case, the `playererror` function will be fired at the end.

*PS: here you can find a lot of links: https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags*

I'm not sure if I'm doing something wrong. Any feedback is appreciated and thanks in advanced

**Comment by rafa8626** [comment]
@Rubioli thanks for reporting this; please download the master branch and let me know if it works now for you. Once it tries to process both, it stops the `playererror` since there's nothing else to do.

**Comment by Rubioli** [comment]
Thanks for your reply @rafa8626 

I tested with the master and this is the result :)

```
src: [
  // Single Skippable Inline
  "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=",
  
  // Single Inline Linear
  "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=",
]
```

What I saw was that the second ad never gets played now and when I do skip as well, it doesn't play. In regards to the errors, it still fires up 2 `playererror` and I tested this with all different type of VAST, but still the same :/

I tested with 2 Single Inline Linear and still the same. First ad plays, throws the `playererror` exactly twice and the last/2nd ad doesn't get played.
```
src: [ 
  "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=",
  "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator="
]
```

I hope I managed to explain well :)

**Comment by rafa8626** [comment]
@Rubioli perfectly explained; I’ll check why it is still triggering 2 errors instead of one

**Comment by Rubioli** [comment]
@rafa8626 besides the errors, only one of the ads gets to play. I only tested with 2 ads and only the first one played

**Comment by rafa8626** [comment]
@Rubioli I need to check that because sometimes these sample tags return empty from the server; I’ve seen that before even playing just one. I don’t know why but the source is an empty XML tag

**Comment by rafa8626** [comment]
@Rubioli please download the master branch and check this; the number of errors should be the right one now; and yes, this happens because the server that serves the ads returns the XML as empty, so if none of the Ads play it is because of it

**Comment by Rubioli** [comment]
Thanks @rafa8626 I'll run a test today. 

PS: Sorry for late reply, I've been visiting family
