### ISSUE TITLE
Is there a way to have two players playing at the same time in the page? (seamless transition between two videos)

### ISSUE THREAD

**Issue by gabrieletassoni** [openplayerjs/openplayerjs#230]
I'm trying to create a seamless transition between two videos, to fake a multi language audio swap.

I have two m3u8 playlists, the normal behaviour is, with one player in the page, to set the src to the new m3u8 playlist when I need it, for example:

```javascript
var currTime = player.getMedia().currentTime
player.src = {src: "lang1.m3u8", type: "application/x-mpegURL"};
player.getMedia().currentTime = currTime
player.play()
```

So the new source starts at the same time of where the previous source was, but the problem here is that I see a loading animation and the player pauses while doing the seeking to the currentTime. This is not so seamless.

I tried to fake the right behaviour I need: seamless transition from one source to the other, without seeing loaders or pauses in the playback by instantiating two different players in the page, one absolutely positioned with z-index: -1 (call it background player), the other visible above the absolutely positioned one, with z-index: 1 (call it foreground player). Upon clicking on the new source, I attach an eventlistener to the background player for seeked event, i send the new source to the background player, set the currentTime on the backgroundplayer to the foreground one and then play() on the background player and when seeked is fired, it swaps the z-index of the two players (and the position: absolute/relative). This play() makes the seeked event alctually  fire after some time (the download time of the movie to go to the currentTime), but it has the drawback to put in pause the foreground player, so, I don't have the loading spinner thing and a little pause, but I have a long pause on the foreground player and then the swap, when the seeked is fired of the background and foreground players. If there would be a way to have the background player play without pausing the foreground player, the seamless perception would be perfect.

Here the onclick function which sends the source to the player with foreground class and makes the preload to the background player:

```javascript
function onClickManagePlayers() {
          console.log("click: " + pId + " " + lang["name"])
          if(player.getElement().parentElement.parentElement.parentElement.classList.contains("foreground")) {
            console.log("Sending to otherplayer for preload")
            otherplayer.getElement().addEventListener('seeked', swapVideoElements);
            otherplayer.src = {src: lang["playback_url"], type: "application/x-mpegURL"}
            otherplayer.getMedia().currentTime = player.getMedia().currentTime
            otherplayer.play()
          } else {
            console.log("Sending to mainplayer for preload")
            player.getElement().addEventListener('seeked', swapVideoElements);
            player.src = {src: lang["playback_url"], type: "application/x-mpegURL"}
            player.getMedia().currentTime = otherplayer.getMedia().currentTime
            player.play()
          }
}
```

Here the swapVideoElements which responds to the seeked event on the background player:

```javascript
  function swapVideoElements(e) {
    // console.log(e)
    e.target.removeEventListener('seeked', swapVideoElements)
    console.log("Seeked! Finished!")
    var fg = document.querySelector(".foreground").classList
    var bg = document.querySelector(".background").classList
    fg.remove("foreground")
    fg.add("background")
    bg.remove("background")
    bg.add("foreground")
  }
```

The foreground/background elements are styled like this:

```css
  .foreground {
    position: relative;
    z-index: 1;
  }

  .background {
    position: absolute;
    z-index: -1
  }
```

Thank you very much for the help, or an explanation or also an idea on another direction.

**Comment by rafa8626** [comment]
@gabrieletassoni if you can create a CodePen with what you are trying to achieve I’ll have a better idea about how to answer you; I don’t think it’s difficult but I wanna explore some options before I give you a final answer

**Comment by gabrieletassoni** [comment]
Here it is:

https://codepen.io/gabrieletassoni/pen/zYNMJMr

I had to extract the general functionality from the dynamically generated page, but it's quite accurate on the problem, the only thing is that codepen has fast connection and the demo files are quite short, so it's less evident than uusing my adsl, but you can anyway see that the foreground video player, as soon as the background one is played  needed to trigger the seek to the current time of the foreground player, it pauses, the seeked is fired, and the background player becomes foreground, playing the new movie. What I would like to achieve is that the foreground player keeps playing until the background one have finished seeking, so the swap between foreground and background doesn't look like a pause and play, but a continous play.

And, yes, I know these are not truly the same movie with different languages, but are the test videos I have access now.

Thanks again for the help

**Comment by rafa8626** [comment]
@gabrieletassoni thanks I’ll check it out and give you my feedback as soon as I can

**Comment by rafa8626** [comment]
@gabrieletassoni after I checked your CodePen, I realized that something was missing in the player itself that I should have put a long time ago. Please download the master branch to verify if the following code sample fits your needs. I did it trying to be as smooth as possible; I couldn't detect a pause event on it, but maybe your scenario is different:
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>OpenPlayer Tests</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" media="all" href="../dist/openplayer.css">
        <style>
            body {
                max-width: 700px;
            }
            .hidden {
                display: none !important;
            }
            .video {
                width: 100%;
                background-color: black;
            }
            .videowrapper {
                width: 640px;
                height: 360px;
            }
        </style>
    </head>
    <body>
        <div id="container">
            <section>
                <h1>OpenPlayer.js</h1>
                <div class="players">
                    <div class="videowrapper">
                        <video id="player" class="main op-player__media" playsinline preload="metadata">
                            <source src="https://stream.mux.com/m1eSRRWzK3YdghY1K01q2WyAnkhTv01rQ4DVikz2g7uJU.m3u8?redundant_streams=true" type="application/x-mpegURL">
                          </video>
                    </div>
                    
                </div>
            </section>
        </div>
        <script src="../dist/openplayer.js"></script>
        <script>
            const player = new OpenPlayerJS('player', {
                mode: "fit",
                showLoaderOnInit: false, // you need this to avoid seeing the loader
                hls: {
                    limitRenditionByPlayerDimensions: false,
                    smoothQualityChange: true,
                    overrideNative: true
                }
            });

            player.addControl({
                icon:'https://img.icons8.com/cotton/64/000000/blood-sample.png',
                id: 'rewind',
                title: 'Rewind',
                position: 'right',
                click: () => {
                    player.getContainer().querySelector('.op-player__loader').classList.add('hidden');
                    const time = player.getMedia().currentTime;
                    player.src = {src: "https://upload.wikimedia.org/wikipedia/commons/2/22/Volcano_Lava_Sample.webm", type: "video/webm"}
                    // New addition: load() returns a Promise to execute the play in the proper time
                    player.load().then(() => {
                        player.getMedia().currentTime = time;
                        if (!player.paused) {
                            player.play();
                        }
                    });
                }
            });

            player.init();
        </script>
    </body>
</html>

```

**Comment by gabrieletassoni** [comment]
On this sample, it looks ok, thank you, I try it on the real thing and let you know (so, there's no need for two players this way, good)

**Comment by gabrieletassoni** [comment]
Mybe the webm is better than the m3u8, but in this project I'm stuck with m3u8

**Comment by rafa8626** [comment]
I’ll check it with m3u8. Do you have another source I can use to mimic the behavior more properly? In your CodePen you used the same one so I’d like to try having 2 different ones

**Comment by gabrieletassoni** [comment]
Here they are, longer so you can also check if the behavior differs after minutes:

- https://stream.mux.com/XHp500iPqujBykFKCYrJwCdkL00PItGj93L4BUamK22Zg.m3u8?redundant_streams=true
- https://stream.mux.com/lzqPULGkpx8o01H97C6fqlSDbHy9GQr3rQpESqyCGErw.m3u8?redundant_streams=true

Many thanks again

**Comment by rafa8626** [comment]
@gabrieletassoni OK I think I made it work the way you expect now. Unfortunately, there's no seamless way to do it with 1 player based on what I read, so you do need 2 players. Please download again the master branch and use the following snippet. I tested multiple times and it work always consistently

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>OpenPlayer Tests</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" media="all" href="../dist/openplayer.css">
        <style>
            body {
                max-width: 700px;
            }
            .hidden {
                display: none !important;
            }
            .video {
                background-color: black;
                width: 100%;
            }
            .video-wrapper {
                height: 360px;
                width: 640px;
            }
        </style>
    </head>
    <body>
        <div id="container">
            <section>
                <h1>OpenPlayer.js</h1>
                <div class="players">
                    <div class="video-wrapper">
                        <video id="player" class="main op-player__media" playsinline preload="metadata" poster="https://www.w3schools.com/images/w3schools_green.jpg">
                            <source src="https://stream.mux.com/XHp500iPqujBykFKCYrJwCdkL00PItGj93L4BUamK22Zg.m3u8?redundant_streams=true" type="application/x-mpegURL">
                          </video>
                    </div>
                    <div class="video-wrapper hidden">
                        <video id="player2" class="main op-player__media" playsinline preload="metadata" poster="https://www.w3schools.com/images/w3schools_green.jpg">
                            <source src="https://stream.mux.com/lzqPULGkpx8o01H97C6fqlSDbHy9GQr3rQpESqyCGErw.m3u8?redundant_streams=true" type="application/x-mpegURL">
                          </video>
                    </div>
                </div>
            </section>
        </div>
        <script src="../dist/openplayer.js"></script>
        <script>
            const player = new OpenPlayerJS('player', {
                mode: "fit",
                showLoaderOnInit: false,
                pauseOthers: false,
                hls: {
                    limitRenditionByPlayerDimensions: false,
                    smoothQualityChange: true,
                    overrideNative: true
                }
            });
            const player2 = new OpenPlayerJS('player2', {
                mode: "fit",
                showLoaderOnInit: false,
                pauseOthers: false,
                hls: {
                    limitRenditionByPlayerDimensions: false,
                    smoothQualityChange: true,
                    overrideNative: true
                }
            });

            player.addControl({
                icon:'https://img.icons8.com/cotton/64/000000/blood-sample.png',
                id: 'rewind',
                title: 'Rewind',
                position: 'right',
                click: () => {
                    player2.load();
                    player2.getElement().addEventListener('hlsManifestLoaded', () => {
                        const time = player.getElement().currentTime;
                        player2.getElement().currentTime = time;
                        player2.play();
                    });
                    player2.getElement().addEventListener('playing', () => {
                        player2.getContainer().closest('.video-wrapper').classList.remove('hidden');
                        player.getContainer().closest('.video-wrapper').classList.add('hidden');
                        player.pause();
                    });
                }
            });
            player2.addControl({
                icon:'https://img.icons8.com/cotton/64/000000/blood-sample.png',
                id: 'rewind',
                title: 'Rewind',
                position: 'right',
                click: () => {
                    
                }
            });

            player.init();
            player2.init();
        </script>
    </body>
</html>
```

**Comment by gabrieletassoni** [comment]
Yes, thanks, the sample works really as needed. Now I port it into the application.

**Comment by gabrieletassoni** [comment]
Ok, it works also in the real thing. Thank you very much for the changes and hints.

**Comment by rafa8626** [comment]
@gabrieletassoni glad it worked for you :)

**Comment by gabrieletassoni** [comment]
Meanwhile, I'm trying to spread the word on how good is this project, some more stars are coming from friends! ^_^

**Comment by rafa8626** [comment]
Thanks, I truly appreciate it! :)
