### ISSUE TITLE
React rich example

### ISSUE THREAD

**Issue by mkaiphant** [openplayerjs/openplayerjs#233]
Hey mate thanks for the awesome plugin.
Would you mind to create and share an example of player in react js with external controls to control the playback like play/pause, mute, seek etc. 
Thanks in advance

**Comment by rafa8626** [comment]
@mkaiphant thanks for using OpenPlayerJS! Sure I’ll work on one and share it with you. Please the project a star to show your support

**Comment by manojvarmaboppisetti** [comment]
Hey any update on my issue @rafa8626

**Comment by mkaiphant** [comment]
hey @rafa8626 . any update on my issue?

**Comment by rafa8626** [comment]
@mkaiphant I’ll try to work on it tonight. I have some work that is delaying this but I’ll see if I can get to it later tonight. I’ll keep you posted

**Comment by rafa8626** [comment]
@mkaiphant I created this CodePen; it's not a lot but it will give you the right idea about how to use OpenPlayerJS with React: https://codepen.io/rafa8626/pen/GRrVLMB. Hope it's helpful

**Comment by mkaiphant** [comment]
@rafa8626 it gives me decent idea. thanks for your prompt response
