### ISSUE TITLE
TypeError: attempted to get private field on non-instance

### ISSUE THREAD

**Issue by gabrieletassoni** [openplayerjs/openplayerjs#235]
**Describe the bug**
Using the library in a Ionic/Vue application, with 2.7.2 as openplayerjs, results in that error, in console, which prevents from the player to switch to another source.
Using 2.6 version works, but I need to use the latest version for some improvements released in 2.7.2.

**To Reproduce**
1. In a Ionic/Vue application, create a vue component which uses the OpenPlayerJS library
2. The openplayerjs initialization works and the m3u8 source set from the `<video><source>` tag works, but as soon as I try to set the player source to another stream, like: `this.player.src = {src: src, type: "application/x-mpegURL"};` it fails with the error in the title
3. It's not clear, for me, from the documentation pointed from [here](https://github.com/openplayerjs/openplayerjs/blob/master/migration.md)  what I have to change in my code to be compliant with 2.7+ version of the library, not being typescript expert is non trivial to find the solution.

**Expected behavior**
When the source is set on an initialized player, it must change the source to the new one.

**Desktop (please complete the following information):**
 - OS:Ubuntu Budgie 20.10
 - Browser: Chrome
 - Version: 90.0.4430.93 (Official Build) (64-bit)

Maybe a working example in the page linked for a 2.6 to 2.7 migration would help better understand how to integrate the library and not have this braking problem.

Thank you very much,
Gabriele

**Comment by gabrieletassoni** [comment]
I also tried other ways to set the src at runtime, by googling around for the error in the title of this bug report, none worked, but i expected this since I'm blind aiming at the problem:

`this.player.src = src`

`this.player["src"] = { src, type: "application/x-mpegURL"}`

`this.player["#src"] = { src, type: "application/x-mpegURL"}`

`this.player.src.set({ src, type: "application/x-mpegURL"})`

**Comment by gabrieletassoni** [comment]
The *TypeError: attempted to get private field on non-instance* happens also when I try to use methods on the player instance, like: 

```javascript
if(this.player) this.player.pause()
```

With an error like:

```javascript
player.js?df63:10 Uncaught (in promise) TypeError: attempted to get private field on non-instance
    at __classPrivateFieldGet (player.js?df63:10)
    at Proxy.pause (player.js?df63:165)
    at Proxy.$route (DeventaPlayer.vue?1e21:59)
    at callWithErrorHandling (runtime-core.esm-bundler.js?5c40:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?5c40:163)
    at Array.job (runtime-core.esm-bundler.js?5c40:2096)
    at flushPreFlushCbs (runtime-core.esm-bundler.js?5c40:328)
    at flushJobs (runtime-core.esm-bundler.js?5c40:368)
```

**Comment by rafa8626** [comment]
@gabrieletassoni if you can prepare a CodePen or similar where I can dig more into this error I’d appreciate it

**Comment by gabrieletassoni** [comment]
Understood, maybe this can be put in documentation if someone wants to use openplayerjs in a Vue.js application:

With 2.7 releases of openplayerjs, the private methods and properties are actually more private than before, this means that, with Vue.js 3, which observes *.vue template variables, by adding [reactivity](https://v3.vuejs.org/guide/reactivity.html) to them, the variable which is used to hold the OpenPlayerJS object is Proxied by Vue's observers, so, the call to player's methods, like play(), init(), pause(), etc. are not called on the player object directly, but are called by the reactivity Proxy in a way not compatible with 2.7+ versions of OpenplayerJS.
The solution is to assign the OpenPlayerJS instantiation to a non-reactive (so un-Proxied) variable, to do so, Vue.js allows to declare $ variables (variables starting with $) which are not observed by the reactivity Proxy.
Thus, going to the point, to use OpenPlayerJS in a Vue Application, you have to declare the object holder like:

```javascript
data() {
	return {
		$player: null
	};
}
```

And then use `$player` in other Vue methods, for example:

```javascript
mounted() {
	this.$player = new OpenPlayerJS('player');
	this.$player.init();
}
```

Having declared the HTML template like, for example:

```html
<template>
	<div class="block live players">
		<div class="video-wrapper">
			<video id="player" class="main op-player__media" controls playsInline autoPictureInPicture
				preload="metadata" height="360" :poster="`${currentURL}/assets/thumbnail-video.jpg`">
				<source :src="`${currentURL}/assets/placeholder.m3u8`" type="application/x-mpegURL" />
			</video>
		</div>
	</div>
</template>
```

**Comment by rafa8626** [comment]
@gabrieletassoni thanks for the info; I’ll add that in the documentation and try to put a CodePen for it
