### ISSUE TITLE
Access to XMLHttpRequest at 'website-domain' from origin 'https://imasdk.googleapis.com' has been blocked by CORS policy:

### ISSUE THREAD

**Issue by asifmushtaqse** [openplayerjs/openplayerjs#244]
I'm using my custom vast tag and it is showing the following console error.

`Access to XMLHttpRequest at 'website-domain' from origin 'https://imasdk.googleapis.com' has been blocked by CORS policy:`

**Comment by rafa8626** [comment]
You need to make sure your VAST server is serving the file with proper CORS permissions. That why you are seeing this.

Thanks for using this player, and please give a star to the project to show your support
