### ISSUE TITLE
Update play buttons on ad click

### ISSUE THREAD

**Issue by draganpetos** [openplayerjs/openplayerjs#252]
Clicking on the ad does not update the play buttons, and there is an additional click needed, before being able to continue playing the ad.

Steps to reproduce:
1. Go to https://codepen.io/rafa8626/pen/vVYKav 
2. Click on the linear ad example and return to player
3. Click play

Expected behavior:
When the ad is paused, the icon should be 'play', click on play should continue playing the ad.

**Comment by rafa8626** [comment]
@draganpetos thanks for reaching out; I'll take a look at it and get back to you as soon as I can. In the meantime, please provide a star to the project to show your support. Thanks!

**Comment by rafa8626** [comment]
@draganpetos this should be fixed; please download the master branch and test it. Let me know if it all works as expected now. Thanks!

**Comment by draganpetos** [comment]
Hi @rafa8626, thank you for the updates. The icons update correctly however, we still need to click the play button twice to continue playing the ad.

**Comment by rafa8626** [comment]
@draganpetos I’ll check this since in my tests it was working as expected but maybe I missed something

**Comment by rafa8626** [comment]
@draganpetos This should be fixed now; please confirm by downloading the master branch

**Comment by draganpetos** [comment]
Now it works, thanks again!
