### ISSUE TITLE
HTML on destroy using mode: fit

### ISSUE THREAD

**Issue by draganpetos** [openplayerjs/openplayerjs#254]
HTML doesn't fully return to its initial state on destroying when using mode: fit, and fit wrapper container 'op-player__fit--wrapper' gets left behind.

Steps to reproduce:

1. create the player w/ mode: 'fit' option
2. run destroy method
3. check the HTML

Expected behavior
Return HTML to its original state on destroy by removing wrapper container.

Calling the init / destroy multiple times:

![PixelSnap 2021-07-04 at 12 03 44](https://user-images.githubusercontent.com/13521410/124474298-a9e82000-dda0-11eb-8671-749df41b79fe.png)

**Comment by rafa8626** [comment]
@draganpetos this should be fixed; please download the master branch and test it. Let me know if it all works as expected now. Thanks!

**Comment by draganpetos** [comment]
@rafa8626 this works as expected now. Thank you!
