### ISSUE TITLE
Ability to refresh VAST file (ad source) without destroying the player

### ISSUE THREAD

**Issue by trampolinstudio** [openplayerjs/openplayerjs#255]
Would it be possible to have a method to refresh the ad source without destroying the player? 

We are trying to switch zones on an active instance (this means switching the VAST file).

Thank you!

**Comment by rafa8626** [comment]
@trampolinstudio please download the master branch and use the new method `loadAd` like this:
```javascript
const player = new OpenPlayerJS( .... );
player.init();

player.loadAd('[YOUR NEW AD]');
```

**Comment by trampolinstudio** [comment]
Thank you!

**Comment by draganpetos** [comment]
This works flawlessly, thank you! 🙌

**Comment by rafa8626** [comment]
You are welcome :)
