### ISSUE TITLE
Ability to provide own hls.js and not load from jsdelivr cdn

### ISSUE THREAD

**Issue by ziegenberg** [openplayerjs/openplayerjs#260]
**Is your feature request related to a problem? Please describe.**

I'd love to use OpenPlayerJS but due to the GDPR, it is necessary for us that all resources are provided locally with the webpage and are not dynamically loaded from a CDN. As long as this requirement is not met, I cannot deploy OpenPlayerJS. Sadly OpenPlayerJS loads hls.js from jsdelivr.net (-> https://cdn.jsdelivr.net/npm/hls.js@latest/dist/hls.min.js)

**Comment by rafa8626** [comment]
@ziegenberg to avoid that you can install the library on your own and that way it won’t use the CDN version to be complaint with GDPR. If you have further questions let me know, and please give a star to the project to show your support.

**Comment by ziegenberg** [comment]
Ah, that works. I tested it.
Should that info be provided in the documentation?

**Comment by rafa8626** [comment]
@ziegenberg yes I’ll include this in the docs for the next release
