### ISSUE TITLE
Add keyboard shortcuts to operate player

### ISSUE THREAD

**Issue by ziegenberg** [openplayerjs/openplayerjs#262]
**Is your feature request related to a problem? Please describe.**
Currently, it's not easily possible to use keyboard controls to interact with the player, except start and stop the video with the `Space` key.

**Describe the solution you'd like**

Implementing keyboard shortcuts similar to the ones available in YouTube would be a nice feature. Using the same key bindings as in YouTube would give the benefit of users not having to learn new keyboard shortcuts if the already know the ones from YouTube.

I propose the following list:

- Pause/Play the video: **K** (or Spacebar, but that's already available)
- Mute/Unmute the video: **M**
- Skip 5 seconds forward/back in a video: **Left/Right arrows**
- Skip 10 seconds forward in a video: **J**
- Skip 10 seconds back in a video: **L**
- Skip to the next frame when the video is paused: **Comma** ","
- Skip to the previous frame when the video is paused: **Period** "."
- Speed up/slow down video playback: **<** or **>**

**Comment by rafa8626** [comment]
@ziegenberg there are some keyboard behavior already implemented as long as the focus is in the video. I didn’t considered global events since in some cases, a page can have multiple players. So I’ll add this global behaviors only if there’s one instance of the player, does that meet your requirements?

**Comment by ziegenberg** [comment]
I didn't find documentation on the keyboard behaviour. And I also tested with the [Firefox Accessibility Inspector](https://developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector) and there were none listed.

I wasn't especially talking about global events, just keyboard control while the player has the focus.

But because you mentioned it, I suggest adding global behaviours only when they are configurable because those global key bindings might interfere with other keyboard shortcuts when the player is embedded into a web application. And yes, also only enable them if there's only one instance of the player.

**Comment by rafa8626** [comment]
@ziegenberg thanks for the heads up; I’ll check this since it should trigger keyboard events for skipping/rewinding, full screen, play/pause. But I’ll add an option to enable global bindings if needed as well

**Comment by rafa8626** [comment]
@ziegenberg please download the master branch and let me know if the new changes satisfy the requirements for keyboard shortcuts on your end

**Comment by ziegenberg** [comment]
I quickly tested those. Works like a charm, thank you very much!
I'll thoroughly test it tomorrow and report afterwards.
Small question: What's the options key to enable global key bindings? Did not find this info in the new documentation.

**Comment by ziegenberg** [comment]
PS: If you want to test yourself with the provided test stream, there the current master is deployed.

**Comment by rafa8626** [comment]
@ziegenberg Sorry I forgot to mention that after doing some research, I didn’t enable the global bindings because it could interfere with other elements. So only if the focus is in the player they will work

**Comment by ziegenberg** [comment]
No problem, than I won't cover this with the tests tomorrow.

**Comment by ziegenberg** [comment]
The keyboard shortcuts [listed in the docu](https://github.com/openplayerjs/openplayerjs/blob/master/docs/api.md#keyboard-shortcuts) are working as expected/documented. Very nice work!

**Comment by rafa8626** [comment]
Thanks @ziegenberg! This will go in the next release, probably by the end of this week
