### ISSUE TITLE
Trouble getting HLS to work

### ISSUE THREAD

**Issue by galipmedia** [openplayerjs/openplayerjs#264]
I am getting the following error... HTTP “Content-Type” of “application/vnd.apple.mpegurl” is not supported.
When trying to use an m3u8 source. I am using the npm package inside of Vue, I needed to manually add the css for some reason but thats fine. I have also imported Hls and it is present when I check the version.

```
this.$player = new OpenPlayerJS('mainVideo', {
      showLoaderOnInit: false,
      pauseOthers: false,
      controls: {
        layers: {
          right: ['settings', 'levels', 'fullscreen']
        }
      },
      hls: {
        startLevel: -1
      }
    })
```

**Comment by rafa8626** [comment]
@galipmedia can you provide a CodePen where this issue is reproduced so I can take a look at it please?

**Comment by galipmedia** [comment]
Its really hard to reproduce in a codePen as its in a pretty mature project. Is there any other way around, could you DM me on discord bigKnightOut#0207 and I can send you the link?

**Comment by rafa8626** [comment]
@galipmedia send me the link via email please. Send it to rafa8626@gmail.com since I don’t use Discord

**Comment by rafa8626** [comment]
@galipmedia I had a thought: change the mine type to application/x-mpegURL, since that’s a more generic type for m3u8; let me know if that worked for you

**Comment by galipmedia** [comment]
I just narrowed down the problem better. I am using a dynamic src in the video element.
```
<video class="full-width op-player__media plyr" id="mainVideo" :poster="poster" >
                           <source :src="videoSrc" />
 </video>
 ```
 This is a regular data element in Vue, it gets set after an ajax request but before OpenPlayer is initialised. If I use a static src it works fine. Would setting the source via the openplayer api work? I will try to figure it out.

**Comment by rafa8626** [comment]
@galipmedia yes, when dealing with dynamic sources is better to rely on the OP API to set the dynamic source without issues. I’ll add that as part of the updates on the documentation for the next release

**Comment by galipmedia** [comment]
I tried 
```
this.$player.src = `${this.cloudFront}/vods/${this.currentComposition.uuid}/manifest.m3u8`
this.$player.init()
    ```
    Now I get the following error...
```Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.```

**Comment by rafa8626** [comment]
@galipmedia what happens if you invert the order of the operations? First you initialize and then set the source?

**Comment by galipmedia** [comment]
I tried that and I get different errors.
![image](https://user-images.githubusercontent.com/1904800/129444416-2ab971a5-53c9-4042-be52-1944a30a0526.png)

**Comment by rafa8626** [comment]
@galipmedia ok let me check this, but at least I’ll need a snippet of the generated HTML to see what’s being generated, and I’ll keep you posted about it

**Comment by galipmedia** [comment]
I get this error when reversed...
![image](https://user-images.githubusercontent.com/1904800/129444531-ef43d2b1-100a-4b23-8ca0-9fa3c7c14afe.png)

**Comment by galipmedia** [comment]
Everything looks normal but the <video src is the m3u8 when usually when m3u8 is working it looks like a blob.

**Comment by rafa8626** [comment]
Yeah, that means that the source is not set correctly. I’ll need to dig deeper to see what’s going on, because this was working before

**Comment by galipmedia** [comment]
Just to confirm it doesn't work when setting a hardcoded m3u8 so it doesn't seem to be a reactivity issue. Thanks for looking into it.

**Comment by galipmedia** [comment]
Using a dynamic mp4 after init works fine.

**Comment by galipmedia** [comment]
Seems to work if I use this.$player.load() after init and before play. But I wonder if I should be waiting for hls manifest passed before hitting play to be sure?

**Comment by galipmedia** [comment]
I got it working like this...
```
    this.$player.init()
    this.$player.src = `${this.cloudFront}/vods/${this.currentComposition.uuid}/manifest.m3u8`
    this.$player.load()
    this.$player.getElement().addEventListener('hlsLevelLoaded', (e, data) => {
      this.$player.play()
    })
    ```

**Comment by galipmedia** [comment]
I finally got it working like this...
```
this.$player = new this.$openPlayer('mainVideo', {
        showLoaderOnInit: false
      })
      this.$player.init()      
      this.$player.src = `${this.cloudFront}/vods/${this.currentComposition.uuid}/manifest.m3u8`
      this.$player.load()
      const that = this
      this.$player.getElement().addEventListener('hlsManifestParsed', (e, data) => {
        that.$player.play()
        that.$player.loadAd('https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=')
      })

**Comment by galipmedia** [comment]
I also have to destroy the player on beforeRouteChange when switching to another video, then re init.

**Comment by galipmedia** [comment]
However I still get 2 console errors every time.
![image](https://user-images.githubusercontent.com/1904800/129475566-f735c7e6-1ee6-4c94-845a-e7bebe6c39fc.png)
![image](https://user-images.githubusercontent.com/1904800/129475582-5c9bf227-cd0b-4f4e-9bc8-60eaa907ec7b.png)

**Comment by rafa8626** [comment]
@galipmedia I agree that the player needs to be destroyed when changing routes (similar to what React would do), but I still see that the way to assign a dynamic source is not the right one, since I had a CodePen that did that and it’s not working now. So there was a change introduced that affected that, but I need to figure out what was it

**Comment by rafa8626** [comment]
The second error is related to the Ads, so that one you will need to verify it by checking the content of the ads; could be that the ads content is not ready when you load it, or definitely there’s something malformed in it

**Comment by rafa8626** [comment]
@galipmedia please download the master branch and let me know if it works for you now; I'd definitely use something like this for your purposes: 
```javascript
     const that = this;
     this.$player = new this.$openPlayer('mainVideo', {
        showLoaderOnInit: false
      });
     this.$player.src = `${this.cloudFront}/vods/${this.currentComposition.uuid}/manifest.m3u8`
     this.$player.getElement().addEventListener('hlsManifestParsed', (e, data) => {
        that.$player.play();
        that.$player.loadAd('https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=');
     });
     this.$player.init();
```

**Comment by galipmedia** [comment]
I updated to the latest code. Putting init at the end causes the video to not load at all, no errors but the m3u8 is never fetched. Keeping it where it was works but throws the same errors as before in console.

**Comment by rafa8626** [comment]
@galipmedia if you can create something that I can see public that would help me because in my tests all worked as expected

**Comment by galipmedia** [comment]
It might be worth noting that I am using Vue 2. I finally got it working without any errors, by putting the src back into the html <video> tag. I removed this.player.load() and this.player.src = and put init at the end as you suggested. No errors :)

**Comment by rafa8626** [comment]
You are welcome!
