### ISSUE TITLE
VPAID errors events not emitted

### ISSUE THREAD

**Issue by mdevang10** [openplayerjs/openplayerjs#266]
**Describe the bug**
**[ima.admanager.VpaidAdManager] Vpaid Error: Ad blocked** not thrown on "playererror" event.
I am trying to load an VPAID ad on open playe audio Instance.
The above mentioned error is thrown by ima sdk in the console when we use debug=true in the ads option.

**To Reproduce**
Use any VPAID enabled VAST XMLs

**Expected behavior**
**Ad error: AdError 901: An unexpected error occurred within the VPAID creative. Refer to the inner error for more info. Caused by: Error: Error: Ad blocked**
The above error should trigger onError method which is not happening and silently failing after adsLoaded event.
Used https://googleads.github.io/googleads-ima-html5/vsi/ to test the vast url and capture the above error.

**Code Snippet**
```
const player = new OpenPlayer("audio", {
            ads: {
                debug: true,
                src: <Dummy VPAID enabled VAST url>,
            },
            controls: {
                layers: {
                    left: ["play"],
                    middle: ["progress"],
                    right: ["time"],
                },
            },
            onError: (e) => {
                console.log("error");
                console.log(e);
            },
        });
        player.init();
```

**Screenshots**
![image](https://user-images.githubusercontent.com/23494961/130319593-55d824d6-4957-47e9-95a7-9b1fb836eb49.png)

warning can be observed in the console but not passed on onError method.

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: Chrome
 - Version: Openplayer js v2.8.2

**Comment by rafa8626** [comment]
@nejcsever thanks for reporting this; I’ll research this and keep you posted. Please give the project a star to show your support

**Comment by mdevang10** [comment]
Sure :). If you need any assistance do contact me on mdevang10@gmail.com

**Comment by rafa8626** [comment]
@mdevang10 if the AdBlock is enabled, it won't even load IMA SDK. I added a check for that. Please download the master branch and let me know if it works for you. As far as I know, there's no documentation to grab those log events, since they are not logged in IMA as errors. I'll continue looking but this should work as well

**Comment by mdevang10** [comment]
Hello, yes if the ad blocker is on then the network call to ima ask will time out agreed. But this error is due to the VPAID settings of ads manager. The url I am trying to use, requires secure VPAID mode and since the default settings is insecure, hence the error is thrown on adsManager Ad error event which is currently not being captured. I will provide you with the sample URL, that might help you to analysis the issue. I appreciate the quick response from your side. You are really doing a great job by providing an open source audio vast player which is I guess the only one available in the community right now.

**Comment by mdevang10** [comment]
Hello @rafa8626,
The below test cases are failing while running test suite/build on latest master branch.
![image](https://user-images.githubusercontent.com/23494961/130389240-f10d1efe-b636-4e94-8f45-98cbe5eb2fb6.png)

Also the documentation for the same can be found at below links. The error is thrown by IMA sdk and while using videojs and videojs-ima libraries the same is passed onto player's error event listener.
Below are the links for the documentation of the error.
https://support.google.com/admanager/answer/4442429?hl=en (check error 901)

https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdError (check VPAID_ERROR that is thrown on AdError)

Same error thrown by Google's VAST URL tester
![image](https://user-images.githubusercontent.com/23494961/130389555-236d5fec-5d8c-418f-be34-5b31c28d7f1b.png)
Note: Ad blocker is turned off while testing this. The IMA plugin is loaded. Ad is also loaded (events can be seen in the screenshot) and it is then blocked from the Ad server and hence the error.

Links for Videojs and videojs-ima plugins which handles these errors just like google tester.(Main library is videojs and the remaining two are used as plugins to show ads)
https://www.npmjs.com/package/video.js?activeTab=readme
https://www.npmjs.com/package/videojs-contrib-ads
https://www.npmjs.com/package/videojs-ima

Due to security reasons I am unable to share the VAST url I am using. I hope this information helps you to resolve the issue. If you need anything else feel free to tag me in the comment with the question Ill be happy to help :)

**Comment by mdevang10** [comment]
Hi @rafa8626, Just an update
The Adblocker detection is working and the error is thrown on onErr function. I have tested on your latest master branch. 
Also the 2 test cases are still failing, and that VPAID issue still persists.

**Comment by mdevang10** [comment]
Hey @rafa8626 any updates on the issue?

**Comment by rafa8626** [comment]
@mdevang10 thanks for the hints you provided! Please download the master branch and let me know if it captures the event as you expect; it's hard for me to test this without a sample that has the issue, but I think I found out the reason why it wasn't being dispatched

**Comment by mdevang10** [comment]
Hi @rafa8626, thanks for continuous support. Ill surely test this first thing tomorrow and post that you can release the tag. I hope this also fixes the 2 failed test suites 😊

**Comment by rafa8626** [comment]
@mdevang10 the 2 failing test cases are because I’m trying to expand the test cases but I haven’t found how to make them work; nothing is wrong with the player right now

**Comment by mdevang10** [comment]
Hi @rafa8626 , this is working as expected :) I can see the below error thrown on onErr function.
AdError 901: An unexpected error occurred within the VPAID creative. Refer to the inner error for more info. Caused by: Error: Error: Ad blocked 

Thank you so much for quick resolution. You are doing a great job.

**Comment by mdevang10** [comment]
Hey @rafa8626  can you please release the tag so that I can used it as a package.

**Comment by rafa8626** [comment]
@mdevang10 yes I’ll release the next version this week; I need to have the resolution on one more issue and that will be it. I’ll let you know once it’s drployed

**Comment by mdevang10** [comment]
Hey @rafa8626 I found one more bug post the latest changes which is on destroy method.

PFB Screenshoot for the error and the error message.
Error occurring when calling player.destroy() using latest master branch.

ERR MSG - 
```
Uncaught TypeError: Cannot read property 'removeEventListener' of null
    at Ads.destroy (webpack-internal:///../di-component-lib/node_modules/openplayerjs/dist/esm/media/ads.js:220)
    at Player.destroy (webpack-internal:///../di-component-lib/node_modules/openplayerjs/dist/esm/player.js:203)
    at eval (webpack-internal:///../di-component-lib/packages/react-component-internal/src/js/components/AudioPlayer/AudioPlayer.js:95)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:347)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:397)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:454)
    at safelyCallDestroy (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19900)
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20279)
    at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:643)
    at runWithPriority$2 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11305)
```

![image](https://user-images.githubusercontent.com/23494961/130619294-4c776048-3515-465c-bbe1-18e20b9ee6a1.png)

Let me know once this is resolved so that I can retest

**Comment by rafa8626** [comment]
@mdevang10 thanks for finding this; I'll fix it in a bit and let you know

**Comment by rafa8626** [comment]
@mdevang10 it should be fixed now; please download the master branch and let me know if it worked as expected on your side. Thanks again for all your help!

**Comment by mdevang10** [comment]
Hey @rafa8626 
Everything is working now :). Please release the tag and let me know

**Comment by mdevang10** [comment]
Just wanted to ask @rafa8626  by when you will releasing the tag for the same ? so that I can plan my timelines accordingly.

**Comment by rafa8626** [comment]
@mdevang10 I estimate that by Friday this week I’ll release the next version
