### ISSUE TITLE
Volume control: can I override it's functionality?

### ISSUE THREAD

**Issue by gabrieletassoni** [openplayerjs/openplayerjs#271]
In a web page, I have one main video player and some (hidden) audio players, I added a custom control on the main player to play the audio players keeping them in sync with the main Video player. Now I would like to have a control on the main video player to adjust volume and mute for the currently playing hidden audio player, ideally it would be the same volume control which openplayerjs shows on the player UI but with the methods which handle mute and volume level overridden by methods I write.
Is there a clean way to do or achieve this? Something undocumented, but functional?
Thank you very much.

**Comment by rafa8626** [comment]
@gabrieletassoni I think what you are looking for is driven by events; so if you wanna dispatch something custom, you could use the `volumechange` event for it. For example:
```javascript
player.getElement().addEventListener('volumechange', () => { // ... all your code there, including the manipulation of other players });
```

**Comment by gabrieletassoni** [comment]
> @gabrieletassoni I think what you are looking for is driven by events; so if you wanna dispatch something custom, you could use the `volumechange` event for it. For example:
> 
> ```javascript
> 
> player.getElement().addEventListener('volumechange', () => { // ... all your code there, including the manipulation of other players });
> 
> ```

Hi, thanks for the answer, I'll investigate this ruote tomorrow, but at a first glance it looks that this solution does keep the two volumes somewhat chained, not allowing to have a muted video player while one of the audio players is set to the volume level set using the gauge on the videoplayer, for example, from an initial thinkering, it looks like the following flow will be impossibile (since the audio player would always follow video player, having both muted at the same time or always at the same level):

- Play one of the audio players, while video player still plays
- Then mute the video player
- Move the Video Player volume gauge at, i.e. 50% setting audio player to 50%, but keeping video player muted

**Comment by gabrieletassoni** [comment]
I resolved by not using the player volume, setting it to 100% and using the computer/smartphone physical buttons. ^_^
