### ISSUE TITLE
Cannot catch player.play() exceptions

### ISSUE THREAD

**Issue by gabrieletassoni** [openplayerjs/openplayerjs#276]
If I try to play the player before user interaction with the page it, rightfully, throws an exception I can see in the console, but I'm not able to catch the exception, I tried: 

```javascript
player.play().catch(e => console.log("Catched!"))
```

but the exception is thrown anyway and pollutes the console, but the "Catched!" string is not dumped in the console.

The exception is this:

```
Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.
```

I would like to be able to catch it to show a proper alert.

Thank you,
Gabriele

**Comment by rafa8626** [comment]
@gabrieletassoni thanks for logging this one. I’ll check what needs to be added there; do you have a CodePen that I can use for testing purposes?

**Comment by rafa8626** [comment]
@gabrieletassoni please check the `unit-tests` branch in the project and test if that solves your issue; this branch will be merged soon, but I wanted to integrate that test as part of the suite I'm working on progressively to ensure proper behaviors. Let me know if it worked for you, and thanks again for reporting this.

**Comment by gabrieletassoni** [comment]
Thank you very much @rafa8626 I can test it only on monday CET, but I'll surely do and report back.

**Comment by rafa8626** [comment]
Thank you! I'll wait for your feedback

**Comment by rafa8626** [comment]
I found out an error when bundling. I’ll check it and let you know when it’s fixed

**Comment by rafa8626** [comment]
@gabrieletassoni it should work now as expected. Test the `unit-tests` branch and let me know. If this works as expected, I'll try to add a couple more unit tests during this week and release on Friday, while I continue working on adding more and more unit tests

**Comment by gabrieletassoni** [comment]
Ok, it works! I can catch the exception on play.

**Comment by gabrieletassoni** [comment]
Thank you very much

**Comment by gabrieletassoni** [comment]
Need to reopen this since also on the pause() is  throwning an uncatchable exception, when the video pauses (reached the end of the playtime), and no interaction has occurred on the page, I can see the following error:

```
Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.
```

The stranger thing, to me, is also that it looks like pause() is threated like play(), in the exception the error comes in this event manager, at the pause() call:

```javascript
        player.getElement().addEventListener('pause', function (e) {
            OpenPlayerJS.instances[activeAudioTrack].pause();
        });
```

**Comment by rafa8626** [comment]
@gabrieletassoni I’ll take a look at this; it’s odd because I didn’t modify the pause at all

**Comment by rafa8626** [comment]
@gabrieletassoni I tested this with my unit-tests branch and your gist, and I couldn't reproduce this issue. The pause worked as expected.

**Comment by gabrieletassoni** [comment]
uhm! As stated in the other ticket, I try to reset chrome, maybe it's that... It feels strange anyhow.

**Comment by rafa8626** [comment]
@gabrieletassoni if you have a CodePen where it can be reproduced I can take a look at it, but so far I haven’t been able to reproduce. Or try to reproduce the bug in FF

**Comment by gabrieletassoni** [comment]
Resetting Chrome made the problem disappear, ok, the Promise chain for play() works as expected.
Thank you
