### ISSUE TITLE
Interact with openplayerJS DOM

### ISSUE THREAD

**Issue by gabrieletassoni** [openplayerjs/openplayerjs#278]
Hi, I'm finding an unexepcted behaviour while trying to interact with openplayerjs manged DOM elements, by using javascript.
It looks like, if I add a class using Javascript to an element, the modification is not persisted on the rendering but only on an in-memory representation of the element.
I try to explain better, at this gist a self contianed (except for images, sorry) code (https://gist.github.com/gabrieletassoni/04ee9a5408f34841c98df52fff023f28).

At line https://gist.github.com/gabrieletassoni/04ee9a5408f34841c98df52fff023f28#file-index-html-L405, I try, from this script in the html page, to add the 'selected' class to one of the elements in a customControl. The class is not added, since the element background does not turn orange. 
But if you see, at line https://gist.github.com/gabrieletassoni/04ee9a5408f34841c98df52fff023f28#file-index-html-L292, in the click function insed the custom control menu item, I can interact with the DOM and I see the change reflected. It looks like from inside the click event management of the custom control I have access to the DOM elements of the player, from outside the click event, I cannot add classes or manipulate the elements which are part of the openplayerjs instance.

Thank you very much

**Comment by rafa8626** [comment]
@gabrieletassoni thanks for reporting this; I’ll use your gist to solve both issues

**Comment by rafa8626** [comment]
@gabrieletassoni Interesting, because I could see the element turning orange when I used my local machine and pretty much copied/pasted your gist. Instead of using the library as you had, I just used the paths for styles and the plugin and worked. See attached screenshot. Is that what you expected?
<img width="1015" alt="Screen Shot 2021-09-13 at 5 41 32 PM" src="https://user-images.githubusercontent.com/910829/133160328-4b6adf6c-410a-4088-b0a3-93ce53d619ff.png">

**Comment by gabrieletassoni** [comment]
Yes, if you didn't clicked anywhere (just page load, it "selects" the first language during , that's the intended behaviour... I try to reset Chrome to factory defaults, maybe it lies there :thinking:  so strange

**Comment by rafa8626** [comment]
@gabrieletassoni have you tried setting that up using the init callback in the button configuration? That option is intended to set things right from the beginning before any interaction from the user

**Comment by gabrieletassoni** [comment]
I completely missed the `init: (player) => {},` callback, sorry, tomorrow i test this path

**Comment by gabrieletassoni** [comment]
@rafa8626 using the init callback (after placing the `player.init()` down below all the `player.addControl(..)` instructions, did the trick.

```
init: (player) => {
                document.querySelector(`#submenu-${id}`).classList.add("selected")
            }
```

Thank you very much

**Comment by rafa8626** [comment]
@gabrieletassoni glad to hear it :) I'll be releasing this new version maybe by the end of this week
