### ISSUE TITLE
player.play() not starting audio player on load

### ISSUE THREAD

**Issue by timstoute** [openplayerjs/openplayerjs#280]
Hi, thanks for your excellent work here. I'm hoping to use the api to start and stop the player, as my goal is to implement a playlist that will progress through a series of sources (with vast audio ads in between). I assume I'm doing something wrong, but I cannot script the player start event. Here's my audio only player  codepen (it includes an ad call too): https://codepen.io/timstoute/pen/jOwYeJr

**Comment by rafa8626** [comment]
@timstoute thanks for using the project! I’ll take a look at it during the day and let you know my thoughts. If there’s anything wrong I’ll make sure it’s fixed

**Comment by rafa8626** [comment]
@timstoute the proper way to use it is like this: 
```javascript
player.init();
player.src='https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3';
player.load();
```
however, I see an issue doing with Ads;  if you remove the Ads, it will work. I'll try to pin point what's the issue using your code and let you know

**Comment by timstoute** [comment]
thanks @rafa8626, I've altered [the codepen](https://codepen.io/timstoute/pen/jOwYeJr) as you suggested, but it's still not playing on page load, even with the ad removed

`player.init();
player.src='https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3';
player.load();
setTimeout(() => {
      console.log("waited, now calling play()");
      player.play()
    }, 1000);
`
I appreciate your review and help

**Comment by rafa8626** [comment]
@timstoute try this one: https://codepen.io/rafa8626/pen/PojaKyN

Keep in mind that the size of the window matters for auto play policies, as stated here: https://developer.chrome.com/blog/autoplay/

So in a small screen you won't be able to autoplay no matter what you do

**Comment by rafa8626** [comment]
I need to take a look, because the behavior is not consistent even in larger screens. So let me take a look and I'll let you know my findings

**Comment by rafa8626** [comment]
@timstoute interesting enough, this is not an issue with video. Audio, after playing with it, it doesn't allow to be autoplayed, until the user interacts with the page in any capacity. I saw it working on my CodePen because I had used the play button in prior tests. So what I'd recommend here is to have a layer that says Start Playing, or something like that, that will dispatch the initial play; after that, if you need to switch media, you can do it programatically. But there has to be a prior click in the page so this works for audio. Hope this helps. In the meantime, I'm working on some improvements with the play/load mechanisms in the `unit-tests` branch if you are interested on testing them.

**Comment by rafa8626** [comment]
@timstoute sorry for a lot of back and forth. Given the dynamic nature of your example, I'd suggest you to use the following snippet and use my `unit-tests` branch to test it:
```html
<html>
    <head>
        <link rel="stylesheet" href="../dist/openplayer.css" />
    </head>
    <body>
        <h1>Audio Ad</h1>
        <div class="players audio-player">
            <div id="stream-info" class="hidden"></div>
            <img class="cover" />
            <audio class="op-player__media" id="audio1" controls playsinline></audio>
        </div>
        <script src="../dist/openplayer.js"></script>
        <script>
            const player = new OpenPlayerJS('audio1');
            player.src = 'https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3';
            player.init().then(() => {
               // This is how I'd load ads dynamically in your case
               player.loadAd('https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=');

                // Give some time before you start the autoplay
                setTimeout(() => {
                    player.play();
                }, 300);
            });
        </script>
    </body>
</html>
```
I tested this on desktop and it autoplayed, at least in my local environment. On mobile (even emulator), it is still requiring an action from the user to autoplay. The only way to make it autoplay across the board (including in mobile) is to  add a `muted` attribute in the audio tag. That I was able to test it in desktop and mobile and worked like a charm, but I'm not sure if that's something you can get away with.

I couldn't set the Ads due to an error on my browser, so please test it and let me know if it works with the ads as well.

**Comment by timstoute** [comment]
@rafa8626 thank for you for this, very helpful - great insight on the autoplay / browser requiring user interaction before the audio can play issue.  I'll test with your branch and let you know how it goes with ads ( I'm using the npm package in an Ionic / Angular project but will install the branch).

**Comment by rafa8626** [comment]
@timstoute yes, please keep me posted because it's not often that I have the opportunity to hear from people using ads with audio only. And if that's the case, I need to know if there are features missing for it.

**Comment by rafa8626** [comment]
@timstoute any updates on your testing with the unit-tests branch? I'd recommend you to download it again and test since I fixed a couple of things in the bundle

**Comment by timstoute** [comment]
hi @rafa8626 - I'm still on it, but was pulled away from this project temporarily.  In my package.json file I have` "openplayerjs": "github:openplayerjs/openplayerjs#unit-tests"` installed, but will refresh this based on your comment above. I have been seeing success with the player and inclusion of ads with my ad tag, but the ads seem to play intermittently - in other words they seem to work about half the time. BUT - I need to spend more time with this to see what's going on, and also I was hoping to create an Angular code pen so as to share the actual code with you.

**Comment by rafa8626** [comment]
ok sounds good; keep me posted

**Comment by rafa8626** [comment]
@timstoute I'm gonna release the changes I have so far, and I'm gonna take a good look at the intermittent issues you reported in the `v3.0.0` branch I just created. I need to refactor some stuff to make it consistent but it may take some time to get it all working. So for now, all unit-tests changes are now in master and I'll release them today

**Comment by timstoute** [comment]
@rafa8626 update: 
1. I'm using OpenPlayerJS 2.9.0
2. perhaps we should start a new issue since the original issue here seems resolved - i.e. audio requires interaction before the api play() method will work 
3. I'm still having intermittent success with ad plays; for example in my tests I see:
player.isAd() returns true
adInstance.started()  returns  true
but the player stalls and nothing plays / nothing happens
4. iv) Codepen, with errors, in progress here (Angular 6, OpenPlayerJS 2.9.0 min.js): https://codepen.io/timstoute/pen/NWgoqaQ?editors=1111
