### ISSUE TITLE
unable to load and play audio ads via api

### ISSUE THREAD

**Issue by timstoute** [openplayerjs/openplayerjs#283]
**Describe the bug**
I'm unable to load and play ads via the OpenPlayerJS API in my audio only Angular 6 / Node project.

**To Reproduce**
See CodePen: https://codepen.io/timstoute/pen/NWgoqaQ?editors=1111

When line 49 is NOT commented out (//), and lines 52 - 72 ARE commented out, the player loads, initialises and plays when the Play button is pressed. 

When line 49 is commented and lines 52-72 are not commented out, the player does not play an ad or the media file. Lines 52-72 call the player.init() method, and then use promise then to continue with additional instructions to load an ad in the player.

**Expected behavior**
With respect to the codepen, I expect that when lines 52-72 are included in the codepen (while line 49 is commented out), and the user presses the player Play button, an ad should load and play,  subsequently followed by the playing of the primary media source.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Browser Chrome, Linux Ubuntu
 - Version 94.0.4606.54 (Official Build) (64-bit)

**Additional context**
OpenPlayerJS 2.9.0  (https://cdn.skypack.dev/openplayerjs@2.9.0)

**Comment by rafa8626** [comment]
@timstoute please download the master branch and let me know if it works as expected. I'm in the middle of adding unit tests for this case to prove that will work consistently, but in the meantime, if you could do me that favor I'd appreciate it

**Comment by timstoute** [comment]
Hi @rafa8626, with my local dev project I've verified I have the master branch installed `openplayerjs@2.9.0 (git+ssh://git@github.com/openplayerjs/openplayerjs.git#c109bb9a1a1f610fab7ecc3edf895c6d1c21cf35)` but I'm still not getting the ad to play.

When I comment out the line `this.player.loadAd('https://pubads.g...')` the player.src DOES play as expected.

When I include the line `this.player.loadAd ...`  the following code logs out: "player is playing an ad" and  "adInstance.started() =  true", but the ad is not actually playing.

```
this.player.loadAd('https://pubads.g.doubleclick.net/gampad/ads?iu=/393492695/toasties-ad-unit&description_url=https%3A%2F%2Flocalhost%3A8100%2Ftabs%2Ftab1&tfcd=0&npa=0&ad_type=audio&sz=1x1&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=');

setTimeout(() => {
          this.player.play()
            
            .then(result => {
              console.log("play()")

              if (this.player.isAd()) {
                console.log("player is playing an ad")
                this.adInstance = this.player.getAd()
                this.adInstance.play();
                console.log("adInstance.started() = ", this.adInstance.started())
              }
            })
            .catch(err => {
              console.log("error during play = ", err)
            })
            
        }, 500);
```

**Comment by rafa8626** [comment]
@timstoute Try this: 
```javascript
videoPlayer.src = 'https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3';
            videoPlayer.load();
            videoPlayer.loadAd(
                'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator='
            );

            try {
                videoPlayer.play();
            } catch (err) {
                throw new Error('error');
            }
```
You don't need to execute a play for Ads individually, since it is already considered in the flow for `play()`

**Comment by timstoute** [comment]
Ok, thanks - I tried this but still no luck, and no errors thrown either. Notes:

1) If I comment out the this.player.loadAd() line the main src file plays properly.

2) If I leave the loadAd() in, grab a reference to the ad instance, and check the play status it shows as true:
 ```
try {
                this.player.play();
                this.adInstance = this.player.getAd()
                console.log("adInstance.started() = ", this.adInstance.started())
            }
```

**Comment by rafa8626** [comment]
Can you update your CodePen with the newest build from master so I can see what’s the issue? Because it passed the tests on my side

**Comment by rafa8626** [comment]
You know? I missed to tell you: use `init` as a Promise. So your whole example should use this: 

```javascript
this.player = new OpenPlayerJS(id);
this.player.init().then(() => {
     this.player.src = 'https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3';
     this.player.load();
     this.player.loadAd(
                'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator='
            );

      try {
         this.player.play();
      } catch (err) {
         throw new Error('error');
     }
});
```
That's why your example may not be working. But this is the sample I used on my side and worked perfectly fine

**Comment by timstoute** [comment]
ok, thanks again for your help with this :)

Here's a code pen that I think illustrates the issue I'm still seeing: 
https://codepen.io/timstoute/pen/NWgoqaQ?editors=1111

Notes:
I've commented out the .play() since that fails unless the user has interacted with the document as we previously established.
If I comment out the  this.player.loadAd() line the player.src does play properly.
I'm importing this openplayerjs (which is hopefully correct): https://raw.githubusercontent.com/openplayerjs/openplayerjs/master/dist/openplayer.js

**Comment by rafa8626** [comment]
@timstoute I checked the CodePen you sent me and I see a problem: you imported OpenPlayerJS from the CDN and then you attempted to import it from GitHub. And the import from GitHub is not being used at all, since it's being coded as plain text, and CodePen complains about it. If you wanna test it again, use the **promises** branch and try it again, but make sure you are not importing the library more than once

**Comment by rafa8626** [comment]
@timstoute Check this CodePen (it's using the promises branch) where I prove that the workflow I gave you works: https://codepen.io/rafa8626/pen/gORJWVz

**Comment by timstoute** [comment]
yes, sorry, I mistakenly forgot to remove the 2.9.0 OpenPlayerJS import; I've corrected this now. Thank you for your example codepen, I see the sequence does work in that case. 

I can only assume there is something about the Angular environment that is causing my codepen to still not play pre-roll ads; the codepen shows "AdError 1205: The browser prevented playback initiated without user interaction." But I have the `muted` attribute in the audio tag.

https://codepen.io/timstoute/pen/NWgoqaQ?editors=1111

**Comment by rafa8626** [comment]
@timstoute yeah, honestly, I don't know since I don't have experience with Angular. I just forked your CodePen and I see the same on mine: https://codepen.io/rafa8626/pen/RwgmpBN?editors=0010, but I really don't know how to bypass this in Angular, since in regular mode it worked as expected

**Comment by rafa8626** [comment]
I think in your case, it is very recommendable to create a div that says Start the first time the user gets to the page, and then, once the user clicks in it, remove the DIV and do the whole workflow, since at that point, the user would have interacted with the page.

**Comment by rafa8626** [comment]
@timstoute let me know if you approve my fix so I can prepare the release in the next few days, so I can focus on 3.0.0

**Comment by timstoute** [comment]
hi @rafa8626 - I approve the fix :) as the codepen you sent clearly show it working in a non Angular environment. I think the issue I'm seeing is specific to the way the ads load in the Angular;  wrt to Angular, I think I'm getting close to a breakthrough using techniques to attach the player and load ads into the DOM following the initial app init and DOM load / render. I need more time, but aim to get a codepen illustrating this.

**Comment by rafa8626** [comment]
@timstoute thanks for the thumbs up; I’ll release this today, just FYI
