### ISSUE TITLE
Ads Does't wokr  VAST 

### ISSUE THREAD

**Issue by virienko** [openplayerjs/openplayerjs#295]
Good afternoon. Thanks for a great project.
I am very interested in using it in my projects. I looked at examples:
[https://codepen.io/rafa8626/pen/wvvxbMN](url)  - It doesn't work at all :(
[https://codepen.io/rafa8626/pen/gORJWVz](url) -This will only work if you allow the browser to autoplay video and audio

How do I prevent autoplay? How to play ads only after clicking the play button ? 
How to get a working version with multiple urls?

Thank you very much in advance:)

**Comment by rafa8626** [comment]
@virienko thanks for considering using the project! I’ll take a look and let you know what’s the issue. Do you happen to have a logo and demo URL you can share with me where you showcase the player? If so, I’d like to include it in a section I’ll be putting for version 3

**Comment by rafa8626** [comment]
And also, can I ask you to give the project a star to show your support, please?

**Comment by rafa8626** [comment]
@virienko sure let me see what I can do and I’ll share it with as soon as I can

**Comment by virienko** [comment]
For example this does not work (I took video and ad from your example ): 
`<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.js"></script>
</head>
<body>
<video class="op-player__media" id="video" controls playsinline>
    <source src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" type="video/mp4">
</video>
<script>
    // Check the `API and events` link below for more options
    const player = new OpenPlayerJS('video', {
        ads: {
            src: ['https://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=is&c=23&pl=VAST&pli=14432293&PluID=0&pos=8834&ord=%5Btimestamp%5D&cim=1', 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=',]
        }
    });
    player.init();
</script>
</body>
</html>`

This will be blocked by any browser due to autoplay:

`<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.js"></script>
</head>
<body>

<video class="op-player__media" id="video" controls playsinline>
    <source src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" type="video/mp4">
</video>

<script>
    // Check the `API and events` link below for more options
    const id = 'video';
    const player = new OpenPlayerJS(id);
    player.init().then(() => {
        player.load();
        player.loadAd('https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=');

        try {
            player.play();
        } catch (err) {
            throw new Error('error');
        }
    });
</script>

</body>

</html>`

**Comment by virienko** [comment]
For example this does not work (I took video and ad from your example ):
`<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.js"></script>
</head>
<body>

<video class="op-player__media" id="video" controls playsinline>
    <source src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" type="video/mp4">
</video>

<script>
    // Check the `API and events` link below for more options
    const player = new OpenPlayerJS('video', {
        ads: {
            src: ['https://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=is&c=23&pl=VAST&pli=14432293&PluID=0&pos=8834&ord=%5Btimestamp%5D&cim=1', 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=',]
        }
    });
    player.init();
</script>

</body>

</html>

This will be blocked by any browser due to autoplay:

`
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.js"></script>
</head>
<body>

<video class="op-player__media" id="video" controls playsinline>
    <source src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" type="video/mp4">
</video>

<script>
    // Check the `API and events` link below for more options
    const id = 'video';
    const player = new OpenPlayerJS(id);
    player.init().then(() => {
        player.load();
        player.loadAd('https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=');

        try {
            player.play();
        } catch (err) {
            throw new Error('error');
        }
    });
</script>

</body>

</html>

**Comment by virienko** [comment]
This is where I do it in my HTML

https://codepen.io/virienko/pen/bGrdwMK - This does not work

https://codepen.io/virienko/pen/MWvwjXd - This will be blocked by any browser due to autoplay

**Comment by rafa8626** [comment]
@virienko the second one has to have the muted attribute to autoplay as expected due to browser policies; I’ll check why the first one is not working

**Comment by rafa8626** [comment]
@virienko the fix has been released now; you should be able to get the Ads working in both ways, but for the autoplay one, I'd suggest to use `muted` as attribute to make it happen correctly

**Comment by rafa8626** [comment]
@virienko I tested the CodePen and it works; make sure you don't have cache in your browser. Also, I realized that the CDN may have not refreshed the cache on its side, so setting the URL from https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.js to https://cdn.jsdelivr.net/npm/openplayerjs@2.9.2/dist/openplayer.min.js helped to fix the issue
