### ISSUE TITLE
unable to play second ad and second audio file

### ISSUE THREAD

**Issue by timstoute** [openplayerjs/openplayerjs#296]
Codepen: 

https://codepen.io/timstoute/pen/porJLvN?editors=1111

Expected behavior:

Pressing the "Play" button in the Codepen plays i) an ad and then ii) the audio file src. <-- this works properly

Then, pressing the "Play Next" button should load and play a second ad, followed by a second audio file <-- but this does not happen. No errors are shown. Console logging indicates that the next ad is loaded, but the player does not play.

Additional context:

Hoping for some guidance.
Angular 9, TypeScript, OpenPlayerJS 2.9.2

**Comment by rafa8626** [comment]
Sounds good; I’m just checking one last thing and I’ll release this later today (if this last thing is sorted out)

**Comment by rafa8626** [comment]
@timstoute by the way, do you have a logo and demo URL for your project that you can share with me? I’d love to include it as part of the projects section I’m working on
