### ISSUE TITLE
Title prop for skipping ads

### ISSUE THREAD

**Issue by pooryak** [openplayerjs/openplayerjs#300]
Could you please provide a prop for changing the skip ads text?

**Comment by rafa8626** [comment]
@pooryak since OpenPlayerJS uses IMA SDK to play ads, there’s no way to change that label since it violates their policies and could interfere with translations. 

Can you provide a star to this project to show your support to it, please?

**Comment by pooryak** [comment]
sure,
thanks, I want to translate skip add to Persian so there isn't any solution for that?

**Comment by rafa8626** [comment]
If you use the ads element in the configuration, you can set the language for the ads and that should do it. See https://github.com/openplayerjs/openplayerjs/blob/master/docs/usage.md#javascript for more info
