### ISSUE TITLE
Error playing video on mobile

### ISSUE THREAD

**Issue by pooryak** [openplayerjs/openplayerjs#301]
when ads is active, the mobile version of player doesn't work and show this error in console : 
GET blob:http://localhost:3000/1107d630-fdff-431d-84e0-e19c37cf062b net::ERR_FILE_NOT_FOUND
warning: [  0.014s] [ima.common.GptCompanionAdService] GPT companion ads service not available. 
The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.
 but in desktop mode, everything happens as expected.
I faced this problem even in demo player at https://www.openplayerjs.com/ with this ad: [https://napi.arvancloud.com/vod/channels/c49885f0-11e3-4f15-b0a4-68392958643b/ads](url)

**Comment by rafa8626** [comment]
@pooryak I wasn't able to reproduce this issue. Check this screenshot from an iPhone, using a very basic cofniguration:

```javascript 
const player = new OpenPlayerJS('video', {
                ads: {
                    src: 'https://napi.arvancloud.com/vod/channels/c49885f0-11e3-4f15-b0a4-68392958643b/ads',
                },
            });
            player.init();
```
<img width="324" alt="Screen Shot 2021-11-14 at 6 01 06 PM" src="https://user-images.githubusercontent.com/910829/141702226-5903bda5-0339-40e6-a006-6dbc5bcd54ea.png">

**Comment by pooryak** [comment]
Thanks for answering,
Please this one 
https://codesandbox.io/s/openplayerjs-nextjs-forked-eeoix?file=/pages/index.js&resolutionWidth=320&resolutionHeight=675

**Comment by pooryak** [comment]
The problem is ad
whenever there is an ad( no matter which kind), on mobile after showing the ad it shows blob error and timeout for the main video
but if I comment ad it works as expected.

**Comment by rafa8626** [comment]
@pooryak sorry for the delay; I’ll try to check this as soon as I can and get back to you. It seems odd that is just on mobile but I have to dig deeper

**Comment by pooryak** [comment]
thanks, I checked it with another ad and player(plyr) it happened again
in firefox I saw this Security Error: Content at http://localhost:3000/post/202111161/%D8%AA%D8%B3%D8%AA may not load data from blob:http://localhost:3000/297f0ec5-faf5-46fc-87e7-6f028e1a6f94.
I see this error on desktop too but it work on desktop anyway

**Comment by rafa8626** [comment]
So what you are saying is that this is not necessarily related to this player?

**Comment by pooryak** [comment]
Yes I checked another player I have this one again

**Comment by rafa8626** [comment]
@pooryak the only thing I can say is that, because localhost is using http and your Ad is https, there's a conflict and it is being reported as a security error. Both protocols must match
