### ISSUE TITLE
localstorage for volume control

### ISSUE THREAD

**Issue by galipmedia** [openplayerjs/openplayerjs#302]
I am wondering if sound levels could be stored in a local storage item so that when a new player is initiated it plays at the level previously set by the user? I am quite certain I could implement this on my side but it could be a nice feature to have. I have seen it before as an optional setting in other player apis.

**Comment by rafa8626** [comment]
Hi @galipmedia; thanks for suggesting this. Currently I’m focused on getting 3.0 completed, but after that I’ll see if it’s a good candidate to be included in the package
