### ISSUE TITLE
HLS Firefox Android

### ISSUE THREAD

**Issue by Bosutike** [openplayerjs/openplayerjs#303]
**Describe the bug**
Simply, the video does not play.

**To Reproduce**
You can go to "https://nazarewaves.com/en/webcams" and check both cameras. Both do not work on Firefox Android.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Android
 - Browser Firefox
 - Version 94.1.2

**Additional context**
I have been doing some debugging and was getting this error while loading the page:
![image](https://user-images.githubusercontent.com/37370053/144896051-e033f8a0-6567-4d7c-8a4f-a242d46e77fc.png)

Furthermore, when play pressed:
Uncaught (in promise) DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable. openplayer.min.js:1

**Comment by rafa8626** [comment]
@Bosutike thanks for reporting this; I’ll check this out. For now, you can use the forceNative as false and see if that works

**Comment by Bosutike** [comment]
@rafa8626 Thanks for your answer. I have added that config on cam 2 here: https://nazarewaves.com/en/webcams. Still doesn't work. :S

**Comment by rafa8626** [comment]
@Bosutike checking your code, I noticed that you set the source as a MP4 MIME type but you are using an HLS resource (which should be a application/x-mpegURL). See if that works

**Comment by rafa8626** [comment]
Also, could you give a star to the repo to show your support to this project, please?

**Comment by Bosutike** [comment]
Thank you for your answer. I have changed the MIME type but it still does not work

**Comment by rafa8626** [comment]
Ok I’ll take a deeper look using an emulator because I don’t own an Android device. I’ll keep you posted about it

**Comment by Bosutike** [comment]
We have done some more testing and we found out that the problem is not with the player.
We have a security implementation that validates a jwt inside a cookie, every time a video resquest is made. When we deactivate this verification, the player works. Although, It's weird that it is only breaking on Firefox Android when active.
We are working on further investigation. If you have any ideas about the problem let me know.
Thanks for your help anyway. 
Great project!

**Comment by rafa8626** [comment]
Thanks for the heads up; although, I’ve never faced an issue like that and I can’t offer any insights about it.
