### ISSUE TITLE
Videos without sound doubt

### ISSUE THREAD

**Issue by utilsites** [openplayerjs/openplayerjs#306]
I would like to know if openplayerjs has a developer option to disable sound (for videos that don't have sound), and using ForceNative = 1.
It was not clear for me after reading the documentation.
This would be good in android for example, because if a person is listening music it stops when playing the video, but maybe if it was configured with no sound, it would not stop the music.
Thanks.

**Comment by rafa8626** [comment]
@utilsites you can use startVolume as zero to mute programmatically video; it will be also helpful to set the video tag’s muted attributed. I hope that helps you; otherwise, let me know.

Please give the project a star to show your support to this player. Thanks!

**Comment by utilsites** [comment]
Thanks for explanation. Star done.
