### ISSUE TITLE
post-roll, not a bug, just a question

### ISSUE THREAD

**Issue by timstoute** [openplayerjs/openplayerjs#318]
This is not a bug, just a question.

Apologies if I missed this in the docs, but how can I set an ad to play post-roll, after the video / audio media completes?

**Comment by rafa8626** [comment]
Hi @timstoute all that is driven by the XML configuration; an example of that is at https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpostonly&cmsid=496&vid=short_onecue&correlator=

That one is configured to be a postroll. If you have any further questions, please let me know, but everything in terms of Ads in that regards has to do with his composition as an XML document
