### ISSUE TITLE
second ad not playing

### ISSUE THREAD

**Issue by virienko** [openplayerjs/openplayerjs#326]
Hello. I already wrote to you before, I see that the problem with the second advertisement has not been resolved. When I enter something like this src: ["https://telecola-sport.com/linear/rafinad.xml", "https://telecola-sport.com/linear/rafinad.xml"]
The following happens: the first video starts, when the first ad ends, the player freezes and that's it.
I am using native XML VAST without google ad service.
You can look at them here:

https://telecola-sport.com/linear/Balviten.xml
https://telecola-sport.com/linear/Lion.xml

You can also check out this demo site. Now I'm using a different player and 3 ads play well.
However, I would really like to switch to your player.
Please, help!)

**Comment by rafa8626** [comment]
@virienko could you post the demo site please? I need to see how are you trying to implement it and see how can I fix it

**Comment by rafa8626** [comment]
@virienko can you test the `v3.0.0` branch and let me know if it worked for you, please?

**Comment by virienko** [comment]
> @virienko can you test the `v3.0.0` branch and let me know if it worked for you, please?

I didn't quite understand what I should do. In my example, I am using the latest version of the player via CDN. Please clarify and I will check. Thank you.

**Comment by rafa8626** [comment]
@virienko download the dist folder from the v3.0.0 branch and rather than using the openplayer.min.js file from the CDN, use the one from that folder

**Comment by virienko** [comment]
Yes, it's work!!I am very grateful for the help!!

**Comment by rafa8626** [comment]
Excellent! This fix will go to the CDN once I deploy that branch. Hopefully by next week this will happen. Thanks for testing it!

**Comment by rafa8626** [comment]
Do you have a project URL with a logo that you could share to include it in my showcase list?

**Comment by virienko** [comment]
The project is still in progress. I can finish it, install your player and contact you. Provide a link to the project with a logo. This will happen in about 2 weeks. 
Where can I write to you so that you understand that it's me? Thanks again

**Comment by rafa8626** [comment]
Thanks, I appreciate it
