### ISSUE TITLE
Blocking google ads service in Russia

### ISSUE THREAD

**Issue by komato3huk** [openplayerjs/openplayerjs#337]
Good afternoon. Is it possible to switch from google ima to another library?

**Comment by rafa8626** [comment]
Hi @komato3huk currently no; the player is only relying on IMA to render ads

**Comment by komato3huk** [comment]
Bad news =(

**Comment by rafa8626** [comment]
I’m working on version 3 and I’ll explore the possibility of using IMA and potentially another service but I’m still defining how can I do thaf. I’m sorry I couldn’t help you on this

**Comment by komato3huk** [comment]
Is it possible to use the local version? IMA

**Comment by komato3huk** [comment]
sdkPath:
And remove in ima3_debug.js
(function() {
    if (!db(function(a) {
      return a.match(J().location.href)
    })) {
      var a = zc();
      if (null == Sa(a, function(a) {
        return db(function(c) {
          return c.match(a.src)
        })
      })) throw Error("IMA SDK is either not loaded from a google domain or is not a supported version.");
    }
  })();

**Comment by foadabdollahi** [comment]
@komato3huk use [https://github.com/basil79/ads-manager](https://github.com/basil79/ads-manager) to manage your ads without google iframe
