### ISSUE TITLE
Video player not working on iOS 15.3+

### ISSUE THREAD

**Issue by utilsites** [openplayerjs/openplayerjs#338]
**Describe the bug**
The video player stopped to work on iPhone Safari from iOS version 15.3+.
We use as video source a .m3u8 playlist with .ts files and they are served correctly on the network, and no error is shown on javascript safari console (connected using macOS), and the video player does not work (only black screen appear).
Using latest openplayerjs version, also tried with older one and don't work.

**To Reproduce**
Use m3u8 video source that uses .ts files, embed iframe with openplayers js and open website on iPhone with iOS 15.3+

**Expected behavior**
Video play does not work.

**Smartphone (please complete the following information):**
 - Device: Iphone 
 - OS: iOS 15.3+
 - Browser: Safari
 - Version: latest

**Comment by rafa8626** [comment]
@utilsites could you provide a CodePen where you illustrate this issue so I can check what’s going on please?

**Comment by utilsites** [comment]
Please check the web cam 1 here for a live test:
https://nazarewaves.com/en/webcams#headercam1

The iframe has a token in url valid for 3 min.

The problem started from iOS 15.3 at least when we noticed, I think iOS
15.0 or 15.1 worked fine and we didn't change anything, so the problem has
to due with iOS updates.

We connected the iphone iOS 15.3 to macOS to check safari console logs, but
no related errors where present, it seems that the stream files are loaded
in the network but a black screen appears on the video player.
Can you confirm if the video player is correctly using iOS native video
playback and not using hls.js?

We also tried to change our server hls stream encoding, bitrate, etc, but
never works on iOS 15.3+ (safari and chrome), it always works on chrome
Android and desktop.

We also tried with clapper and also didn't work, so I was wondering if the
problem has to due with our hls stream that may not comply with some new
iOS requirement?
We use restreamer to serve hls.

With the latest version of openplayerjs it does not work too.

Thanks!

**Comment by rafa8626** [comment]
@utilsites I’ll check it tomorrow; thanks for setting it up: yes, it may be related to the latest iOS version because I haven’t changed anything related to media sources

**Comment by utilsites** [comment]
> @utilsites I’ll check it tomorrow; thanks for setting it up: yes, it may be related to the latest iOS version because I haven’t changed anything related to media sources

Hi @rafa8626, do you have any news?
Thanks

**Comment by rafa8626** [comment]
One thing is advised comes from hls.js

Keep in mind that if the intention is to support HLS on multiple platforms, beyond those compatible with HLS.js, the HLS streams need to strictly follow the specifications of RFC8216, especially if apps, smart TVs, and set-top boxes are to be supported.

**Comment by rafa8626** [comment]
@utilsites there's definitely something wrong with your media. I left it for a little bit and I got this error from the phone. My advise is to check the RFC8216 specs and see if your streams are really complaint, because if it failed in 2 different players, it's a clear indication that either the server or the stream are the problem 
<img width="664" alt="Screen Shot 2022-04-03 at 2 21 59 PM" src="https://user-images.githubusercontent.com/910829/161442445-f9bd7105-3b9e-4e11-93f5-b242ca38b087.png">
e

**Comment by rafa8626** [comment]
@utilsites thanks for the update
