### ISSUE TITLE
Question: using api how can I seek

### ISSUE THREAD

**Issue by timstoute** [openplayerjs/openplayerjs#339]
Using the api, I would like the change / set the progress of the media file (just as the 0 -9 keyboard keys will seek to between 0% to 90% of the media). How can I do this?

**Comment by rafa8626** [comment]
@timstoute you can use a player instance and then retrieve the media element and set the currentTime. So, knowing the duration, I’d do a calculation to know the corresponding percentage and then set it. So, if you key is 1, then duration * 0.1 is the value you will set with playerInstance.getMedia().currentTime.

I hope I explained this in the proper way; if not, let me know.

**Comment by timstoute** [comment]
@rafa8626 - thanks - that worked; here's a codepen: https://codepen.io/timstoute/pen/PoEORQV

**Comment by rafa8626** [comment]
Glad to know it worked!
