### ISSUE TITLE
api playlist

### ISSUE THREAD

**Issue by timstoute** [openplayerjs/openplayerjs#342]
I'm hoping to pass a playlist object to the player and that the player will progress sequentially though the playlist without further code intervention.

I've made a codepen here to illustrate what I'm doing, and seeing. The player inits, loads, and plays the 1st audio track it is passed, but does not proceed to play the second audio track.

https://codepen.io/timstoute/pen/WNdXJrw

I'm assigning the playlist to the player like this:

`this.myPlayer.getMedia().src = [
      { "src": "https://ccrma.stanford.edu/~jos/mp3/Latin.mp3", "type": "mp3" },
      { "src": "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3", "type": "mp3"}
    ];`

**Comment by rafa8626** [comment]
@timstoute the player doesn’t work like that: you have to code that on your own. You can pass multiple sources but that means that you have options to see which one will be played successfully first. What you can do is to dispatch an ended event to set the next source in your list and attempt to autoplay it

**Comment by timstoute** [comment]
ok, thanks, understood
