### ISSUE TITLE
Ability to set watermark

### ISSUE THREAD

**Issue by jpike88** [openplayerjs/openplayerjs#353]
Would be nice to be able to set a watermark on the video element (cover the whole thing, or have a logo in a corner)

**Comment by rafa8626** [comment]
@jpike88 thanks for the suggestion; do you have an example of this to see how this could affect the controls interaction, or similar? This may end up being a separate plug-in

**Comment by rafa8626** [comment]
@jpike88 after reevaluating this, I decided to include a new method that will allow you to set a more generic element into the player. This week I’ll release that new method with a CodePen that allows you to set a watermark to test this.

Thanks for your suggestion, and please give the project a star to show your support

**Comment by rafa8626** [comment]
@jpike88 here's a CodePen that showcases what you need: https://codepen.io/rafa8626/pen/JjLQNjo

I'll release the change next week and remove the unnecessary script from it
