### ISSUE TITLE
One audio music in 2 players (OpenPlayerJS), how?

### ISSUE THREAD

**Issue by johnsmith10000** [openplayerjs/openplayerjs#354]
I'm sorry, I speak a little English.

I would like playing 1 audio file with 2 player in my website. First player in top and the second player in bottom.

How to?

```
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.css" />
    </head>
    <body>

        <div id="top-player">
          <audio class="op-player__media" id="playertop" controls playsinline>
            <source src="/path/to/music.mp3" type="audio/mpeg" />
          </audio>
        </div>

        <div id="bottom-player">
          <audio class="op-player__media" id="playerbottom" controls playsinline>
            <source src="/path/to/music.mp3" type="audio/mpeg" />
          </audio>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.js"></script>

        <script>
            const playertop = new OpenPlayerJS('playertop');
            playertop.init();
            const playerbottom = new OpenPlayerJS('playerbottom');
            playerbottom.init();
        </script>

    </body>
</html>
```

I want different player designs, but the file is the same and the playerbar too.

**Comment by rafa8626** [comment]
@johnsmith10000 thanks for reaching out; if you want to change colors on the player, you can just add a `<styles>` tag after the main CSS styles for the player and customize it, based on the ID you assigned to the player. For example:
```html
<head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.css" />

        <styles>
             #playerbottom {
                    // ... from here, find the styles that you want to override
             }
       </styles>

 </head>
```

Also, if you want to customize the player in terms of positions of elements and such, combine what I just mentioned above with the approach indicated in this CodePen: https://codepen.io/rafa8626/pen/vYGgqRK

Thanks for using OpenPlayerJS, and could you give the project a star to show your support to it, please?

**Comment by JustinWebDev** [comment]
For future readers, I think the tag is "style" (not plural).

**Comment by rafa8626** [comment]
My bad, I didn’t notice about that typo
