### ISSUE TITLE
AddControl (<div> instead of <button>)

### ISSUE THREAD

**Issue by matranovakifanyuvo** [openplayerjs/openplayerjs#358]
Hello,

Please see this:

```javascript
footer_player = new OpenPlayerJS('footer-player', {});
footer_player.addControl({
  icon: '<i class="bi bi-skip-end-fill font-weight-bold text-white"></i>',
  position: 'right'
});
footer_player.init();
```

It works, very nice, but this code only create `<button>` element. Is this changeable? I want to use a `<div>` instead of a `<button>` element.

My dream:

```javascript
footer_player.addControl({
  tag: div
  // etc...
});
footer_player.addControl({
  tag: span
  // etc...
});
```

😇

**Comment by rafa8626** [comment]
@matranovakifanyuvo currently there’s no way to change it but I’ll add it as an enhancement for the next version

**Comment by rafa8626** [comment]
@matranovakifanyuvo this week I’ll push a change where you can use an `addElement` rather than `addControl`; that will allow you to customize the player even more. I hope that helps you :)
