### ISSUE TITLE
How to change the red progress and volume bar colors?

### ISSUE THREAD

**Issue by matranovakifanyuvo** [openplayerjs/openplayerjs#359]
Hello,

<img src="https://i.imgur.com/CE70FwV.png">

How to change the red colors? Progress and volume bars.

**Comment by rafa8626** [comment]
@matranovakifanyuvo you have to override these styles’ color by using a style tag after the player’s style sheet:

`.op-controls .op-controls__progress--played` and `.op-controls .op-controls__volume--display`

Currently, both have a `f00` value for color
