### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by JustinWebDev** [openplayerjs/openplayerjs#361]
**Describe the bug**
various documentation-related issues

1) Need to clarify what "levels" are, wherever it is mentioned.  It took me a while to figure out this is a media quality level.  (Oddly, I had to look in the controls config details to learn this, where it is the _only_ place it is mentioned.)  See [API](https://github.com/openplayerjs/openplayerjs/blob/master/docs/api.md)and [Usage](https://github.com/openplayerjs/openplayerjs/blob/master/docs/usage.md) pages.

2) Usage > defaultLevel: should "numeric ID" be "numeric value"?

3) Usage > "About the levels control" sample [codepen](https://codepen.io/rafa8626/pen/ExxXvZx): might need more explanation.  The sample configuration
`right: ['levels', 'captions', 'settings', 'fullscreen'],`
doesn't seem to translate to the second video because there first two controls don't display.  And, the 'levels' actually show in the settings menu.

4) homepage: YouTube video example [codepen](https://codepen.io/rafa8626/pen/wvvOYpg): the video doesn't work (won't play), does it need to be updated?

5) [Customize](https://github.com/openplayerjs/openplayerjs/blob/master/docs/customize.md): the control layout diagram doesn't match the player.  E.g., the levels codepen sample shows
```
left: ['play', 'time', 'volume'],
middle: ['progress'],
right: ['levels', 'captions', 'settings', 'fullscreen'],
``` 
and the progress bar is above the left and right controls, but the diagram shows middle being in-between the left and right controls (all on the same line).

About the levels codepen sample, I really can't make sense of it.  There seems to be information missing in the player config or the HTML.  The HTML implies level correlates to the two diff sources, but that doesn't happen, either.

PS:  Was the NPM install really updated 37 years ago?  ;-)

**Comment by rafa8626** [comment]
@JustinWebDev thanks for your feedback on this; I’ll make some updates in the documentation to make the levels more clear on what they are and how to use them. 

I tested the YouTube video on my phone and worked properly. Did you test it under a specific browser/device?

The NPM tag is one from a different project, and I can’t seem to obtain it without that typo 😝 I’ll try to update it in the next release for one that is accurate

**Comment by JustinWebDev** [comment]
This is what I see on my Windows desktop using Edge:
![image](https://user-images.githubusercontent.com/40804543/186530712-7469d07b-a0e1-4b11-94e2-a8ed980aadfb.png)

If you poke the OpenPlayerJS button on the video image, nothing happens.  I you poke the play control button, it toggles to pause but the video does not play.

**Comment by rafa8626** [comment]
Ok I’ll check this on Edge since in Chrome and Safari this works for me

**Comment by rafa8626** [comment]
@JustinWebDev this seems to be a unique issue for Edge due to Privacy policies in the browser; YouTube sets trackers and those are blocked by default in newer versions of Edge. This is something I have to investigate more and see if there's any solutions on code that I can implement, since I depend on YouTube API for this. I have addressed the rest of the items you listed here, so feel free to check them and let me know if you are good with them so I can release them next week. As always, thanks for using OpenPlayerJS

**Comment by rafa8626** [comment]
@JustinWebDev I fixed the issue but due to some policies, I have to mute the video for Chrome and Edge, but that seemed to work. Thanks again for reporting this.

**Comment by JustinWebDev** [comment]
Follow-up:
"For HTML5 elements, you MUST have at least two different sources inside the video/audio tag and each MUST include a _unique_ title, **that in turn must be unique as well**."  Redundant?

Look at this https://github.com/openplayerjs/openplayerjs/blob/master/docs/usage.md#configuration-options all jumbled up.

I don't see any diff for the image in https://github.com/openplayerjs/openplayerjs/blob/master/docs/customize.md#modify-look.  Middle goes full-width above left and right in the player, but the image doesn't show that.

**Comment by rafa8626** [comment]
@JustinWebDev I didn’t change any images because in the end I made a note about the layers and how they are when we set top and bottom.
I’ll make the correction in a bit. Thanks for noticing it

**Comment by rafa8626** [comment]
@JustinWebDev just made the change for it

**Comment by JustinWebDev** [comment]
usage.md:  Is this description text correct?
![image](https://user-images.githubusercontent.com/40804543/187310591-d6d766a9-81e6-4223-b968-b9fdd8a0e872.png)

Sorry for being dunce, but how does a note about top and bottom controls explain how left-middle-right is not as shown in the diagram?  After playing with your codepen, it looks like the progress control is treated in a special way.  Maybe you need a note about that to clarify things?

**Comment by rafa8626** [comment]
@JustinWebDev I’ll add the note about CSS modifying the look of the progress bar but semantically it’s in the middle. I’ll add that later today

**Comment by JustinWebDev** [comment]
Well, compare this:
```
left: ['play', 'time', 'volume'],
        **middle: ['progress'],**
        right: ['levels', 'captions', 'settings', 'fullscreen'], 
```
![image](https://user-images.githubusercontent.com/40804543/187544433-863fc7a0-cce8-4b51-bbd1-4c71b2efb6e1.png)

to this:
```
left: ['play',  'volume'],
        **middle: ['time'],**
        right: ['levels', 'captions', 'settings', 'fullscreen'], 
```
![image](https://user-images.githubusercontent.com/40804543/187544517-db57f84a-9a66-49b9-bf90-70bed348e210.png)

The second reflects the diagram depiction (though one may argue that 'middle' should also be centered between left and right).  Same syntax, but different control, yet different layout.

**Comment by rafa8626** [comment]
@JustinWebDev I added a new section to explain this and some other details; let me know if that works

**Comment by JustinWebDev** [comment]
Yep.  Thanks for the attention.
