### ISSUE TITLE
Error Event Leaks even though the playererror event listener is attached.

### ISSUE THREAD

**Issue by afkcodes** [openplayerjs/openplayerjs#364]
**Describe the bug**
The player logs the error event though the playererror event listener is attached, ideally the player should log the errors when the error event is attached and should not leak it. The playererror events should capture all the events once its defined. 

**To Reproduce**
attach event listener to the player and wait for the error to happen it will be logged in the event handler as well as outside of that.

**Expected behavior**
The playererror events should capture all the events once its defined. 

**Screenshots**

![Screenshot 2022-08-31 at 11 16 06 AM](https://user-images.githubusercontent.com/17390257/187603149-7568b1f2-fd03-49cb-b13b-7cefce47b76d.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version Latest

**Comment by rafa8626** [comment]
@afkcodes can you provide me a CodePen where I can see this in action? I need to determine why are you seeing this

**Comment by afkcodes** [comment]
sure @rafa8626 was out the whole day will try to make a repro and will update it here

**Comment by afkcodes** [comment]
@rafa8626 This is the codebase: https://github.com/afkcodes/radio_india
and this is the output: https://indiafm.vercel.app

**Comment by rafa8626** [comment]
@afkcodes is there any stream that I have to click on in particular to reproduce the issue?

**Comment by afkcodes** [comment]
no just do a random click on some of the streams and see the console.

**Comment by rafa8626** [comment]
@afkcodes I can't see what you described, I can see only a playererror event
<img width="1485" alt="Screen Shot 2022-09-07 at 9 51 36 AM" src="https://user-images.githubusercontent.com/910829/188895576-ae020ce0-597d-4679-9fdc-1dd4344b4592.png">

**Comment by afkcodes** [comment]
will recheck this @rafa8626

**Comment by rafa8626** [comment]
Closing this since more than 7 days of inactivity had passed. If this issue is still valid, we’ll reopen it. Thanks

**Comment by afkcodes** [comment]
Thanks i was not able to reproduce at my side again will update if it happens again @rafa8626
