### ISSUE TITLE
ES6/AMD *.default is not a constructor

### ISSUE THREAD

**Issue by geichelberger** [openplayerjs/openplayerjs#366]
**Describe the bug**

Since version 2.10, I get the following error `Uncaught TypeError: _openplayer.default is not a constructor`, version 2.9.4 is working fine.

**To Reproduce**
```
import OpenPlayer from 'mod_livestream/openplayer';
...
const player = new OpenPlayer('player', {
```
Looking at the debugger, you can see that default is undefined, which was not the case in version 2.9.4.
![grafik](https://user-images.githubusercontent.com/35195803/190593106-f593e126-95ae-4251-9289-864251ce8567.png)

**Additional context**
We are embedding the player in a Moodle Plugin where all the ES6 syntax is converted into an AMD syntax.

**Comment by rafa8626** [comment]
@geichelberger thanks for bringing this up; I’ll check what changed in the configuration.

Can you give the project a star to show your support please?

And if your project is live, could you provide me a url and a logo so I can showcase it in the oncoming 3.x.x versión please?

Thanks

**Comment by rafa8626** [comment]
@geichelberger I checked your screenshot again; we deprecated OpenPlayer in favor of OpenPlayerJS. Can you try that and let me know if that works for you?

**Comment by geichelberger** [comment]
I tried that already. It makes no difference. Isn't that just a name you can define that will refer to the module's default export?

**Comment by rafa8626** [comment]
You are totally right. I was thinking more in terms of the global variable available in the browser. I’ll check the configurations and see what changed. Also, do you have a CodePen where I can see the issue?

**Comment by geichelberger** [comment]
ES6 in codepen is working  🙈 maybe its caused by the AMD part, the ES6 syntax gets translated into an AMD syntax, thats the result:

```
define("mod_livestream/loader", ["exports", "mod_livestream/openplayer", "mod_livestream/hls"], (function (_exports, _openplayer, _hls) {
    function _interopRequireDefault(obj) {
        return obj && obj.__esModule ? obj : {default: obj}
    }

    Object.defineProperty(_exports, "__esModule", {value: !0}), _exports.init = _exports.default = void 0, _openplayer = _interopRequireDefault(_openplayer), _hls = _interopRequireDefault(_hls);
    var init = function () {
        window.Hls = _hls.default, new _openplayer.default("player", {
            controls: {layers: {left: ["play", "time", "volume"], middle: [], right: ["fullscreen"]}},
            forceNative: !1,
            hidePlayBtnTimer: 500,
            live: {showLabel: !0, showProgress: !1},
            hls: {capLevelToPlayerSize: !0, nudgeMaxRetry: 180, nudgeMinRetry: 5, maxLiveSyncPlaybackRate: 1.1, liveDurationInfinity: !0}
        }).init()
    };
    _exports.init = init;
    var _default = {init: init};
    return _exports.default = _default, _exports.default
}));
```

**Comment by rafa8626** [comment]
Did you post the CodePen? I’d like to use it when I review the issue and verify it works as expected

**Comment by rafa8626** [comment]
@geichelberger I made one commit that may fix your issue; please download the latest version of master and let me know if it works for you

**Comment by rafa8626** [comment]
No, something is still not right. I need to check the Webpack configuration to determine where is it broken

**Comment by rafa8626** [comment]
@geichelberger please download the master branch and test it; I figured out what was the problem: the configuration changed for Webpack 5 and the name of the library was not complaint to what is expected. Once I changed the name and adapted the configuration to generate a library, the default is generated correctly. Thanks for reporting this

**Comment by geichelberger** [comment]
Sorry, I was busy the last few days. I can confirm it's working again. Thank you!
Our Logo is already present in the README.

**Comment by rafa8626** [comment]
Great! Thanks again for reporting this.
I’ll deploy this tomorrow
