### ISSUE TITLE
Question: How to destroy player ?

### ISSUE THREAD

**Issue by pd-pranay** [openplayerjs/openplayerjs#367]
How to delete player instance after ad is done playing ? @rafa8626

**Comment by rafa8626** [comment]
@pd-pranay you can use an event for it: `adsallAdsCompleted`. So, as an example:

```javascript
const player = new OpenPlayerJS(‘video’);
player.init();

player.getElement().addEventListener(‘ adsallAdsCompleted’, player.destroy);
```

That event will execute once all the ads in your XML are executed.

Thanks for using this player!

**Comment by pd-pranay** [comment]
Thanks, also [#240](https://github.com/openplayerjs/openplayerjs/issues/240) is this the only way to handle outstream ads ?

**Comment by rafa8626** [comment]
Yes, for now. I’ll explore other alternatives in the near future

**Comment by pd-pranay** [comment]
> Yes, for now. I’ll explore other alternatives in the near future

Thanks for mentioning,
I'm not able to destroy player instance, here's my code pen link [CodePen](https://codepen.io/pd_pranay/pen/rNvdvPY)
can you have a look ?

**Comment by rafa8626** [comment]
Yeah I’ll check it and get back to you

**Comment by rafa8626** [comment]
@pd-pranay the error was in how the event was defined; it should be this way
```javascript
player
          .getElement()
          .addEventListener("adsallAdsCompleted", () => {
          player.destroy();
        });
```
I tested it and that way the player is destroyed

**Comment by pd-pranay** [comment]
> Hi @rafa8626 I have tried this with the same [CodePen](https://codepen.io/pd_pranay/pen/rNvdvPY) above but didn't work . Can you please have a look into it. Also thanks for the support.
My end goal is to dispose / destroy the player when adsallAdsCompleted or the video ends.

**Comment by rafa8626** [comment]
@pd-pranay I tested your CodePen in a Mac laptop (enabling and disabling the AdBlocker) and I can see it working in both scenarios
<img width="1510" alt="Screen Shot 2022-10-03 at 11 23 39 AM" src="https://user-images.githubusercontent.com/910829/193615634-e3609b4d-824f-4dcf-ae0a-1a4b1523238c.png">
<img width="1511" alt="Screen Shot 2022-10-03 at 11 23 59 AM" src="https://user-images.githubusercontent.com/910829/193615642-8aa607e1-0be6-479c-b222-a6be614e284f.png">

**Comment by rafa8626** [comment]
The destroy method just destroys the player instance but not the video tag itself; you need to do that on your own

**Comment by pd-pranay** [comment]
oh okay, my bad thanks for the help.

**Comment by pd-pranay** [comment]
by any chance do you have vpaid ad script that works well with this player ? 
SImilar to [this](https://github.com/ryanthompson591/vpaidExamples/blob/master/playVideo/VpaidVideoAd.js)

**Comment by rafa8626** [comment]
I believe this is what IMA SDK uses: https://github.com/googleads/googleads-ima-html5/blob/main/vpaid/linear/VpaidVideoAd.js

**Comment by pd-pranay** [comment]
> I believe this is what IMA SDK uses: https://github.com/googleads/googleads-ima-html5/blob/main/vpaid/linear/VpaidVideoAd.js

Thanks very much
