### ISSUE TITLE
Playback is blocked on iOS when ads are loaded dynamically 

### ISSUE THREAD

**Issue by DamianDugan** [openplayerjs/openplayerjs#368]
**Describe the bug**
If ads are both loaded and played dynamically through the loadAd / getAd.play() methods, the playback gets blocked on iOS and I get the following error :
AdError 1205: The browser prevented playback initiated without user interaction.

**To Reproduce**
1. Set a media src for the player
2. When the user clicks on the play button, use the loadAd method, providing an XML string coming from an async source. A setTimeout of 1000ms with a hardcoded VAST XML string is enough to reproduce the bug
3. use the Player.play() or the getAd.play() methods to play the ad
4. See IMA debug warning concerning AdError 1205

**Expected behavior**
The player should be able to bypass iOS "autoplay" restrictions, either through the use of AudioContext API or the autoplay attribute.

**Screenshots**
![image](https://user-images.githubusercontent.com/45030994/193874810-609bd5e2-1435-4c63-aa23-e0c8a5c1cdb2.png)

**Smartphone :**
 - OS: iOS
 - Browser: Safari
 - Version : 2.11.0 and up

**Additional context**
I've also noticed that the player doesn't seem to behave properly when it is given an empty VAST response such as :
`<VAST version="2.0"/>`
Both of our ad providers will occasionally return that from their API.

**Comment by rafa8626** [comment]
@DamianDugan I don’t think there’s much I can do about it since the error itself it’s pretty clear: the user must perform an action before playing the ads. This goes hand in hand with the browser’s autoplay policies and that can’t be bypassed. Even autoplay is discouraged in many situations now

**Comment by rafa8626** [comment]
@DamianDugan what’s the issue with the empty xml tag, just so I can check it and determine how to handle it?

**Comment by DamianDugan** [comment]
Thank you for such a quick answer.

I'm not advocating for actually autoplaying the audio, in my example the ads would be played after the user clicks on the play button.

The problem with Safari / iOS is that the getAd.play() method has no relation or context that binds it to the play button as far as i'm aware. Providing context through the WebAudio API might be a solution for playback that gets interrupted.

Examples can be found here: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/resume

Regarding the empty xml tag, I haven't been able to reproduce the problem, i'll keep you posted if I do.

**Comment by rafa8626** [comment]
If you can give me a CodePen where I can see your implementation to check what can I do to help, I’d appreciate it

**Comment by rafa8626** [comment]
@DamianDugan thanks for the CodePen; I’ll try to check this during the week. I’ve been busier than usual, but I’ll keep you posted

**Comment by DamianDugan** [comment]
Did you have a chance to take a look at it ?

**Comment by rafa8626** [comment]
Not yet; I’ll try to check this today

**Comment by rafa8626** [comment]
@DamianDugan please download the master branch and let me know if the changes I made will work for your case

**Comment by rafa8626** [comment]
@DamianDugan sorry if I misunderstood the issue. I actually moved the code to the play button, rather than the play event. See if that works for you. Otherwise, I’ll wait for your example this week

**Comment by DamianDugan** [comment]
https://codepen.io/rafa8626/pen/OJZBvYN

Is it still this codepen ? If so i still see the event listener on the "play" event rather than "click" on play button.

**Comment by rafa8626** [comment]
@DamianDugan the CDN has the previous version cached. Please download the master branch and test it on your side. The workaround is now on the button

**Comment by DamianDugan** [comment]
I've tested the master branch, it seems like my idea of adding the autoplay attribute was unsuccessful, feel free to revert the changes.

I have a reproduction of the bug but it contains sensitive info that i'm not willing to share publicly. Is there any private channel I could use to reach you ?

**Comment by rafa8626** [comment]
You can email me directly: rafa8626@gmail.com. I’ll delete this comment once you reach out

**Comment by rafa8626** [comment]
@DamianDugan closing this for now; after your tests, if it’s still present I’ll reopen it
