### ISSUE TITLE
Keeping the volume level

### ISSUE THREAD

**Issue by supersh86** [openplayerjs/openplayerjs#37]
Hi Rafa!
Recently, many of my users complain about the problem with adjusting the volume.
Youtube usually keeps the volume in cookies, can you do it in your player?

**Comment by rafa8626** [comment]
Hey, generally speaking, that feature is implemented in the whole website ecosystem. The player is just part of the ecosystem, so that's why I wouldn't include it. However, I can include an option to set the initial volume, and you could use your own implementation of storage to set that value.

Does it sound reasonable?

**Comment by supersh86** [comment]
Yes you are right.

I have another question, is it possible to change the source of the video, after player initialization?

player.load () does not work ((

**Comment by rafa8626** [comment]
You just set the source and that does it. Check the demo file that has that option

**Comment by supersh86** [comment]
Rafa, just noticed a critical problem.
On, ipad neither in safari, nor in chrome, the player does not work with VAST.

https://www.openplayerjs.com/embed.html?file=https%3A%2F%2Fcdn100.anivid.tk%2Fvid2%2Fs1%2F10586%2F1%2F1.mp4%2Fplaylist.m3u8&type=video&ads=https%3A%2F%2Fmoevideo.biz%2Fvast%3Fref%3Donline.anidub.com%26impressionAfterPaid%3D1%26es%3D1

**Comment by rafa8626** [comment]
Ok I’ll check that and implement the volume setting we talked about and let you know. Thanks for noticing that

**Comment by supersh86** [comment]
Hello
1 startVolume is the setting for player initialization?
2 Iphone lost control menu. I can not go full screen.

**Comment by supersh86** [comment]
https://www.openplayerjs.com/embed.html?file=https%3A%2F%2Fcdn100.anivid.tk%2Fvid2%2Fs1%2F10586%2F1%2F1.mp4%2Fplaylist.m3u8&type=video

**Comment by rafa8626** [comment]
The main website is using the old version still since I haven’t released any change. Just check the master branch and if you still have the issue give me a CodePen to replicate please

**Comment by rafa8626** [comment]
@supersh86 I have updated the master branch since I found out something missing to display Ads correctly but it's working now. Once you confirm, I'll create the new release. Thanks
