### ISSUE TITLE
DRM Support for FairPlay

### ISSUE THREAD

**Issue by EastSun5566** [openplayerjs/openplayerjs#370]
Hi OpenPlayerjs team,

Just want to quickly ask does the player support HLS with FairPlay?

Thanks for your help!

**Comment by rafa8626** [comment]
@EastSun5566 do you have an example
To test if the player can play it?

**Comment by EastSun5566** [comment]
Hi @rafa8626, 

After I dig into the source code a little bit. I found out you use hls.js internally.
Unfortunately, hls.js [does not support FairPlay](https://github.com/video-dev/hls.js/#not-supported) yet.

Thanks for the quick response! I will close the issue.

**Comment by rafa8626** [comment]
@EastSun5566 you are welcome. Could give this project a star to show your support, please?

**Comment by EastSun5566** [comment]
@rafa8626 I already starred it 😊

**Comment by rafa8626** [comment]
Thanks :)
