### ISSUE TITLE
Volume slider class never added if it's mobile view?

### ISSUE THREAD

**Issue by Jurugi** [openplayerjs/openplayerjs#372]
When initialized in mobileview, volume/mute is never added. 
Using Firefox, developer tools.

**Comment by Jurugi** [comment]
Fixed,
line         if ((!IS_ANDROID && !IS_IOS) || !this.#player.getOptions().useDeviceVolume) {
or search useDeviceVolume in the minified version, then remove it or replace that area with p||!p insteadof !p||!v||.useDeviceVolume. It is faulty code that doesn't append volume option if it's mobile IOS or Android.

**Comment by rafa8626** [comment]
@Jurugi thanks for the heads up; I’ll fix this in the oncoming version. Please give a star to the project to show your support

**Comment by Jurugi** [comment]
Yep I didn't notice yet. I did run into problems but some actually are options added or can be fixed 1 or 2 ways. So you can do the fix my way, also there is:
useDeviceVolume option, set it to false and maybe that will of course work.
pauseOthers option, set it to false if you have 3 or more streams and want them all to play.
Controls option did not work at all for some reason, using the example or any other way. But I just added css to hide certain parts as it's not a big issue.
When adding <script>openplayer.js</script> on the top, it for some reason messed up and deleted css/designs, but adding it on the bottom worked for some reason.
Otherwise I gave star, it's actually working and it's a good solution if you have videos/stream elements, and just want to initialize them without making new divs/player of your own and add certain things like volume etc, as you can't modify default browser controls. Just call the init function on each ID of the videos or streams you spawned in, add options as needed.
It's good probably better than video.js, as the styling on that did not even work right anyway and all I wanted was to add a simple option like volume for streams etc. so this is a good option. Just wanted to add notes of things I ran into yesterday.
