### ISSUE TITLE
Can it repeat sentences (1/2/3/4 per sentence) according the lrc/srt subtitles?

### ISSUE THREAD

**Issue by bk111** [openplayerjs/openplayerjs#373]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Can it repeat sentences (1/2/3/4 per sentence) according the lrc/srt subtitles?

**Describe alternatives you've considered**
mp3 repeater

**Additional context**

**Comment by rafa8626** [comment]
@bk111 no that’s a feature that I wasn’t aware of. Do you have any links I could use to check how that could be implemented and, with that, decide how complex would be to implement?

**Comment by bk111** [comment]
for example:
00:00:01  --> 00:00:10
sentence1
00:00:15  --> 00:00:26
sentence2
00:00:33  --> 00:00:54
sentence3

normally, it plays sentence1, then sentence2, then sentence3.
Can you add an option to repeat it X times for every sentences? (  X(2) times, then play sentence1, sentence1,then sentence2, sentence2,then sentence3,sentence3...)

**Comment by bk111** [comment]
> for example: 00:00:01 --> 00:00:10 sentence1 00:00:15 --> 00:00:26 sentence2 00:00:33 --> 00:00:54 sentence3
> 
> normally, it plays sentence1, then sentence2, then sentence3. Can you add an option to repeat it X times for every sentences? ( X(2) times, then play sentence1, sentence1,then sentence2, sentence2,then sentence3,sentence3...)



> 



> @bk111 no that’s a feature that I wasn’t aware of. Do you have any links I could use to check how that could be implemented and, with that, decide how complex would be to implement?

for example:
00:00:01 --> 00:00:10
sentence1
00:00:15 --> 00:00:26
sentence2
00:00:33 --> 00:00:54
sentence3

normally, it plays sentence1, then sentence2, then sentence3.
Can you add an option to repeat it X times for every sentences? ( X(2) times, then play sentence1, sentence1,then sentence2, sentence2,then sentence3,sentence3...)
