### ISSUE TITLE
Subtitle (caption) not work.

### ISSUE THREAD

**Issue by Dacogetul** [openplayerjs/openplayerjs#390]
**Describe the bug**
I used standard template in html file and add path's for .mp4 and .vtt files. 

**To Reproduce**
After open html file, i start the video and working without subtitle. 
After puch CC button it turned in red color but nothing happend. My subtitle not loading.

Standard template :  
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.css" />
    </head>
    <body>
        <video class="op-player__media" id="player" controls playsinline>
            <source src="mypath/video.mp4" type="video/mp4" />
            <track kind="subtitles" src="mypath/video.vtt" srclang="en" label="English" />
        </video>
        <script src="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.js"></script>
        <script>
            // Check the `API and events` link below for more options
            const player = new OpenPlayerJS('player');
            player.init();
        </script>
    </body>
</html>

**Comment by rafa8626** [comment]
@Dacogetul you need to check if the file is having CORS issues. Even when the player attempts to load them in a different way to bypass CORS, I've seen that it can be blocked still by that. So, check that first and let me know if that's the cause. If so, you need to make sure your files don't have CORS

**Comment by Dacogetul** [comment]
I open html files from some folder on my desktop: html, mp4 and vtt not from server.

**Comment by rafa8626** [comment]
@Dacogetul in order to troubleshoot this, I will need a CodePen or URL where you reproduce the error

**Comment by Dacogetul** [comment]
https://codepen.io/Dragos-Brojbeanu/pen/ZEVOGap

**Comment by rafa8626** [comment]
@Dacogetul I can see the subtitles, the thing is that they are not turned on automatically. If you want that, you need to set one of the tracks as `default` by setting that keyword as part of the track tag attributes. In order to see the other languages, you need to check the settings icon and you will see them listed. But again, if they are off, you will never see them (see how the Captions button is red, rather than gray)
<img width="945" alt="Screenshot 2023-08-31 at 8 42 09 AM" src="https://github.com/openplayerjs/openplayerjs/assets/910829/fd4a92c5-5992-4221-a35c-814d9af61a69">

**Comment by Dacogetul** [comment]
And how can i see caption tracks settings icon?

**Comment by rafa8626** [comment]
<img width="571" alt="Screenshot 2023-08-31 at 8 50 06 AM" src="https://github.com/openplayerjs/openplayerjs/assets/910829/ef36175c-3ec5-46a1-9877-6d3efbc9585e">

**Comment by Dacogetul** [comment]
OK...Thank you Now I realized that the settings of the subtitles are made from the gear wheel.

**Comment by Dacogetul** [comment]
Thank you again

**Comment by rafa8626** [comment]
You are welcome; please consider giving the project a star to support it :)

**Comment by Dacogetul** [comment]
I already did it !!! Thank you very much!!!!
