### ISSUE TITLE
Settings not work online

### ISSUE THREAD

**Issue by Dacogetul** [openplayerjs/openplayerjs#391]
I published the standard script with two subtitles, but the settings do not appear after pressing the gear wheel, but only 2 arrows. Is it possible to interfere with another js script?
See here for more details and script: [http://test.workpage.ro](url)

**Comment by rafa8626** [comment]
@Dacogetul you have malformed HTML, because I see 2 `html`, `body` and `head` tags in your markup. Remove those and make sure the OpenPlayerJS stylesheet is in the head of the document.

**Comment by Dacogetul** [comment]
I fixed the problem with html but it still doesn't work....

**Comment by rafa8626** [comment]
@Dacogetul your index.css file is conflicting with the OpenPlayerJS styles: you have a style where font-size is equal to 0, and that's what's causing your issue
