### ISSUE TITLE
Change play icon

### ISSUE THREAD

**Issue by polman4** [openplayerjs/openplayerjs#397]
Hello,

Thank you for the great project.

I'm trying to change the play button. I managed to do this with the following

`		  .op-controls__playpause::before{
			content: url("/_img/jplayer.play.png");
		  }`

Even though this worked, when i click play, it doesn't change to the "pause" icon, which is "logical". What's the correct way to do it?

Also when i run a vast ad, is there a way to show that an ad is running?

Thank you!

**Comment by rafa8626** [comment]
@polman4 thanks for using this project! The proper way to achieve this is by using that selector and also the `op-controls__playpause--pause:before` selector so the pause button changes as well. As per the Ad question, you can instantiate the player and then do something like
```javascript
const player = new OpenPlayerJS();
let isRunningAd = false;
player.getElement().addEventListener(‘adsstart’, () => { isRunningAd = true; });

player.getElement().addEventListener(‘adscomplete’, () => { isRunningAd = false; });

```

Let me know if that works for you, and please give the project a star to show your support 🙂
