### ISSUE TITLE
Add alt attribute to addControl api

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#398]
Hi,
please add "Alt" attribute to  `addControl`

```
export interface ElementItem {
    readonly icon?: string;
+    readonly alt?: string;
    readonly title?: string;
    readonly id: string;
    readonly showInAds: boolean;
    position: 'right' | 'left' | 'middle' | string;
...

```

and 
controls.ts
`   ? `<img src="${sanitize(item.icon)}" alt="${sanitize(item.alt??item.id)}">``

Best

**Comment by rafa8626** [comment]
@foadabdollahi I have added it; let me know if it worked for you. Thanks

**Comment by foadabdollahi** [comment]
thanks @rafa8626  but alt attribute added in api but in rendering img has not alt attr.
 because i add button type with icon (svg ) and it work only for img type. it must work for svg and image 
 
![image](https://github.com/openplayerjs/openplayerjs/assets/13816403/ead73901-f17b-4bb5-ad72-3c00c18b107c)

**Comment by rafa8626** [comment]
@foadabdollahi got it. I’ll check this and release a patch for it later today

**Comment by foadabdollahi** [comment]
@rafa8626  Yes it work right. Thanks
