### ISSUE TITLE
reduce css file size

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#401]
i checked css file and it contain some base64 svg icons.
but svg icons has some comment and  this icons convert with base64 with this comments 
for example:

```
.op-controls__playpause:before {
    content: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDI0LjMuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCAzNSAzNSIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgMzUgMzU7IiB4bWw6c3BhY2U9InByZXNlcnZlIj4KPHN0eWxlIHR5cGU9InRleHQvY3NzIj4KCS5zdDB7ZmlsbDojRkZGRkZGO30KPC9zdHlsZT4KPHBhdGggY2xhc3M9InN0MCIgZD0iTTMxLjEsMTYuMmMwLjcsMC4zLDEsMSwwLjcsMS43Yy0wLjEsMC4zLTAuNCwwLjYtMC43LDAuN0w1LDM0LjdjLTEuMSwwLjctMiwwLjItMi0xLjFWMS40YzAtMS4zLDEtMS44LDItMS4xCglMMzEuMSwxNi4yeiIvPgo8L3N2Zz4K);
}
```
raw text :

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 24.3.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 35 35" style="enable-background:new 0 0 35 35;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#FFFFFF;}
</style>
<path class="st0" d="M31.1,16.2c0.7,0.3,1,1,0.7,1.7c-0.1,0.3-0.4,0.6-0.7,0.7L5,34.7c-1.1,0.7-2,0.2-2-1.1V1.4c0-1.3,1-1.8,2-1.1
	L31.1,16.2z"/>
</svg>
```

it can be optize like this:

![image](https://github.com/openplayerjs/openplayerjs/assets/13816403/755b1e69-f9b3-49bf-b2f6-744e0a47ae6b)

after remove this comment and convert it again:

it can be optize like this:
```

<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1"  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 35 35" style="enable-background:new 0 0 35 35;" xml:space="preserve">
<path fill="#FFFFFF" d="M31.1,16.2c0.7,0.3,1,1,0.7,1.7c-0.1,0.3-0.4,0.6-0.7,0.7L5,34.7c-1.1,0.7-2,0.2-2-1.1V1.4c0-1.3,1-1.8,2-1.1
	L31.1,16.2z"/>
</svg>
```
removing:  id , class, style and comment

`url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPHN2ZyB2ZXJzaW9uPSIxLjEiICB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCIKCSB2aWV3Qm94PSIwIDAgMzUgMzUiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDM1IDM1OyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+CjxwYXRoIGZpbGw9IiNGRkZGRkYiIGQ9Ik0zMS4xLDE2LjJjMC43LDAuMywxLDEsMC43LDEuN2MtMC4xLDAuMy0wLjQsMC42LTAuNywwLjdMNSwzNC43Yy0xLjEsMC43LTIsMC4yLTItMS4xVjEuNGMwLTEuMywxLTEuOCwyLTEuMQoJTDMxLjEsMTYuMnoiLz4KPC9zdmc+)`

549 byte to 390 byte ~28% improve

you can do this for all svg in css file

**Comment by rafa8626** [comment]
@foadabdollahi great suggestion! I'll do this as part of the oncoming patch. Thanks!

**Comment by rafa8626** [comment]
@foadabdollahi I just pushed my changes in master but haven't released them yet. If you can install the branch on your side and verify this I'd appreciate it

**Comment by foadabdollahi** [comment]
@rafa8626 i check it. and it is fine. 
thanks
