### ISSUE TITLE
HLS has problem

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#403]
Hi again,

Something wrong is in my site after last update.
hls file was not play and show error "GET blob:https://nashrin.com/068f6a76-2c9a-4a3d-b69c-f786a1c39fe0 net::ERR_FILE_NOT_FOUND" but  "https://vfd.nashrin.com/0r56/playlist.m3u8" was exist and it worked before update?
do you have any idea about this issue?

you can check ir on this page https://nashrin.com/v/0r56

**Comment by foadabdollahi** [comment]
it is weird. when i remove VAST ads it work fine

**Comment by foadabdollahi** [comment]
Yes i pretty sure about it

**Comment by rafa8626** [comment]
@foadabdollahi I tested it without ads and worked for me

**Comment by foadabdollahi** [comment]
@rafa8626 Please test it with ads config.
in issue #399 I sent player config with ads.

**Comment by rafa8626** [comment]
@foadabdollahi I tested the configuration with and without ads and, although it took a little bit for the ad to play, both worked just fine for me. I was able to see the HLS streaming as expected.

**Comment by foadabdollahi** [comment]
@rafa8626  Thanks so much

I think it was for google sdk.
Google ban some feature in Iran and it can make this issue.

I will try find some solution to use an opensource Vast-ads povider.

**Comment by foadabdollahi** [comment]
@rafa8626 i'm sorry. i know you response about this issue. but i found some new evidence. 
when i set preload="auto" or autoplay it work fine 
but when preload is 'metadata'   it got error.
and when preload is  'none ' it has time base (if i click on play button less than 2s it work fine. and after 2s it has error ). i think before 2s ads component was not load.

and when i set  preload='none'  without ads. hls not work and has error : ncaught (in promise) TypeError: Cannot read properties of undefined (reading 'play')    at Media.eval (media.js:106:109)

i think issue come from metadata

**Comment by rafa8626** [comment]
@foadabdollahi you are right: the `none` preload makes it fail, but not `metadata`.  I applied a patch in the master branch, so if you could test it and let me know if it worked for you, I'd appreciate it. Thanks for noticing this

**Comment by foadabdollahi** [comment]
@rafa8626  Thanks . The issue about none was fix.
but the ads and hls has issue yet.

i saw 
other think about rendering
 
without ads config: (Correct)
![image](https://github.com/openplayerjs/openplayerjs/assets/13816403/08eb9af4-81c3-4736-a011-94a0a877d95e)

with ads config: (Error not found resource)
![image](https://github.com/openplayerjs/openplayerjs/assets/13816403/e93d6538-aef1-4faa-8b38-2ff151251deb)



maybe it can help to find issue!

**Comment by rafa8626** [comment]
@foadabdollahi I tested your configuration using Ads with a different VAST URL and worked as expected; test it with `https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/single_ad_samples&sz=640x480&cust_params=sample_ct%3Dlinear&ciu_szs=300x250%2C728x90&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=`; if it works for you, it means that your VAST may be the problem

**Comment by foadabdollahi** [comment]
@rafa8626 Thank you so much.

Yes you are right. it work with your vast. I will continue this issue with vast provider.

Best wishes

**Comment by rafa8626** [comment]
@foadabdollahi sounds good; thanks for reporting this! I'll release the new version today
