### ISSUE TITLE
loop playback: spinner is permently visible

### ISSUE THREAD

**Issue by catkrahl** [openplayerjs/openplayerjs#405]
**Describe the bug**
* when i activate loop-playbay, the loading animation (spinner) is permanently visible

**To Reproduce**
1. loop-playback of HLS-streams via video-tag with loop as parameter
2. when the video starts again, the spinner is permanently visible

**Expected behavior**
* the aria-hidden-flag of the op-player__loader-class should be set to "true" after the next loop of the videoplayback, so the span containing the spinner is hidden via CSS 

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Browser: FF 
 - Version: 122.0 (64-bit)

**Comment by rafa8626** [comment]
@catkrahl could send me a CodePen/URL where I can see the issue? Generally the loader should disappear, unless there are events being fired that cause this, but I wanna verify if this is the case or there's another issue that it's not that evident

**Comment by rafa8626** [comment]
@catkrahl thanks, I’ll take a look at it and get back to you

**Comment by catkrahl** [comment]
[like]  Christoph Krahl reacted to your message:
________________________________

**Comment by rafa8626** [comment]
@catkrahl sorry for the delay; I tested it on FF and I wasn't able to reproduce the issue at all. All ran smoothly on my end. I tried on Chrome as well, and the video ran correctly. I'm not sure what's the difference here, other than you are using Ubuntu, and I'm using Mac.

**Comment by rafa8626** [comment]
Closing this issue. If you can reproduce it or you would like to be reopened, let me know
