### ISSUE TITLE
Subtitle problems...

### ISSUE THREAD

**Issue by Dacogetul** [openplayerjs/openplayerjs#409]
I'm sorry to reopen this topic, but I keep having problems with subtitles on the iPhone in fullscreen format. For the .srt subtitles they do not appear at all in full screen mode and for the .vtt ones they appear but with visible changes to the font size (very reduced) and the subtitle background (enlarged). For the Romanian language it is a srt file and for English it is a vtt file. 
I mention that I have no additional script other than the basic one of the player.
All can see http://test.workpage.ro/index.html

**Comment by rafa8626** [comment]
@Dacogetul I’ll take a look at it this week and get back to you

**Comment by rafa8626** [comment]
@Dacogetu I’ve tried to access the URL that you posted but no luck. Could you post this in a CodePen or similar to check your issue?

**Comment by Dacogetul** [comment]
OK. Here are codepen: https://codepen.io/Dragos-Brojbeanu/pen/rNoLPEm , but in fact is your code from Getting Started and can change with your video and subtitles sources. Thank you.

**Comment by rafa8626** [comment]
@Dacogetul I finally remembered the source of your problem: QuickTime Player (the default player when you go full screen mode in iOS) doesn’t support SRT files; that’s why in my documentation never mentioned SRT, since VTT is cross browser/cross device compatible. Read https://multimedia.easeus.com/amp/ai-article/how-to-add-subtitles-in-quicktime-player.html.

For your other problem, use CSS to enlarge the font by using the `::cue` pseudo selector. Let me know if that helps you

**Comment by Dacogetul** [comment]
Not work for me: see here: https://codepen.io/Dragos-Brojbeanu/pen/rNoLPEm .
english language have .vtt subtitle. 
I'm really curious...did it work for you?
Tank you !!

**Comment by rafa8626** [comment]
@Dacogetul your URLs don’t work for me. I tried with a different VTT file and worked for me. I tried to access the URLs outside of CodePen and I always have an error since they can’t be reached

**Comment by Dacogetul** [comment]
I don't know why my url doesn't work for you as long as it works on codepen. Probably your internet provider is blocked with the entire range of ips on my server due to the large number of hackers in your network like DIgitalocean, Palo alto, etc. But that is not important. You can see on codepen that the English file is vtt and in working condition (recognized and run by the player). So you can open the provided codepen link in any iphone and if you run the movie with English subtitles it works in the player but if you change to fullscreen the English subtitles disappear. Can you give me an example using the player script with your movie and subtitle sources in a codepem. Thank you in advance!

**Comment by rafa8626** [comment]
The CodePen doesn’t work for me: I never get to play the movie at all. I’m going to test the switching back and forth between normal and fullscreen mode to see if I see subtitles correctly and I’ll post my code once I do it

**Comment by Dacogetul** [comment]
Thank you very much and I look forward to a link from you.
I thank you very much again.

**Comment by rafa8626** [comment]
@Dacogetul this CodePen works with captions in full screen using a hack by setting the default the default selection for QuickTime, but won’t work if you are not in full screen, so I need to check that: https://codepen.io/rafa8626/pen/NWmrKbW

**Comment by rafa8626** [comment]
I’ll take a look at this and get back to you as soon as I can

**Comment by rafa8626** [comment]
@Dacogetul I’m going to try to look at this and have an update for you by the end of the week. Apologies for the delay

**Comment by rafa8626** [comment]
@Dacogetul please test the master branch; I refactored the code to make this work properly, and I removed support for remote captions using the old flow since there are better ways to do this now. I'll add some documentation about this as soon as you approve this, and then I can release the change for good. Let me know if it worked for you. (Note: this won't work in CodePen at all, since captions rely on same-origin policies)

**Comment by Dacogetul** [comment]
with  min.js and min .css it doesn't work at all anymore and in the player settings both languages remain checked... anyway it doesn't show anything

**Comment by Dacogetul** [comment]
Sorry Sir but you did you at least test once you modified.?? On any platform? What platform work for you? I would like to try too..

**Comment by rafa8626** [comment]
I used the unminified files to test this. Everything worked on my test and I tested it in Chrome, Safari and iOS to test the fullscreen.

**Comment by rafa8626** [comment]
@Dacogetul I used this for test
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./dist/openplayer.min.css" />
    </head>
    <body>
    <video class="op-player__media" id="player" playsinline>
        <source src="https://github.com/mediaelement/mediaelement-files/blob/master/big_buck_bunny.mp4?raw=true" type="video/mp4" />
        <track srclang="ro" label="Romanian" src="./romanian.vtt" kind="subtitles" />
        <track default srclang="en" label="English" src="./english.vtt" kind="captions" />
    </video>
    <script src="./dist/openplayer.js"></script>
    <script>
        // Check the `API and events` link below for more options
        const player = new OpenPlayerJS('player');
        player.init();
    </script>
</body>
</html>
```

**Comment by Dacogetul** [comment]
Hello.
I downloaded the master code from openplayerjs and copied the dist folder to the root of my site, and then copied your code into the html (page). I replaced the paths for the movie and subtitles with my own, like this: 

<html>
<body>

<!doctype html>
--
  | <html>
  | <head>
  | 
  | <title>index</title>
  | <meta name="viewport" content="width=device-width, initial-scale=1.0">
  | <link href="test.css?v=3" rel="stylesheet">
  | <link href="index.css?v=3" rel="stylesheet">
  | <link rel="stylesheet" href="http://test.workpage.ro/dist/openplayer.min.css" />
  |  
  | </head>
  | <body>
  | <video class="op-player__media" id="player" controls playsinline>
  | <source src="http://test.workpage.ro/openplayerjs/videoteca/videoplayback.mp4" type="video/mp4" />
  | <track kind="captions" src="openplayerjs/videoteca/english.vtt" srclang="en" label="English" />
  | <track kind="subtitles" src="openplayerjs/videoteca/romana.srt" srclang="ro" label="Romana" default />
  | </video>
  | <script src="http://test.workpage.ro/dist/openplayer.min.js"></script>
  | <script>
  | // Check the `API and events` link below for more options
  | const player = new OpenPlayerJS('player');
  | player.init();
  | player.getElement().addEventListener('canplay',() => {
  | player.getElement().querySelector('track').default = true;
  | });
  |  
  | </script>
  |  
  | </body>
  | </html>


</body>
</html>

The result being the following:
in EDGE and Chrome work subtitle .srt (with subtitles) and .vtt (with captions) (normal website view + fullscreen mod).
In IOS 17.4 and IOS 17.4.1 work both .srt and .vtt in normal view website  in the vertical and horizontal position of the phone, but when I press the fullscreen button, no .vtt or .srt subtitles are visible (I understood that IOS does not support .srt).
In chrome on the phone when put this in horizontal position de movie size do not keep de screen size is large it is larger than the screen in both length and width and the subtitles have reduced dimensions for both versions of subtitles.srt or .vtt.

**Comment by rafa8626** [comment]
@Dacogetul can you send me screenshots of the issues with Chrome and full screen please? I need to see what you are seeing

**Comment by Dacogetul** [comment]
No issue with Chrome on PC."In EDGE and Chrome work subtitle .srt (with subtitles) and .vtt (with captions) (normal website view + fullscreen mod)." 
![Chrome on phone](https://github.com/openplayerjs/openplayerjs/assets/18350449/9b927141-4cce-408e-b95e-8d9de92dbc1a)

In fullscreen Chrome works fine but no subtitle.

**Comment by rafa8626** [comment]
@Dacogetul can you test this removing these lines from your code?
```javascript
player.getElement().addEventListener('canplay',() => {
   player.getElement().querySelector('track').default = true;
   });
```
These shouldn't be needed

**Comment by Dacogetul** [comment]
The same problems exist without the 2 lines both in fullscreen Chrome on the iPhone and PC and in Safari on the iPhone. But I suspect that for the size of the player, a div must be used to adapt, but the subtitle problem persists. The player in Safari cannot take over the subtitle in fullscreen even though I tried all the possible settings of the phone.

**Comment by rafa8626** [comment]
OK let me check that and get back to you, since it works on my end, but I'm on iOS 16

**Comment by rafa8626** [comment]
@Dacogetul these screenshots came from iOS 17.2, just FYI
<img width="857" alt="Screenshot 2024-03-24 at 12 31 22 PM" src="https://github.com/openplayerjs/openplayerjs/assets/910829/b42839c7-ac43-4905-8a3f-29221a20aff7">
<img width="862" alt="Screenshot 2024-03-24 at 12 31 32 PM" src="https://github.com/openplayerjs/openplayerjs/assets/910829/7d110398-a3a3-4865-9cf9-1cbe7e3c71c9">

**Comment by Dacogetul** [comment]
Can send me your code with html here ? To check on my website?

**Comment by rafa8626** [comment]
@Dacogetul it's the same code I sent you before; I used the dist files to test it; the captions are stored locally to aovid any CORS issues

**Comment by rafa8626** [comment]
@Dacogetul just FYI, I obtained the same results in 17.4

**Comment by Dacogetul** [comment]
What is FYI ? I'm not familiar with the terms...I'm not a programmer..  :) :)

**Comment by rafa8626** [comment]
Correct :) it’s an English abbreviation of for your information :)

**Comment by Dacogetul** [comment]
For me not work in iphone full scree after push this button >>>>>
<img width="857" alt="1" src="https://github.com/openplayerjs/openplayerjs/assets/18350449/bafc5a00-c84f-49a2-acfc-88df1b004657">

**Comment by rafa8626** [comment]
That’s weird, because that’s exactly how I did it and I could see the captions shown previously. Quick question: do you have enabled closed captions + SDH in your phone? 
![Uploading IMG_3716.jpeg…]()

**Comment by Dacogetul** [comment]
Yes ...work for me but my website  not refreshing and most restart the server. Initially I did not change openplayer.min.js with openplayer.js in the script page. I had not noticed this, then when I carefully read the code I saw this. How would it be better to use the path for files with subtitles .vtt captions or subtitles or is there no difference? I saw that you used both versions and they work... I suspect that in future updates or versions I will only use the openplayer.js file.
Please consider that this problem has been solved.. Thank you very much!!!

**Comment by rafa8626** [comment]
That means that your files are cached probably and you should clear the cache. I’m planning to just have 2 versions (esm and cus of umd) so that way are less files and adapted to modern browsers and less code footprint. But that will come in another version. I’m glad your issue is solved. I’ll release this fix once I add some documentation about captions

**Comment by Dacogetul** [comment]
For the future, do you think you could bring an additional setting regarding the font size where the wheel and the language is chosen?

**Comment by rafa8626** [comment]
Since all of that is controlled by CSS I wasn’t planning on it. I’m leaving that to each person to decide what’s the best path for their project
