### ISSUE TITLE
Player starts with sound on

### ISSUE THREAD

**Issue by lamtab** [openplayerjs/openplayerjs#410]
**Describe the bug**
I am loading the player using js and I add the muted property to the video tag, however most of the time the player starts with the sound on.

**To Reproduce**
0. Use a greek IP, cause the ads have location targeting.
1. Open the following test page:
https://www.caranddriver.gr/review/arthro/odigoyme_ti_nea_bmw_x2_stin_portogalia-7829803/

**Expected behavior**
The player should appear after the second paragraph of the body and immediately start playing an ad. It is not going to be muted.

**Screenshots**
![image](https://github.com/openplayerjs/openplayerjs/assets/13386247/6938aa3a-9c6b-495e-beab-6a3842fe3ffc)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 122.0.6261.94

**Comment by rafa8626** [comment]
@lamtab I checked your page and I couldn’t find any references to OpenPlayerJS; do you mind posting your configuration to see what the problem could be?

**Comment by lamtab** [comment]
Helle @rafa8626 
Thanks for checking my test page. The video player is loaded only when there is an available ad to be shown and you need a greek ip for that to happen.

Here is my code
```javascript
thetahb.video = document.createElement('video')
      thetahb.video.setAttribute('id', 'thetahbplayer')
      thetahb.video.setAttribute('muted', '')
      thetahb.video.setAttribute('autoplay', '')
      thetahb.video.setAttribute('playsinline', '')
      thetahb.video.setAttribute('loop', '')
      thetahb.video.classList.add('op-player__media')
      thetahb.container.append(thetahb.video)

      let s = document.createElement('source')
      s.setAttribute('src', `https://assets.thetamedia.gr/theta.mp4?t=${timestamp}`)

      thetahb.video.append(s)

      thetahb.player = new OpenPlayerJS('thetahbplayer', {
        controls: {
          alwaysVisible: false,
          layers: {
            left: ['volume'],
            middle: ['progress'],
            right: [],
          }
        },
        ads: {
          loop: true,
          src: thetahb.vastUri
        }
      })
      thetahb.player.init()
```

**Comment by rafa8626** [comment]
@lamtab can you change the way you set up the video props to this and see if it works for you:
```javascript
thetahb.video.setAttribute('id', 'thetahbplayer');
thetahb.video.setAttribute('muted', '')
thetahb.video.muted = true
thetahb.video.autoplay = true
thetahb.video.playsinline = true
thetahb.video.loop = true
```

**Comment by lamtab** [comment]
Thank you for your help! Will see how it goes over the day and let you know.

**Comment by lamtab** [comment]
Hello again @rafa8626 
Everything seems fine now. Thank you for your help!

**Comment by rafa8626** [comment]
Glad to hear that :)
