### ISSUE TITLE
when call pause() in play event has error (HLS)

### ISSUE THREAD

**Issue by foadabdollahi** [openplayerjs/openplayerjs#414]
When i call pause() in play event has error (HLS):
` Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
`
```
var first = true; 
    player.getElement().addEventListener("pause", function (event) { 
        if (!first) {
           // do something
       }
        first = false;
    });

    player.getElement().addEventListener("play", function (_event) {
         if (first === true) { 
            player.getElement().pause(); 
           // do something
        
        }
        else {
           // do something else
        }
   });

```
you can see it here:
https://codepen.io/foadabdollahi/pen/poBWRNV

**Comment by rafa8626** [comment]
@foadabdollahi if you change this to `player.pause()` you won't see the error. I try to use that since it handles better the async nature of play. You can see it working properly at https://codepen.io/rafa8626/pen/BaEwdOM
