### ISSUE TITLE
HLS stream not playing on mobile android device

### ISSUE THREAD

**Issue by catkrahl** [openplayerjs/openplayerjs#416]
**Describe the bug**
HLS stream is not playing on mobile (android) devices

**To Reproduce**
1. all HLS streams on our website are not playing in the player on mobile android platforms
2. i tested the media URL (https://vz-b1816d38-f69.b-cdn.net/e50cf029-f79d-44db-9b97-44d12791f229/playlist.m3u8) of the stream on your website in the demo-player (openplayerjs.com)
3. the media URL is not playing in your demo-player (all android-browser) , accept i activate the if streaming-checkbox
4. the playback on apple devices is working

**Smartphone (please complete the following information):**
 - Device: XIAOMI MI11T
 - OS: HyperOS
 - Browser : Chrome
 - Version: 123.0.6312.118

**Additional context**
was also tested with firefox and chrome and other android devices

**Comment by rafa8626** [comment]
@catkrahl can you share your player configuration so I can take a look? Or a CodePen where I can see the issue?

**Comment by catkrahl** [comment]
@rafa8626 is it ok, to give you just an URL? here is an example where android devices fail to play the stream:
https://concepts-and-training.de/studio-format-elearning001.html

**Comment by rafa8626** [comment]
@catkrahl yes that could work; I’ll check it and get back to you

**Comment by rafa8626** [comment]
@catkrahl I was checking this in an Android emulator, and I couldn't even get a response from the direct playlist file. But I was able to check the HTML source and I see that you have a `preload` attribute with no value at all. I'm not sure if that could conflict in Android but I'd definitely remove it if it has no use for you. I'll continue checking during this week and give you an update

**Comment by catkrahl** [comment]
@rafa8626 thanks for your hint as the preload attribute was an artefact from a outdated implementation. sadly it didn't solve the anrdoid HLS stream-problem. please let me know, when you have an idea how to fix the issue.

**Comment by foadabdollahi** [comment]
@rafa8626 it seems new. maybe new chrome version restrict some codes.

**Comment by rafa8626** [comment]
> Help.. In the permalink embed for openplayerjs, is there a param to remove the progress bar that is permanently blocking the bottom of video when playing? Thanks.

@DigitalCurator not currently; what's your user case that needs this?

**Comment by rafa8626** [comment]
@catkrahl can you try to add the following option in your player's configuration and see if that helps?
```javascript
const player = new OpenPlayerJS('player', {
    forceNative: false                
});
player.init();
```

I tried with the emulator the HLS demo website and worked, so let's see if this fixes it by forcing the use of hls.js to play HLS media in Android. Let me know if it worked for you

**Comment by catkrahl** [comment]
@rafa8626: thx so much, that fixes the issue and all player instances are now playing HLS-streams on android phones!

**Comment by rafa8626** [comment]
@catkrahl great to hear! Quick question: in iOS is playing correctly after setting that flag?

**Comment by rafa8626** [comment]
> @rafa8626 it seems new. maybe new chrome version restrict some codes.
> 
> maybe it will be useful. I get this error with chrome remote debug but i can't see line of code. ![image](https://private-user-images.githubusercontent.com/13816403/324573365-787d3109-2b49-430d-b868-2df1105b6cf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjgzMDQsIm5iZiI6MTcxMzg2ODAwNCwicGF0aCI6Ii8xMzgxNjQwMy8zMjQ1NzMzNjUtNzg3ZDMxMDktMmI0OS00MzBkLWI4NjgtMmRmMTEwNWI2Y2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEwMjY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczOWRiMTg3MzY4ZjNmYTZkODhhYTkyODZkMDg4ZWRmZTIwMmY1MzdjODNkMTgwMzM3YzY0YmM3ZDRiMTlhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WipsDeQJymKyyTp6WOn7WihwQQ3DiqSYArI81uQ52OE)
> 
> after i add debug true to hls config:this error show on desktop but work fine. ![image](https://private-user-images.githubusercontent.com/13816403/324586752-d138c540-6e22-4193-b48c-d1a19aab7358.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjgzMDQsIm5iZiI6MTcxMzg2ODAwNCwicGF0aCI6Ii8xMzgxNjQwMy8zMjQ1ODY3NTItZDEzOGM1NDAtNmUyMi00MTkzLWI0OGMtZDFhMTlhYWI3MzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEwMjY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNTNiMmIxNmFlYmU3NTdmMjY3MTI5YWU1OGZkZjkyYjcwNzVjOTkzNjY3ZDUwMzY4MTExZDhiOWU0MjM3OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4pusFPGhM91jEzzOb5E9NHutU8_lRMHWeSp4qW3QviI)

When using Android, you don’t necessarily need hls.js since it should allow you to play hls media natively, unless that changed now with Android

**Comment by catkrahl** [comment]
> @catkrahl great to hear! Quick question: in iOS is playing correctly after setting that flag?

Yes, it still seems to work. At least with iPadOS. I will grap an iOS-device later but i think it should work there too!

**Comment by rafa8626** [comment]
@catkrahl let me know because if that’s the case, I’d like to submit a quick patch to set that option to false by default so we shouldn’t worry about setting this over and over

**Comment by catkrahl** [comment]
hi @rafa8626, its still working on iOS, but one instance of the player is now showing the loader-animation from the beginning of stream an does not disapear. this is only on iOS and iPadOS the case, not on android-devices:
https://www.concepts-and-training.de (header video)

**Comment by rafa8626** [comment]
@catkrahl can you add these lines in your code so I can see what event is causing the loader to keep reappearing?
```javascript
const p = playerX.getElement();
p.addEventListener('loadedmetadata', () => console.log('metadata'))
p.addEventListener('waiting', () => console.log('waiting'))
p.addEventListener('seeking', () => console.log('seeking'))
p.addEventListener('seeked', () => console.log('seeked'))
````
My gut tells me it could be the waiting event, but I want to be sure about that

**Comment by catkrahl** [comment]
@rafa8626:
i pushed your snippet to my github-pages-account:
https://catkrahl.github.io/
in my local environment all 4 messages are logged, but online not ... hope that helps!

**Comment by rafa8626** [comment]
@catkrahl that should work; I’ll check in a bit

**Comment by rafa8626** [comment]
@catkrahl I see seeking and seeked events; can you do me a favor and add 2 more, please?
```javascript
p.addEventListener('play', () => console.log('play'))
p.addEventListener('playing', () => console.log('playing'))
```
Because with the 2 events I mentioned before the loader should have disappeared, but I wanna see if these 2 new events are dispatched; otherwise, I have an alternative for you

**Comment by catkrahl** [comment]
@rafa8626: is added

**Comment by rafa8626** [comment]
@catkrahl seems like the events are occuring in different order, so to solve this, use this code after you initialize the player
```javascript
p.addEventListener('seeked', () => {
    p.getContainer().querySelector('.op-player__loader').setAttribute('aria-hidden', 'true');
})
```
Let me know if that works

**Comment by catkrahl** [comment]
sadly not!
i placed the snippet on the live-website now:
https://concepts-and-training.de after the player.init ();
 
on iOS its still there from the start of the stream and on Android it appears when the first loop of the stream is starting ...
and another thing i noticed: all click events (like the unmute- or pause-btn) forces the loader to disappear. 
hope that helps ...

**Comment by rafa8626** [comment]
@catkrahl the issue is that the variable name doesn't exist; it should be `playerX` or `player`, depending where you set the code.
<img width="1135" alt="Screenshot 2024-04-29 at 3 56 51 PM" src="https://github.com/openplayerjs/openplayerjs/assets/910829/1e0ffbb3-46ac-4867-9e0e-b25a3bf49a6f">

**Comment by catkrahl** [comment]
sry for that! i'm not a front-end developer with just very little JS-knowledge. hopefully now its ok:

`<script>
    const playerX = new OpenPlayerJS('playerX', {
        forceNative: false, 
        controls: {
            layers: {
            left: ['play'],
            middle: [],
            right: ['volume'],
            },
        },
    });
    playerX.init();

    const p = playerX.getElement();
    p.addEventListener('seeked', () => {
        p.getContainer().querySelector('.op-player__loader').setAttribute('aria-hidden', 'true');
    })
</script>`

**Comment by rafa8626** [comment]
@catkrahl what if you set the loader to be hidden initially, using `showLoaderOnInit` as true in the player configuration?
