### ISSUE TITLE
OpenPlayerJS Fails to Continue Playback and Switch Quality on HLS Streams

### ISSUE THREAD

**Issue by DimaDemchenko** [openplayerjs/openplayerjs#418]
**Bug description**
The player does not continue playback and fails to change the quality after selecting a higher quality level, showing an infinite loading spinner instead.

**Expected behavior**
The player should switch to the selected quality level and continue playback without interruption.

**Actual behavior**
The player stops playing and displays an infinite loading spinner when a new quality level is selected.

**To Reproduce**
1. Use provided code snippet:

```<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.css"
    />
  </head>
  <body>
    <video class="op-player__media" id="player" controls playsinline></video>

    <script src="https://cdn.jsdelivr.net/npm/openplayerjs@latest/dist/openplayer.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
    
    <script>
      const player = new OpenPlayerJS("player", {
        controls: {
          layers: {
            left: ["play", "time", "volume"],
            right: ["settings", "fullscreen", "levels"],
            middle: ["progress"],
          },
        },
      });
      player.src = {
        src: "https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8",
        type: "application/x-mpegURL",
      };

      player.init();
    </script>
  </body>
</html>
```

2. Choose a better quality level than current one
3. Observe that the player stops and does not resume playback or change quality.

**Screenshots**
Infinite loading after quality change
![image](https://github.com/openplayerjs/openplayerjs/assets/91938357/7fba6ba0-4efe-4092-bef9-80c776e74275)
![image](https://github.com/openplayerjs/openplayerjs/assets/91938357/a2b91940-4dc9-4749-9890-11715428d3cc)

**Desktop**
 - OS: Kubuntu 23.10
 - Browse: Chrome 
 - Version 124.0.6367.60 (Official Build) (64-bit)

The same bug I got on my smartphone.
**Smartphone:**
 - Device: Iphone 14
 - OS: IOS 17.4.1
 - Browser Safari

**Additional Comments and Request for Assistance** 
Player didn't throw any errors in console.

I would appreciate your assistance in investigating this issue. If there are any configurations or steps that I might have overlooked, please feel free to point them out. Your help in resolving this matter would be greatly valued.

Thank you for your time and support.

**Comment by rafa8626** [comment]
@DimaDemchenko thanks for raising this issue; I’ll take a look at it next week and give you an update as soon as I can

**Comment by rafa8626** [comment]
@DimaDemchenko please download the master branch and use the snippet you posted above, but change the configuration to the following:
```javascript
const player = new OpenPlayerJS("player", {
        controls: {
          layers: {
            left: ["play", "time", "volume"],
            right: ["settings", "fullscreen", "levels"],
            middle: ["progress"],
          },
        },
        hls: {
            "debug": true,
            "enableWorker": true,
            "lowLatencyMode": true,
        }
 });
```
I added a new way to change the quality levels to use smooth switching, and that should help. Let me know if it works for you. Thanks

**Comment by DimaDemchenko** [comment]
I tried and it works as expected

**Comment by rafa8626** [comment]
@DimaDemchenko thanks for testing this! I’ll release this formally next week
