### ISSUE TITLE
Subtitle size with css

### ISSUE THREAD

**Issue by rafa8626** [openplayerjs/openplayerjs#419]
### Discussed in https://github.com/openplayerjs/openplayerjs/discussions/417

<div type='discussions-op-text'>

<sup>Originally posted by **Dacogetul** April 24, 2024</sup>
I don't know what else to do to be able to change the font sizes of the subtitles depending on the screen size. I tried to add a style.css file in the head and in the file I tried the @media-screen option for example:

`@media screen and (max-width: 360px) {
.op-captions {
 font-size: 12px !important;
 }
}

@media screen (min-width: 361px) and (max-width: 800px) {
.op-captions {
 font-size: 16px !important;
 }
}

@media screen (min-width: 801px) and (max-width: 1080px) {
.op-captions {
 font-size: 24px !important;
 }
}
@media screen (min-width: 1081px) and (max-width: 1800px) {
.op-captions {
 font-size: 26px !important;
 }
}
@media screen and (min-width: 1801px) {
.op-captions {
 font-size: 28px !important;
 }
}
`
and don't working... Can somebody show me how can do that..?</div>

**Comment by rafa8626** [comment]
@Dacogetul please check this test and let me know if it worked for you, since all worked on my side: [_test_.zip](https://github.com/openplayerjs/openplayerjs/files/15279320/_test_.zip). If so, I'll release the fix by next week

**Comment by Dacogetul** [comment]
It works, but there's still one thing left that still doesn't work....turning off the subtitles doesn't work either from the "CC" or "OFF" button in the settings. This doesn't bother me, but I say this for the overall functionality of the player, which for me has now become the best (it works on all types of browsers, including older Samsung TVs - so I don't have to buy another one :) ) .
I have not checked if the settings of the subtitles (position and size of the font) can still be made as we discussed previously. can the .DS_Store and ._.DS_Store files be placed anywhere or only where is the folder containing the page with the player? I would hide it elsewhere, for example in dist or in another folder.

**Comment by rafa8626** [comment]
@Dacogetul I’ll check why that doesn’t work and get you a fix, since I’d like to release this patch soon. Those DS folders are not supposed to be included, since there are OSX files, so they would be ignored

**Comment by rafa8626** [comment]
@Dacogetul please test these new files, and let me know if all works now. Also, I'm curious to know if these files will work in your old Samsung TV: 
[_test_.zip](https://github.com/openplayerjs/openplayerjs/files/15282841/_test_.zip)

**Comment by Dacogetul** [comment]
Now the subtitles don't show at all...

**Comment by rafa8626** [comment]
How are not seeing them? Do you have specific steps?

**Comment by Dacogetul** [comment]
I extracted the archive to the desktop and moved the subtitles to the dist folder and now I have index.html on the desktop, the dist folder and the .DS_Store file. Then I made the appropriate changes in index.html and started the player. The movie plays but none of the subtitles work.
Here is index.html :
`<!DOCTYPE html>
<html>
    <head>
        <title>Test</title>
        <link href="dist/openplayer.min.css" rel="stylesheet" />
    </head>
    <body>
        <video class="op-player__media" id="player" controls playsinline>
            <source src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" type="video/mp4" />
            <track kind="subtitles" src="dist/engleza.vtt" srclang="en" label="English" />
            <track kind="subtitles" src="dist/romana.vtt" srclang="ro" label="Romana" default />
        </video>
        <script src="dist/openplayer.min.js"></script>
        <script>
            const player = new OpenPlayerJS('player');
            player.init();
        </script>
    </body>
</html>`

**Comment by rafa8626** [comment]
@Dacogetul Try this one: 
[tests.zip](https://github.com/openplayerjs/openplayerjs/files/15283273/tests.zip)

**Comment by Dacogetul** [comment]
I'm sorry for making you wait, but it took me some time to test on browsers, the player and here is the result:
Now I can finally say that everything is perfect. I hope that the additional css settings that I talked about above will continue to work, in the sense of increasing the font and positioning the subtitle in relation to the lower limit of the player, both with and without control. For details, I used EDGE, Chrome, Arc browser on PC including fullscreen mode as well as on Samsung 4k/UHD TV - 2015 with browser with Tizen 2.4 player as well as Samsung 2024 with Tizen 8 player on browser.
Now you can close the topic....thank you very much....
PS : :) if my font settings don't work, I'll contact you, but I hope that's not the case... Have a good day....

**Comment by rafa8626** [comment]
@Dacogetul awesome! The CSS rules that I gave you should work as expected, since nothing in the markup changed with this fix. I’m glad that it’s finally working as it should! Thanks for reporting this
