### ISSUE TITLE
crypto interface: TypeError: Illegal invocation

### ISSUE THREAD

**Issue by stewartrule** [openplayerjs/openplayerjs#424]
Aliasing `crypto` and calling `getRandomBytes` or `getRandomValues` without a `this` context results in a `TypeError: Illegal invocation`
https://github.com/openplayerjs/openplayerjs/blob/dfc3913b68c64aeaf08dfa3fe6055788987a448a/src/js/player.ts#L601

This happens immediately on `player.init()`

```js
alias = crypto.getRandomValues;
alias(new Uint32Array(1))
VM296:2 Uncaught TypeError: Illegal invocation
    at <anonymous>:2:1
```

```js
crypto.getRandomValues(new Uint32Array(1))
Uint32Array [524111001, buffer: ArrayBuffer(4), byteLength: 4, byteOffset: 0, length: 1, Symbol(Symbol.toStringTag): 'Uint32Array']
```

**Comment by stewartrule** [comment]
Hi @rafa8626 I don't need to alias it. It's being aliased within `_createUUID` (line 602-603) which is causing the error:

https://github.com/openplayerjs/openplayerjs/blob/dfc3913b68c64aeaf08dfa3fe6055788987a448a/src/js/player.ts#L596-L605

We just noticed it because we were initializing the player in `componentDidMount`, which is called twice in React strict mode. The first time `_createUUID()` is called, the id will be removed with `this.#element.removeAttribute('id');`, so the second time it tries to generate a random uid which fails because of the aliasing. I think this will also happen to anyone who hasn't manually added an id to the media element.

**Comment by rafa8626** [comment]
@stewartrule thanks, I’ll take a look. Could you also give the project a star to show your support, please?

**Comment by rafa8626** [comment]
@stewartrule please use the new version of the player and let me know if all worked as expected. You were right: I was able to reproduce the issue by not setting the element ID, and I was able to fix it by removing the alias and using the Web Crypto API. Thanks for reporting this

**Comment by stewartrule** [comment]
@rafa8626 can confirm it is working again. Thanks!
