### ISSUE TITLE
Сreation of an additional control button.

### ISSUE THREAD

**Issue by supersh86** [openplayerjs/openplayerjs#45]
Hi Rafa.
I was thinking about customizing the elements of the player.
I think it would be great to make a simple api in the configurator, to add new controls buttons.

**Comment by rafa8626** [comment]
@supersh86 what type of buttons you would like to add?

**Comment by supersh86** [comment]
For example, I want to add a button showing users of p2p online.
By the way, recently hlsjs-p2p-engine included your player in the list of examples, congratulations.

Others, for example, will be interested in changing video quality.

You could do some standard setup method, for example

addButton {
icon : '/.png',
title : 'button',
clickFunc=function(){
....
}
}

**Comment by rafa8626** [comment]
@supersh86 Thanks for the heads up! I didn't know my player was considered for `hlsjs-p2p-engine`

I'll check what I can do for this and keep you posted

**Comment by rafa8626** [comment]
@supersh86 check the `feature/add-control` branch I created. Play with the demo file and let me know if that works for you, before I merge this into master. Thanks

**Comment by supersh86** [comment]
[!Imgur](https://i.imgur.com/SoRTI7x.png)
It works, but there is an error when placed on the right, the icon appears at the most extreme point, on the right of the full screen mode.

I think it will be more correct to place it in front of the speed settings icon.

**Comment by rafa8626** [comment]
@supersh86 thanks for noticing that. I've changed that and it should be working as expected. If you check the demo, I'm using a style to fix the height of that specific button so it is considered the visual manipulation of it. Let me know if it works for you

**Comment by supersh86** [comment]
![Imgur](https://i.imgur.com/tLB4ohe.png)
I think this layout is much more intuitive(habitual) than this.
![Imgur](https://i.imgur.com/KNQu3TI.png)

**Comment by supersh86** [comment]
In any case, you can already do the master.

**Comment by rafa8626** [comment]
Done. Thanks for testing this. Closing issue now

**Comment by supersh86** [comment]
Rafa hello, I found a serious error in this function.
If the button is added after the user enters the full-screen mode, then after adding the user from the full-screen mode, he can no longer exit.

I made an example with a 5 second button call timeout. If at the very beginning you click on fullsreen and then a button appears, you can’t exit the full screen mode anymore.
https://codepen.io/anon/pen/qgqZgx

**Comment by rafa8626** [comment]
@supersh86 This is fixed now in the master branch; please confirm so I can close this issue. Thanks for reporting this

**Comment by supersh86** [comment]
it's fix! Thanks!
