### ISSUE TITLE
Lost connection with HLS after server restart.

### ISSUE THREAD

**Issue by supersh86** [openplayerjs/openplayerjs#47]
Hello Rafa, last I started noticing the problem of reconnecting after a server crash.

  If the streamer program reboots on the server and the openplayer loses connection, then after the server has been restored, the player cannot connect back, thereby destroying the user's session.

I tested on the players
  hls.js demo
https://video-dev.github.io/hls.js/demo/

cdnbye demo
https://demo.cdnbye.com

In these demos, I launched the player, allowed the player to be buffered, and then restarted the VOD server.
They have no problems with recovery, but openplayer has it.

**Comment by rafa8626** [comment]
I will need an example to replicate this and see what we can do about it; it's a more complex scenario than the ones I've seen

**Comment by supersh86** [comment]
Tell me the date and time, I will try to make a server by this time that will reset via cron every 3 minutes.

**Comment by rafa8626** [comment]
If you can set it up today in like 3 hours I may check it. If I need you to put it back another day I’ll let you know, if it’s not a simple fix

**Comment by supersh86** [comment]
sorry.
I guess I was wrong.
