### ISSUE TITLE
The video starts before the advertisement.

### ISSUE THREAD

**Issue by supersh86** [openplayerjs/openplayerjs#5]
Rafa I found for you a new bug.

My users, who are very far from the server with advertising, have problems with premature video launch.

The video starts before the advertisement, the control elements do not work. If you press the pause, the Preroll starts.

I simulated this problem through Chrome using slow internet settings.

![Imgur](https://i.imgur.com/0wc6pRP.png)
![Imgur](https://i.imgur.com/P7ORzpi.png)
![Imgur](https://i.imgur.com/6AAMhTi.png)
![Imgur](https://i.imgur.com/xqlhJzO.png)
![Imgur](https://i.imgur.com/4jIUeaB.png)

**Comment by rafa8626** [comment]
I’ll check this. Thanks for reporting it

**Comment by rafa8626** [comment]
@supersh86 Please download the master branch and let me know if it worked for you. It's tricky, but I think with the flag I implemented to detect if the play was requested, it should help to play the Ads correctly under the scenario you specified. Please let me know

**Comment by supersh86** [comment]
It looks like it works. Thank you

**Comment by rafa8626** [comment]
You are welcome. Thanks for testing this!
