### ISSUE TITLE
Several sources for video.

### ISSUE THREAD

**Issue by supersh86** [openplayerjs/openplayerjs#50]
Hello Rafa!
 When adding an additional source to the video, I noticed that the second source is not added to the hls.levels
```
<video>
<source src="..." type="application/x-mpegURL">
<source src="..." type="application/x-mpegURL">
</video>
```

**Comment by rafa8626** [comment]
The default mechanism is to only play the first playable source, mimicking what the browsers do by default

**Comment by supersh86** [comment]
And he should not play. It should be on the levels list.
If the first source fails, hlsjs switches to the second.
I tried to do it manually, but this should happen before initialization.

**Comment by rafa8626** [comment]
got it; I'll check this and let you know when fixed

**Comment by supersh86** [comment]
I re-read the hlsjs documentation.
I think this is their problem.
I left a question in their branch and am waiting for an answer.

**Comment by rafa8626** [comment]
Ok keep me posted on this to know if it’s something I need to do or it’s them

**Comment by supersh86** [comment]
Hello rafa
I Hls.js said that there is no support.
But they advised me to make a playlist myself.
I made a playlist and specified the file address in test.php and your player could not load it. I tried on safari and on another player, there were no problems.
Do you have a dependency on the file extension?

**Comment by rafa8626** [comment]
Yes you will have to at least indicate the `type` of the source as `application/x-mpegURL` to make it work

**Comment by rafa8626** [comment]
Send me the URL just for reference so I can set an example with an atypical URL and check at the same time if it works

**Comment by supersh86** [comment]
Test it
https://anime.anidub.com/player/test.php

**Comment by rafa8626** [comment]
Ok let me take a look; meanwhile, can you list advantages that I can put on the README file so it looks more attractive to the users?

**Comment by supersh86** [comment]
Really sorry, I was very busy with another project.

1 All in one, this player does not need plug-ins, everything is already compiled by the author. This is very important for a quick start, because like the same videojs, some plugins become irrelevant, and the creators stop supporting them.
2 multivast, the ability to make a vast playlist from several sources. As it turned out, there is no such function in other players.
3 The ability to add your own buttons, I did not see this either.

Just think about the template builder, many users don’t like the single design.

**Comment by supersh86** [comment]
If you need a sample code for several sources, I will leave it here too.


    $return = "#EXTM3U\n";

        $return .= "#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=11739585,RESOLUTION=1920x1080\n";
        $return .= "https://cdn1.com/video.m3u8"."\n";
        $return .= "#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=11739585,RESOLUTION=1920x1080\n";
        $return .= "https://cdn2.com/video.m3u8"."\n";
header("Content-type: application/x-mpegURL");
echo $return;

**Comment by rafa8626** [comment]
Nevermind I didn't see the link you sent of the VideoJS builder. I'll check it out and play with some approaches

**Comment by supersh86** [comment]
Well, waiting for your test with loading playlist with php.

**Comment by rafa8626** [comment]
It can't play I need to check why is it not playing

**Comment by rafa8626** [comment]
@supersh86 It should be fixed now; please download the master branch and test this. Thanks for the suggestions on the builder and the advantages I can include

**Comment by rafa8626** [comment]
If you can give me an example of a multi VAST setup like the one you describe I could elaborate more on it, since you indicate it's rare on a player to do that

**Comment by supersh86** [comment]
Usually advertisers take only part of the traffic. And as a result, users view only 10% of the possible advertising per day. Therefore, for the site you need to connect multiple streams Vast.

Another very important thing is that the user leaves the cookie, the advertiser, so it will not work to parse through the server.
