### ISSUE TITLE
Start video from the designated second.

### ISSUE THREAD

**Issue by supersh86** [openplayerjs/openplayerjs#54]
Hello Rafa
I have a new request.
Can you add a setting in the initial configurator that starts the video from the specified second?
For example, the beginning of the video from 15 seconds instead of the first. This will make remembering the last time for the user as on YouTube.

Also, you should be more attentive to the documentation, for many ignorant users it is not very clear all the advantages of your player.
For example, a list of Vast do not have any other players. You should make it one of the important advantages.

**Comment by rafa8626** [comment]
Ok I’ll check this. What are some of the advantages you have found by using this player as opposed to others? Sometimes it’s difficult for me to compare them since I haven’t invested time on using more than 2

**Comment by rafa8626** [comment]
@supersh86 The feature is ready in the master branch under the `startTime` configuration in the element (see the configuration section in the README). Let me know if that works, and if you have any suggestions for advantages to include in the README file, I'd appreciate it. Thanks
