### ISSUE TITLE
Android ima problem

### ISSUE THREAD

**Issue by supersh86** [openplayerjs/openplayerjs#57]
Hi Rafa!
I recently discovered a problem with running a video on an android phone with embedded advertising.
The video simply does not want to load the manifest.
Check out my example.

https://codepen.io/anon/pen/LqzEKr

**Comment by supersh86** [comment]
Also on the android in the browser chrome does not work seeking

**Comment by rafa8626** [comment]
I don't have access right now to an Android device but I'll try to get one; what version are you using?

**Comment by rafa8626** [comment]
I tried on Browserstack with Android 8 and it worked fine on the main website; I don't know if it's a CodePen issue
