### ISSUE TITLE
features request add ad playback time.

### ISSUE THREAD

**Issue by supersh86** [openplayerjs/openplayerjs#58]
Hello!
Is it possible to set advertising time during initialization?
setAdtime: 15 (seconds)
After which google ima will destroy?

Sometimes advertising can hang, or have inconsistent time. When instead of the stipulated 10 seconds, it may seem 1-2 minutes.

It would also be cool to show a timer in a separate element.

**Comment by rafa8626** [comment]
I'll need to explore this; it may be a simple feature but I need to check how to transition correctly from the Ad to the media

**Comment by rafa8626** [comment]
@supersh86 sorry for not following up on this; I tried to check how much time it will take but it’s not as simple since everything is connected via IMA and I’m not sure if I can alter the behavior of the Ad that easily but I’m still exploring my options in here. Thanks for your patience

**Comment by rafa8626** [comment]
@supersh86 do you still need this feature?

**Comment by rafa8626** [comment]
Closing this for now. We can reopen this ticket if the request comes back
