### ISSUE TITLE
Desactivate autoplay

### ISSUE THREAD

**Issue by frequeradio** [openplayerjs/openplayerjs#63]
Hi ! Is there possible to desactivate the autoplay ? or at least to preload the file ? 

thanks !

**Comment by rafa8626** [comment]
Everything is driven by the HTML tags, so if you remove the `autoplay` it should help you. Otherwise, share a CodePen to see the issue

**Comment by rafa8626** [comment]
and please give a star to the project if you found it useful :)

**Comment by frequeradio** [comment]
You got the star ! It is really a good project.
https://codepen.io/frequeradio/pen/zbgqOg  
You see, the mp3 file loads although i put preload tag to none   (there is no autoplay but i'm try to avoid the  preload too)

**Comment by rafa8626** [comment]
Thanks and sorry for the late response; I have pushed a fix for that, so please check the master branch and let me know if it worked for you.

**Comment by frequeradio** [comment]
works perfectly :) thanks a lot !

**Comment by rafa8626** [comment]
I'm glad. Please invite your friends to star the project to support it please
