### ISSUE TITLE
Feature Request: Allow xml strings as vast source

### ISSUE THREAD

**Issue by eikenilsknopp** [openplayerjs/openplayerjs#70]
I would like to load a string containing a valid vast xml into the player instead of an url.
This can be achieved by extending the  _requestAds() function:

```javascript
private _requestAds(): void {
  const XML_REGEX_CHECK = /(<.[^(><.)]+>)/ig;
  const currentAds = Array.isArray(this.ads) ? this.ads[this.currentAdsIndex] : this.ads;
  
  this.adsRequest = new google.ima.AdsRequest();
        
  if (XML_REGEX_CHECK.test(currentAds)) {
    this.adsRequest.adsResponse = currentAds;
  } else {
    this.adsRequest.adTagUrl = currentAds;
  }

  const width = this.element.parentElement.offsetWidth;
  const height = this.element.parentElement.offsetWidth;
  this.adsRequest.linearAdSlotWidth = width;
  this.adsRequest.linearAdSlotHeight = height;
  this.adsRequest.setAdWillAutoPlay(this.autoStart);
  this.adsRequest.setAdWillPlayMuted(this.autoStartMuted);
  this.adsLoader.requestAds(this.adsRequest);
}
```

Unforunatly I do not have the rights to open a PR myself so it would be great if someone of the team could have a look at this.

Cheers

**Comment by rafa8626** [comment]
@eikenilsknopp I'll take a look at this and get back to you

**Comment by rafa8626** [comment]
@eikenilsknopp Please test the master branch and let me know if it works for you. Thanks for suggesting this

**Comment by eikenilsknopp** [comment]
@rafa8626 Yes this seems to be working. Thanks for the quick implementation!

**Comment by rafa8626** [comment]
Thanks for the suggestion.
