### ISSUE TITLE
Ad error: AdError 1010: The ad response was not understood and cannot be parsed.

### ISSUE THREAD

**Issue by arnabadg17** [openplayerjs/openplayerjs#72]
No ads are showing. 

Ad error: AdError 1010: The ad response was not understood and cannot be parsed. is showing in the console log.

**Comment by rafa8626** [comment]
Can you provide a CodePen or example that I can use to reproduce this please?

**Comment by arnabadg17** [comment]
@rafa8626 you can that error for its own website. https://www.openplayerjs.com/

just follow the console log.

thanks.

**Comment by rafa8626** [comment]
@arnabadg17 I have fixed this and I will deploy a new release later today. Thanks for pointing this out and please star the project to support it

**Comment by rafa8626** [comment]
Deployed new version with fix. Thanks

**Comment by arnabadg17** [comment]
@rafa8626 problem solved on its website. though I am not tested yet on localhost. thanks.

**Comment by arnabadg17** [comment]
tested on localhost. it works now. thanks.

**Comment by rafa8626** [comment]
Thanks for reporting this

**Comment by fabiomagnoni** [comment]
Hello I'm using IMA SDK and I'm getting this kind of error only on mobile, what was the issue you faced to solve this problem?
