### ISSUE TITLE
Video replay not working after post-roll

### ISSUE THREAD

**Issue by arnabadg17** [openplayerjs/openplayerjs#73]
Hey, @rafa8626 found a new bug on the latest dependency. 

Video replay is not working with any buttons or even seeking after post-roll ad. 

`error on the console log => "Uncaught (in promise) DOMException  (index):1 "`

**Comment by rafa8626** [comment]
Thanks I’ll check this soon

**Comment by rafa8626** [comment]
@arnabadg17 Please test the master branch; I have included a fix to solve this potential issue

**Comment by arnabadg17** [comment]
@rafa8626 yes problem has been solved. thank you.

**Comment by rafa8626** [comment]
Thanks for checking this
