### ISSUE TITLE
Feature Request: Add Quality Control

### ISSUE THREAD

**Issue by arnabadg17** [openplayerjs/openplayerjs#76]
If possible please add qulity control feature e.g. 360p, 480p, 720p, 1080p etc.

**Comment by ctaity** [comment]
Yes please, for HLS at least

**Comment by rafa8626** [comment]
Thanks, I’ll scope the effort to integrate this for regular video and HLS (and possibly M-DASH) and get back to you guys.

@ctaity please star the project to support it

**Comment by rafa8626** [comment]
@ctaity and @arnabadg17 I’m working on this and I should have it ready soon. I’ll keep you posted. Thanks for your patience and please star the project to support it

**Comment by rafa8626** [comment]
@ctaity @arnabadg17 just to give you an update: I'm almost done with HLS and DASH formats to display levels; I'm just trying to wrap up a couple of things in terms of replaying media correctly and finishing a couple of missing things for HTML5 levels. You can check the progress in the branch `quality-switch`. Thanks for your patience

**Comment by rafa8626** [comment]
@ctaity @arnabadg17 I finished the whole feature for levels; please take a look and let me know if it's good to go. Thanks for your suggestions

**Comment by ctaity** [comment]
I will test the feature in this or next week thanks

**Comment by rafa8626** [comment]
thanks for your help @ctaity please star the project to support it

**Comment by rafa8626** [comment]
@ctaity any updates? Am I good to merge this?

**Comment by rafa8626** [comment]
I merged this branch already so any bug fixes will come up after the release of this feature
