### ISSUE TITLE
Add hls src after ajax call

### ISSUE THREAD

**Issue by mahdi-gh1373** [openplayerjs/openplayerjs#79]
```
      <video id="oneplayer" class="op-player op-player__media" controls playsinline>
                        <source src="" type="application/x-mpegURL">
      </video>   
.......
$.ajax({
            url: ".....",
            type: 'GET',
            success: function (res) {
                var src = res.data.player_url;
                console.log(res.data)
                var player = new OpenPlayer('oneplayer', null, false, {
                  hls: {
                    startLevel: -1
                  }
                });
                player.src(src)
                console.log(player.getMedia())
            },
        });
```
I want to set src variable to video src but it's not ok and thr error is 'Media not set'

**Comment by rafa8626** [comment]
After instantiating the OpenPlayer class you need to use `player.init()` and to set the source you should do it like this: `player.src = ...`. See if that works and please star the project to support it

**Comment by rafa8626** [comment]
Also, remove the class op-player and see if that helps in your case

**Comment by mahdi-gh1373** [comment]
`                var player = new OpenPlayer('oneplayer', null, false, {
                  hls: {
                    startLevel: -1
                  }
                });
                player.init();
                player.src = src ; // src is string url`

I write like this but I have a error Media not set.

**Comment by rafa8626** [comment]
can you share a CodePen where I can see this error please?

**Comment by rafa8626** [comment]
Also, I'd say don't create the video `source` tag ahead of time

**Comment by rafa8626** [comment]
@mahdi-gh1373 I'll close this issue since no more activity has been recorded. Please reopen if you still experience this issue

**Comment by ignusws** [comment]
> can you share a CodePen where I can see this error please?

Same problem here. Can you please check this CodePen snippet
https://codepen.io/anon/pen/WVZgEa

**Comment by rafa8626** [comment]
@ignusws The only thing I think it's missing is to add the `src` in the video tag, even if it's empty.
Like this:
```html
<video class="op-player__media" id="video" src controls playsinline></video>
```

Let me know if that worked for you, and please star the project to show your support

**Comment by ignusws** [comment]
> @ignusws The only thing I think it's missing is to add the `src` in the video tag, even if it's empty.
> Like this:
> 
> ```
> <video class="op-player__media" id="video" src controls playsinline></video>
> ```
> 
> Let me know if that worked for you, and please star the project to show your support

This worked, thanks. I think it should be documented, because other players that I tried do not require adding this attribute to the video tag

**Comment by rafa8626** [comment]
Thanks I’ll take a look at it and set up a minor fix for this

**Comment by rafa8626** [comment]
@ignusws Fix is in place now, and I'll be releasing this soon. Thanks again for pointing that out

**Comment by rafa8626** [comment]
@mahdi-gh1373 @ignusws would you do me a favor and star the project please?
