### ISSUE TITLE
Safari Mac OS start problem

### ISSUE THREAD

**Issue by supersh86** [openplayerjs/openplayerjs#9]
Hi, after you made an online test player on your website, I got the opportunity to work with a clean player.
My suspicions are confirmed, in some places in the osx safari there are problems with the launch of the video.

https://www.openplayerjs.com/embed.html?file=https%3A%2F%2Fcdn10.anivid.nut.cc%2Fvid%2Fs1%2F10483%2F1%2F6.mp4%2Fplaylist.m3u8&type=video

Video can be revived only using recoverMediaError () hlsjs.

In chrome and firefox there are no such problems.

**Comment by rafa8626** [comment]
Which version did you try just so I can imitate the same scenario?

**Comment by supersh86** [comment]
Safari 12.0

**Comment by supersh86** [comment]
before this, there are errors bufferStalledError
![Imgur](https://i.imgur.com/9KdVeXx.png)

**Comment by rafa8626** [comment]
I just tried with Safari 11.1 and I see Network error, not `bufferStalledError`. The code already accounts for `recoverMediaError` if it's a Media error. So I can't replicate your scenario.

**Comment by rafa8626** [comment]
Unfortunately with the link your provided there's no much I can do about because it's truly a Network Error and that cannot be repaired or attempted to. If you have any suggestions in terms of how to deal with this, not including the existing workflow to deal with media errors, let me know. Otherwise, let's close this issue.

**Comment by supersh86** [comment]
I came to the conclusion that what for safari it is better to disable hls.js.
You can do api for this.

**Comment by rafa8626** [comment]
So I'll just use HLS.js for all technologies except iOS and Safari. I'll let them deal natively

**Comment by rafa8626** [comment]
Safari is now using native approach. Just pushed that fix. Closing this issue now. Thanks.
