### ISSUE TITLE
Feature Request: AdError event listener

### ISSUE THREAD

**Issue by michalisgar** [openplayerjs/openplayerjs#97]
Is it possible to expose the IMA AdError event? We need to provide a custom implementation if an ad error occurs.

**Comment by rafa8626** [comment]
@michalisgar yes I think it's possible; I'll work on it and let you know when available. Please star the project to support it

**Comment by michalisgar** [comment]
Sure thing! Thanks for your prompt response and great work on this project. :slightly_smiling_face:

**Comment by kornarakis** [comment]
Hi @rafa8626 , it would be very handy if we can have access to any kind of errors and even better if we can pass our own code as a fallback if something goes wrong with a VAST , VPAID etc .

**Comment by rafa8626** [comment]
@michalisgar @kornarakis I'll be looking at this soon, once I have some free time. Thanks for your patience.

**Comment by rafa8626** [comment]
@michalisgar @kornarakis please check the **error-event** branch and let me know if that will work for you. Once you approve I'll merge this into master

**Comment by rafa8626** [comment]
@michalisgar @kornarakis any updates on this?

**Comment by michalisgar** [comment]
Sorry about this @rafa8626, I will take a look as soon as I get home.

Thanks a lot for your time and effort on this :slightly_smiling_face:

**Comment by rafa8626** [comment]
You are welcome @michalisgar let me know if you have any questions

**Comment by rafa8626** [comment]
@michalisgar @kornarakis are we good with the implementation so I can merge it into master?
